// Code generated by `ubx sdk gen` from github_copilot. DO NOT EDIT.
package copilot

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Copilot_CustomAgents struct {
	FilePath any
	Name any
	Url any
}

type CopilotConfig struct {
	Enterprise any
	Page any
	PerPage any
}

type CopilotAttrs struct {
	// List of custom agents defined in the repository. Returns `null` if no source repository is configured.
	CustomAgents any
	Enterprise any
	Page any
	PerPage any
}

var Copilot = ubx.DataSourceBinding{
	WireType: "github_copilot",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
