// Code generated by `ubx sdk gen` from github_copilot_enterprise_content_exclusion_details. DO NOT EDIT.
package copilot

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type EnterpriseContentExclusionDetailsConfig struct {
	Enterprise any
}

type EnterpriseContentExclusionDetailsAttrs struct {
	Enterprise any
}

var EnterpriseContentExclusionDetails = ubx.DataSourceBinding{
	WireType: "github_copilot_enterprise_content_exclusion_details",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
	},
}
