// Code generated by `ubx sdk gen` from github_copilot_organization_details. DO NOT EDIT.
package copilot

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type OrganizationDetails_SeatBreakdown struct {
	// The number of seats that have used Copilot during the current billing cycle.
	ActiveThisCycle any
	// Seats added during the current billing cycle.
	AddedThisCycle any
	// The number of seats that have not used Copilot during the current billing cycle.
	InactiveThisCycle any
	// The number of seats that are pending cancellation at the end of the current billing cycle.
	PendingCancellation any
	// The number of users who have been invited to receive a Copilot seat through this organization.
	PendingInvitation any
	// The total number of seats being billed for the organization as of the current billing cycle.
	Total any
}

type OrganizationDetailsConfig struct {
	Org any
}

type OrganizationDetailsAttrs struct {
	// The organization policy for allowing or disallowing Copilot CLI.
	Cli any
	// The organization policy for allowing or disallowing Copilot Chat in the IDE.
	IdeChat any
	Org     any
	// The Copilot plan of the organization, or the parent enterprise, when applicable.
	PlanType any
	// The organization policy for allowing or disallowing Copilot features on GitHub.com.
	PlatformChat any
	// The organization policy for allowing or blocking suggestions matching public code (duplication detection filter).
	PublicCodeSuggestions any
	// The breakdown of Copilot Business seats for the organization.
	SeatBreakdown any
	// The mode of assigning new seats.
	SeatManagementSetting any
}

var OrganizationDetails = ubx.DataSourceBinding{
	WireType: "github_copilot_organization_details",
	Fields: ubx.FieldMap{
		"Org": ubx.FieldSpec{WireName: "org"},
	},
}
