// Code generated by `ubx sdk gen` from github_copilot_space_list. DO NOT EDIT.
package copilot

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SpaceList_Spaces_Creator struct {
	AvatarUrl any
	Email any
	EventsUrl any
	FollowersUrl any
	FollowingUrl any
	GistsUrl any
	GravatarId any
	HtmlUrl any
	Id any
	Login any
	Name any
	NodeId any
	OrganizationsUrl any
	ReceivedEventsUrl any
	ReposUrl any
	SiteAdmin any
	StarredAt any
	StarredUrl any
	SubscriptionsUrl any
	Type any
	Url any
	UserViewType any
}

type SpaceList_Spaces_Owner struct {
	AvatarUrl any
	Description any
	Email any
	EventsUrl any
	FollowersUrl any
	FollowingUrl any
	GistsUrl any
	GravatarId any
	HooksUrl any
	HtmlUrl any
	Id any
	IssuesUrl any
	Login any
	MembersUrl any
	Name any
	NodeId any
	OrganizationsUrl any
	PublicMembersUrl any
	ReceivedEventsUrl any
	ReposUrl any
	SiteAdmin any
	StarredAt any
	StarredUrl any
	SubscriptionsUrl any
	Type any
	Url any
	UserViewType any
}

type SpaceList_Spaces_ResourcesAttributes_Metadata struct {
	CopilotChatAttachmentId any
	FilePath any
	Height any
	MediaType any
	Name any
	Number any
	RepositoryId any
	Text any
	Url any
	Width any
}

type SpaceList_Spaces_ResourcesAttributes struct {
	CopilotChatAttachmentId any
	CreatedAt any
	Id any
	Metadata any
	ResourceType any
	UpdatedAt any
}

type SpaceList_Spaces struct {
	ApiUrl any
	BaseRole any
	CreatedAt any
	Creator any
	Description any
	GeneralInstructions any
	HtmlUrl any
	Id any
	Name any
	Number any
	Owner any
	ResourcesAttributes any
	UpdatedAt any
}

type SpaceListConfig struct {
	After any
	Before any
	Org any
	PerPage any
}

type SpaceListAttrs struct {
	After any
	Before any
	Org any
	PerPage any
	// The list of Copilot Spaces on this page of results.
	Spaces any
}

var SpaceList = ubx.DataSourceBinding{
	WireType: "github_copilot_space_list",
	Fields: ubx.FieldMap{
		"After": ubx.FieldSpec{WireName: "after"},
		"Before": ubx.FieldSpec{WireName: "before"},
		"Org": ubx.FieldSpec{WireName: "org"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
