// Code generated by `ubx sdk gen` from github_secret_scanning_pattern_configuration. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ScanningPatternConfiguration_CustomPatternOverrides {
  alertTotal?: number | Computed<number>;
  alertTotalPercentage?: number | Computed<number>;
  bypassRate?: number | Computed<number>;
  customPatternVersion?: string | Computed<string>;
  defaultSetting?: string | Computed<string>;
  displayName?: string | Computed<string>;
  enterpriseSetting?: string | Computed<string>;
  falsePositiveRate?: number | Computed<number>;
  falsePositives?: number | Computed<number>;
  setting?: string | Computed<string>;
  slug?: string | Computed<string>;
  tokenType?: string | Computed<string>;
}

export interface ScanningPatternConfigurationConfig {
  enterprise: string | Computed<string>;
}

export interface ScanningPatternConfigurationAttrs {
  /** Overrides for custom patterns defined by the organization. */
  customPatternOverrides: ScanningPatternConfiguration_CustomPatternOverrides[];
  enterprise: string;
  /** The version of the entity. This is used to confirm you're updating the current version of the entity and mitigate unintentionally overriding someone else's update. */
  patternConfigVersion: string;
  /** Overrides for partner patterns. */
  providerPatternOverrides: ScanningPatternConfiguration_CustomPatternOverrides[];
}

export const ScanningPatternConfiguration: DataSourceBinding<ScanningPatternConfigurationConfig, ScanningPatternConfigurationAttrs> = {
  wireType: "github_secret_scanning_pattern_configuration",
  fields: {
    enterprise: "enterprise",
  },
};
