// Code generated by `ubx sdk gen` from github_team_repository. DO NOT EDIT.
package team

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Repository_License struct {
	HtmlUrl any
	Key     any
	Name    any
	NodeId  any
	SpdxId  any
	Url     any
}

type Repository_Owner struct {
	AvatarUrl         any
	Email             any
	EventsUrl         any
	FollowersUrl      any
	FollowingUrl      any
	GistsUrl          any
	GravatarId        any
	HtmlUrl           any
	Id                any
	Login             any
	Name              any
	NodeId            any
	OrganizationsUrl  any
	ReceivedEventsUrl any
	ReposUrl          any
	SiteAdmin         any
	StarredAt         any
	StarredUrl        any
	SubscriptionsUrl  any
	Type              any
	Url               any
	UserViewType      any
}

type Repository_Permissions struct {
	Admin    any
	Maintain any
	Pull     any
	Push     any
	Triage   any
}

type RepositoryConfig struct {
	// The permission to grant the team on this repository. We accept the following permissions to be set: `pull`, `triage`, `push`, `maintain`, `admin` and you can also specify a custom repository role name, if the owning organization has defined any. If no permission is specified, the team's `permission` attribute will be used to determine what permission to grant the team on this repository.
	Permission any
	// path parameter, not part of the API's own resource representation
	Org any
	// path parameter, not part of the API's own resource representation
	TeamSlug any
	// path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute)
	OwnerPath any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute)
	OwnerPath2 any
}

type RepositoryAttrs struct {
	// Whether to allow Auto-merge to be used on pull requests.
	AllowAutoMerge any
	// Whether to allow forking this repo
	AllowForking any
	// Whether to allow merge commits for pull requests.
	AllowMergeCommit any
	// Whether to allow rebase merges for pull requests.
	AllowRebaseMerge any
	// Whether to allow squash merges for pull requests.
	AllowSquashMerge any
	ArchiveUrl       any
	// Whether the repository is archived.
	Archived         any
	AssigneesUrl     any
	BlobsUrl         any
	BranchesUrl      any
	CloneUrl         any
	CollaboratorsUrl any
	CommentsUrl      any
	CommitsUrl       any
	CompareUrl       any
	ContentsUrl      any
	ContributorsUrl  any
	CreatedAt        any
	// The default branch of the repository.
	DefaultBranch any
	// Whether to delete head branches when pull requests are merged
	DeleteBranchOnMerge any
	DeploymentsUrl      any
	Description         any
	// Returns whether or not this repository disabled.
	Disabled      any
	DownloadsUrl  any
	EventsUrl     any
	Fork          any
	Forks         any
	ForksCount    any
	ForksUrl      any
	FullName      any
	GitCommitsUrl any
	GitRefsUrl    any
	GitTagsUrl    any
	GitUrl        any
	// Whether downloads are enabled.
	HasDownloads any
	// Whether issues are enabled.
	HasIssues any
	HasPages  any
	// Whether projects are enabled.
	HasProjects any
	// Whether the wiki is enabled.
	HasWiki  any
	Homepage any
	HooksUrl any
	HtmlUrl  any
	// Unique identifier of the repository
	Id any
	// Whether this repository acts as a template that can be used to generate new repositories.
	IsTemplate      any
	IssueCommentUrl any
	IssueEventsUrl  any
	IssuesUrl       any
	KeysUrl         any
	LabelsUrl       any
	Language        any
	LanguagesUrl    any
	// License Simple
	License       any
	MasterBranch  any
	MergesUrl     any
	MilestonesUrl any
	MirrorUrl     any
	// The name of the repository.
	Name             any
	NetworkCount     any
	NodeId           any
	NotificationsUrl any
	OpenIssues       any
	OpenIssuesCount  any
	// A GitHub user.
	Owner any
	// The permission to grant the team on this repository. We accept the following permissions to be set: `pull`, `triage`, `push`, `maintain`, `admin` and you can also specify a custom repository role name, if the owning organization has defined any. If no permission is specified, the team's `permission` attribute will be used to determine what permission to grant the team on this repository.
	Permission  any
	Permissions any
	// Whether the repository is private or public.
	Private          any
	PullsUrl         any
	PushedAt         any
	ReleasesUrl      any
	RoleName         any
	Size             any
	SshUrl           any
	StargazersCount  any
	StargazersUrl    any
	StatusesUrl      any
	SubscribersCount any
	SubscribersUrl   any
	SubscriptionUrl  any
	SvnUrl           any
	TagsUrl          any
	TeamsUrl         any
	TempCloneToken   any
	Topics           any
	TreesUrl         any
	UpdatedAt        any
	Url              any
	// The repository visibility: public, private, or internal.
	Visibility    any
	Watchers      any
	WatchersCount any
	// Whether to require contributors to sign off on web-based commits
	WebCommitSignoffRequired any
	// path parameter, not part of the API's own resource representation
	Org any
	// path parameter, not part of the API's own resource representation
	TeamSlug any
	// path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute)
	OwnerPath any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute)
	OwnerPath2 any
}

var Repository = ubx.ResourceBinding{
	WireType: "github_team_repository",
	Fields: ubx.FieldMap{
		"Permission": ubx.FieldSpec{WireName: "permission"},
		"Org":        ubx.FieldSpec{WireName: "org"},
		"TeamSlug":   ubx.FieldSpec{WireName: "team_slug"},
		"OwnerPath":  ubx.FieldSpec{WireName: "owner_path"},
		"Repo":       ubx.FieldSpec{WireName: "repo"},
		"OwnerPath2": ubx.FieldSpec{WireName: "owner_path2"},
	},
}
