# Code generated by `ubx sdk gen` from github_stargazer. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class StargazerConfig:
    owner: Any = None
    repo: Any = None

@dataclasses.dataclass
class StargazerAttrs:
    count: Any = None
    owner: Any = None
    repo: Any = None

Stargazer = ubx.DataSourceBinding(
    wire_type="github_stargazer",
    fields={
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
