// Code generated by `ubx sdk gen` from github_assignee. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AssigneeConfig {
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  repo: string | Computed<string>;
}

export interface AssigneeAttrs {
  owner: string;
  page: number;
  perPage: number;
  repo: string;
}

export const Assignee: DataSourceBinding<AssigneeConfig, AssigneeAttrs> = {
  wireType: "github_assignee",
  fields: {
    owner: "owner",
    page: "page",
    perPage: "per_page",
    repo: "repo",
  },
};
