// Code generated by `ubx sdk gen` from github_milestone. DO NOT EDIT.
package milestone

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Milestone_Creator struct {
	AvatarUrl         any
	Email             any
	EventsUrl         any
	FollowersUrl      any
	FollowingUrl      any
	GistsUrl          any
	GravatarId        any
	HtmlUrl           any
	Id                any
	Login             any
	Name              any
	NodeId            any
	OrganizationsUrl  any
	ReceivedEventsUrl any
	ReposUrl          any
	SiteAdmin         any
	StarredAt         any
	StarredUrl        any
	SubscriptionsUrl  any
	Type              any
	Url               any
	UserViewType      any
}

type MilestoneConfig struct {
	// A description of the milestone.
	Description any
	// The milestone due date. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
	DueOn any
	// The state of the milestone. Either `open` or `closed`.
	State any
	// The title of the milestone.
	Title any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	MilestoneNumber any
}

type MilestoneAttrs struct {
	ClosedAt     any
	ClosedIssues any
	CreatedAt    any
	// A GitHub user.
	Creator any
	// A description of the milestone.
	Description any
	// The milestone due date. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
	DueOn     any
	HtmlUrl   any
	Id        any
	LabelsUrl any
	NodeId    any
	// The number of the milestone.
	Number     any
	OpenIssues any
	// The state of the milestone. Either `open` or `closed`.
	State any
	// The title of the milestone.
	Title     any
	UpdatedAt any
	Url       any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	MilestoneNumber any
}

var Milestone = ubx.ResourceBinding{
	WireType: "github_milestone",
	Fields: ubx.FieldMap{
		"Description":     ubx.FieldSpec{WireName: "description"},
		"DueOn":           ubx.FieldSpec{WireName: "due_on"},
		"State":           ubx.FieldSpec{WireName: "state"},
		"Title":           ubx.FieldSpec{WireName: "title"},
		"Owner":           ubx.FieldSpec{WireName: "owner"},
		"Repo":            ubx.FieldSpec{WireName: "repo"},
		"MilestoneNumber": ubx.FieldSpec{WireName: "milestone_number"},
	},
}
