// Code generated by `ubx sdk gen` from github_code_frequency. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface FrequencyConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface FrequencyAttrs {
  owner: string;
  repo: string;
}

export const Frequency: DataSourceBinding<FrequencyConfig, FrequencyAttrs> = {
  wireType: "github_code_frequency",
  fields: {
    owner: "owner",
    repo: "repo",
  },
};
