// Code generated by `ubx sdk gen` from github_code_scanning_codeql_database. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ScanningCodeqlDatabase_Uploader {
  avatarUrl: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl: string | Computed<string>;
  followersUrl: string | Computed<string>;
  followingUrl: string | Computed<string>;
  gistsUrl: string | Computed<string>;
  gravatarId: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  id: number | Computed<number>;
  login: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId: string | Computed<string>;
  organizationsUrl: string | Computed<string>;
  receivedEventsUrl: string | Computed<string>;
  reposUrl: string | Computed<string>;
  siteAdmin: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  starredUrl: string | Computed<string>;
  subscriptionsUrl: string | Computed<string>;
  type: string | Computed<string>;
  url: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface ScanningCodeqlDatabaseConfig {
  language: string | Computed<string>;
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface ScanningCodeqlDatabaseAttrs {
  /** The commit SHA of the repository at the time the CodeQL database was created. */
  commitOid: string;
  /** The MIME type of the CodeQL database file. */
  contentType: string;
  /** The date and time at which the CodeQL database was created, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ. */
  createdAt: string;
  /** The ID of the CodeQL database. */
  id: number;
  language: string;
  /** The name of the CodeQL database. */
  name: string;
  owner: string;
  repo: string;
  /** The size of the CodeQL database file in bytes. */
  size: number;
  /** The date and time at which the CodeQL database was last updated, in ISO 8601 format':' YYYY-MM-DDTHH:MM:SSZ. */
  updatedAt: string;
  /** A GitHub user. */
  uploader: ScanningCodeqlDatabase_Uploader;
  /** The URL at which to download the CodeQL database. The `Accept` header must be set to the value of the `content_type` property. */
  url: string;
}

export const ScanningCodeqlDatabase: DataSourceBinding<ScanningCodeqlDatabaseConfig, ScanningCodeqlDatabaseAttrs> = {
  wireType: "github_code_scanning_codeql_database",
  fields: {
    language: "language",
    owner: "owner",
    repo: "repo",
  },
};
