# Code generated by `ubx sdk gen` from github_actions_cache_retention_limit_for_organization. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class CacheRetentionLimitForOrganizationConfig:
    org: Any = None

@dataclasses.dataclass
class CacheRetentionLimitForOrganizationAttrs:
    # For repositories in this organization, the maximum duration, in days, for which caches in a repository may be retained.
    max_cache_retention_days: Any = None
    org: Any = None

CacheRetentionLimitForOrganization = ubx.DataSourceBinding(
    wire_type="github_actions_cache_retention_limit_for_organization",
    fields={
        "org": ubx.FieldSpec(wire_name="org"),
    },
)
