# Code generated by `ubx sdk gen` from github_actions_fork_pr_workflows_private_repos. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ForkPrWorkflowsPrivateReposConfig:
    enterprise: Any = None

@dataclasses.dataclass
class ForkPrWorkflowsPrivateReposAttrs:
    enterprise: Any = None
    # Whether workflows triggered by pull requests from forks require approval from a repository administrator to run.
    require_approval_for_fork_pr_workflows: Any = None
    # Whether workflows triggered by pull requests from forks are allowed to run on private repositories.
    run_workflows_from_fork_pull_requests: Any = None
    # Whether to make secrets and variables available to workflows triggered by pull requests from forks.
    send_secrets_and_variables: Any = None
    # Whether GitHub Actions can create pull requests or submit approving pull request reviews from a workflow triggered by a fork pull request.
    send_write_tokens_to_workflows: Any = None

ForkPrWorkflowsPrivateRepos = ubx.DataSourceBinding(
    wire_type="github_actions_fork_pr_workflows_private_repos",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
    },
)
