# Code generated by `ubx sdk gen` from github_actions_get_default_workflow_permissions. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GetDefaultWorkflowPermissionsConfig:
    enterprise: Any = None

@dataclasses.dataclass
class GetDefaultWorkflowPermissionsAttrs:
    # Whether GitHub Actions can approve pull requests. Enabling this can be a security risk.
    can_approve_pull_request_reviews: Any = None
    # The default workflow permissions granted to the GITHUB_TOKEN when running workflows.
    default_workflow_permissions: Any = None
    enterprise: Any = None

GetDefaultWorkflowPermissions = ubx.DataSourceBinding(
    wire_type="github_actions_get_default_workflow_permissions",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
    },
)
