# Code generated by `ubx sdk gen` from github_actions_hosted_runner_custom_image_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class HostedRunnerCustomImageList_Images:
    id: Any = None
    latest_version: Any = None
    name: Any = None
    platform: Any = None
    source: Any = None
    state: Any = None
    total_versions_size: Any = None
    versions_count: Any = None

@dataclasses.dataclass
class HostedRunnerCustomImageListConfig:
    enterprise: Any = None

@dataclasses.dataclass
class HostedRunnerCustomImageListAttrs:
    enterprise: Any = None
    images: Any = None
    total_count: Any = None

HostedRunnerCustomImageList = ubx.DataSourceBinding(
    wire_type="github_actions_hosted_runner_custom_image_list",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
    },
)
