# Code generated by `ubx sdk gen` from github_actions_variable_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class VariableList_Variables:
    created_at: Any = None
    name: Any = None
    updated_at: Any = None
    value: Any = None

@dataclasses.dataclass
class VariableListConfig:
    owner: Any = None
    page: Any = None
    per_page: Any = None
    repo: Any = None

@dataclasses.dataclass
class VariableListAttrs:
    owner: Any = None
    page: Any = None
    per_page: Any = None
    repo: Any = None
    total_count: Any = None
    variables: Any = None

VariableList = ubx.DataSourceBinding(
    wire_type="github_actions_variable_list",
    fields={
        "owner": ubx.FieldSpec(wire_name="owner"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
