// Code generated by `ubx sdk gen` from github_author. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface AuthorConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
  since?: number | Computed<number>;
}

export interface AuthorAttrs {
  owner: string;
  repo: string;
  since: number;
}

export const Author: DataSourceBinding<AuthorConfig, AuthorAttrs> = {
  wireType: "github_author",
  fields: {
    owner: "owner",
    repo: "repo",
    since: "since",
  },
};
