// Code generated by `ubx sdk gen` from github_custom_deployment_rule_app. DO NOT EDIT.
package custom

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DeploymentRuleApp_AvailableCustomDeploymentProtectionRuleIntegrations struct {
	Id             any
	IntegrationUrl any
	NodeId         any
	Slug           any
}

type DeploymentRuleAppConfig struct {
	EnvironmentName any
	Owner           any
	Page            any
	PerPage         any
	Repo            any
}

type DeploymentRuleAppAttrs struct {
	AvailableCustomDeploymentProtectionRuleIntegrations any
	EnvironmentName                                     any
	Owner                                               any
	Page                                                any
	PerPage                                             any
	Repo                                                any
	// The total number of custom deployment protection rule integrations available for this environment.
	TotalCount any
}

var DeploymentRuleApp = ubx.DataSourceBinding{
	WireType: "github_custom_deployment_rule_app",
	Fields: ubx.FieldMap{
		"EnvironmentName": ubx.FieldSpec{WireName: "environment_name"},
		"Owner":           ubx.FieldSpec{WireName: "owner"},
		"Page":            ubx.FieldSpec{WireName: "page"},
		"PerPage":         ubx.FieldSpec{WireName: "per_page"},
		"Repo":            ubx.FieldSpec{WireName: "repo"},
	},
}
