// Code generated by `ubx sdk gen` from github_org_membership. DO NOT EDIT.
package org

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Membership_Organization struct {
	AvatarUrl        any
	Description      any
	EventsUrl        any
	HooksUrl         any
	Id               any
	IssuesUrl        any
	Login            any
	MembersUrl       any
	NodeId           any
	PublicMembersUrl any
	ReposUrl         any
	Url              any
}

type Membership_Permissions struct {
	CanCreateRepository any
}

type Membership_User struct {
	AvatarUrl         any
	Email             any
	EventsUrl         any
	FollowersUrl      any
	FollowingUrl      any
	GistsUrl          any
	GravatarId        any
	HtmlUrl           any
	Id                any
	Login             any
	Name              any
	NodeId            any
	OrganizationsUrl  any
	ReceivedEventsUrl any
	ReposUrl          any
	SiteAdmin         any
	StarredAt         any
	StarredUrl        any
	SubscriptionsUrl  any
	Type              any
	Url               any
	UserViewType      any
}

type MembershipConfig struct {
	// The role to give the user in the organization. Can be one of: * `admin` - The user will become an owner of the organization. * `member` - The user will become a non-owner member of the organization.
	Role any
	// path parameter, not part of the API's own resource representation
	Org any
	// path parameter, not part of the API's own resource representation
	Username any
}

type MembershipAttrs struct {
	// Whether the user has direct membership in the organization.
	DirectMembership any
	// The slugs of the enterprise teams providing the user with indirect membership in the organization. A limit of 100 enterprise team slugs is returned.
	EnterpriseTeamsProvidingIndirectMembership any
	// A GitHub organization.
	Organization    any
	OrganizationUrl any
	Permissions     any
	// The role to give the user in the organization. Can be one of: * `admin` - The user will become an owner of the organization. * `member` - The user will become a non-owner member of the organization.
	Role any
	// The state of the member in the organization. The `pending` state indicates the user has not yet accepted an invitation.
	State any
	Url   any
	// A GitHub user.
	User any
	// path parameter, not part of the API's own resource representation
	Org any
	// path parameter, not part of the API's own resource representation
	Username any
}

var Membership = ubx.ResourceBinding{
	WireType: "github_org_membership",
	Fields: ubx.FieldMap{
		"Role":     ubx.FieldSpec{WireName: "role"},
		"Org":      ubx.FieldSpec{WireName: "org"},
		"Username": ubx.FieldSpec{WireName: "username"},
	},
}
