# Code generated by `ubx sdk gen` from github_schema. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SchemaConfig:
    enterprise: Any = None

@dataclasses.dataclass
class SchemaAttrs:
    enterprise: Any = None

Schema = ubx.DataSourceBinding(
    wire_type="github_schema",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
    },
)
