// Code generated by `ubx sdk gen` from github_count. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CountConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface CountAttrs {
  count: number;
  owner: string;
  repo: string;
}

export const Count: DataSourceBinding<CountConfig, CountAttrs> = {
  wireType: "github_count",
  fields: {
    owner: "owner",
    repo: "repo",
  },
};
