# Code generated by `ubx sdk gen` from github_api_insights_time_stats. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class InsightsTimeStatsConfig:
    max_timestamp: Any = None
    min_timestamp: Any = None
    org: Any = None
    timestamp_increment: Any = None

@dataclasses.dataclass
class InsightsTimeStatsAttrs:
    max_timestamp: Any = None
    min_timestamp: Any = None
    org: Any = None
    timestamp_increment: Any = None

InsightsTimeStats = ubx.DataSourceBinding(
    wire_type="github_api_insights_time_stats",
    fields={
        "max_timestamp": ubx.FieldSpec(wire_name="max_timestamp"),
        "min_timestamp": ubx.FieldSpec(wire_name="min_timestamp"),
        "org": ubx.FieldSpec(wire_name="org"),
        "timestamp_increment": ubx.FieldSpec(wire_name="timestamp_increment"),
    },
)
