// Code generated by `ubx sdk gen` from github_popular. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface PopularConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface PopularAttrs {
  owner: string;
  repo: string;
}

export const Popular: DataSourceBinding<PopularConfig, PopularAttrs> = {
  wireType: "github_popular",
  fields: {
    owner: "owner",
    repo: "repo",
  },
};
