// Code generated by `ubx sdk gen` from github_download. DO NOT EDIT.
package download

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DownloadConfig struct {
	Enterprise any
}

type DownloadAttrs struct {
	Enterprise any
}

var Download = ubx.DataSourceBinding{
	WireType: "github_download",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
	},
}
