# Code generated by `ubx sdk gen` from github_conflict. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class ConflictConfig:
    org: Any = None

@dataclasses.dataclass
class ConflictAttrs:
    org: Any = None

Conflict = ubx.DataSourceBinding(
    wire_type="github_conflict",
    fields={
        "org": ubx.FieldSpec(wire_name="org"),
    },
)
