// Code generated by `ubx sdk gen` from github_security_manager. DO NOT EDIT.
package security

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ManagerConfig struct {
	Org any
}

type ManagerAttrs struct {
	Org any
}

var Manager = ubx.DataSourceBinding{
	WireType: "github_security_manager",
	Fields: ubx.FieldMap{
		"Org": ubx.FieldSpec{WireName: "org"},
	},
}
