// Code generated by `ubx sdk gen` from github_git_tree. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Tree_Tree {
  content?: string | Computed<string>;
  mode?: string | Computed<string>;
  path?: string | Computed<string>;
  sha?: string | Computed<string>;
  type?: string | Computed<string>;
}

const Tree_TreeFields: FieldMap = {
  content: "content",
  mode: "mode",
  path: "path",
  sha: "sha",
  type: "type",
};

export interface TreeConfig {
  /** The SHA1 of an existing Git tree object which will be used as the base for the new tree. If provided, a new Git tree object will be created from entries in the Git tree object pointed to by `base_tree` and entries defined in the `tree` parameter. Entries defined in the `tree` parameter will overwrite items from `base_tree` with the same `path`. If you're creating new changes on a branch, then normally you'd set `base_tree` to the SHA1 of the Git tree object of the current latest commit on the branch you're working on. If not provided, GitHub will create a new Git tree object from only the entries defined in the `tree` parameter. If you create a new commit pointing to such a tree, then all files which were a part of the parent commit's tree and were not defined in the `tree` parameter will be listed as deleted by the new commit. */
  baseTree?: string | Computed<string>;
  /** Objects (of `path`, `mode`, `type`, and `sha`) specifying a tree structure. */
  tree: Tree_Tree[] | Computed<Tree_Tree[]>;
  /** path parameter, not part of the API's own resource representation */
  owner: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  repo: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  treeSha: string | Computed<string>;
}

export interface TreeAttrs {
  /** The SHA1 of an existing Git tree object which will be used as the base for the new tree. If provided, a new Git tree object will be created from entries in the Git tree object pointed to by `base_tree` and entries defined in the `tree` parameter. Entries defined in the `tree` parameter will overwrite items from `base_tree` with the same `path`. If you're creating new changes on a branch, then normally you'd set `base_tree` to the SHA1 of the Git tree object of the current latest commit on the branch you're working on. If not provided, GitHub will create a new Git tree object from only the entries defined in the `tree` parameter. If you create a new commit pointing to such a tree, then all files which were a part of the parent commit's tree and were not defined in the `tree` parameter will be listed as deleted by the new commit. */
  baseTree: string;
  sha: string;
  /** Objects (of `path`, `mode`, `type`, and `sha`) specifying a tree structure. */
  tree: Tree_Tree[];
  truncated: boolean;
  url: string;
  /** path parameter, not part of the API's own resource representation */
  owner: string;
  /** path parameter, not part of the API's own resource representation */
  repo: string;
  /** path parameter, not part of the API's own resource representation */
  treeSha: string;
}

export const Tree: ResourceBinding<TreeConfig, TreeAttrs> = {
  wireType: "github_git_tree",
  fields: {
    baseTree: "base_tree",
    tree: {
      wireName: "tree",
      kind: "list",
      fields: Tree_TreeFields,
    },
    owner: "owner",
    repo: "repo",
    treeSha: "tree_sha",
  },
};
