// Code generated by `ubx sdk gen` from github_package_version. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Version_Metadata_Container {
  tags: string[] | Computed<string[]>;
}

export interface Version_Metadata_Docker {
  tag?: string[] | Computed<string[]>;
}

export interface Version_Metadata {
  container?: Version_Metadata_Container | Computed<Version_Metadata_Container>;
  docker?: Version_Metadata_Docker | Computed<Version_Metadata_Docker>;
  packageType: string | Computed<string>;
}

export interface VersionConfig {
  /** path parameter, not part of the API's own resource representation */
  org: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  packageType: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  packageName: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  packageVersionId: string | Computed<string>;
}

export interface VersionAttrs {
  /** The real timestamp this object was created. (AI-inferred) */
  createdAt: string;
  /** The real timestamp this object was deleted, if it has been. (AI-inferred) */
  deletedAt: string;
  /** The real, free-text description set on this object. (AI-inferred) */
  description: string;
  /** The real, browsable web URL for this object. (AI-inferred) */
  htmlUrl: string;
  /** Unique identifier of the package version. */
  id: number;
  /** The real, detected open source license for this repository. (AI-inferred) */
  license: string;
  /** Real, structured metadata attached to this object. (AI-inferred) */
  metadata: Version_Metadata;
  /** The name of the package version. */
  name: string;
  /** The real, browsable web URL for this package. (AI-inferred) */
  packageHtmlUrl: string;
  /** The real timestamp this object was last updated. (AI-inferred) */
  updatedAt: string;
  /** The real, canonical API URL for this object. (AI-inferred) */
  url: string;
  /** path parameter, not part of the API's own resource representation */
  org: string;
  /** path parameter, not part of the API's own resource representation */
  packageType: string;
  /** path parameter, not part of the API's own resource representation */
  packageName: string;
  /** path parameter, not part of the API's own resource representation */
  packageVersionId: string;
}

export const Version: ResourceBinding<VersionConfig, VersionAttrs> = {
  wireType: "github_package_version",
  fields: {
    org: "org",
    packageType: "package_type",
    packageName: "package_name",
    packageVersionId: "package_version_id",
  },
};
