# Code generated by `ubx sdk gen` from github_org_hook. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Hook_Config:
    # The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
    content_type: Any = None
    # Controls whether SSL verification is enabled for webhook deliveries. Set to '1' or true to ignore SSL certificate errors, or '0' or false to require valid certificates. Accepts both boolean and string values due to its dynamic type. (AI-inferred)
    insecure_ssl: Any = None
    password: Any = None
    # If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value for [delivery signature headers](https://docs.github.com/enterprise-cloud@latest/webhooks/event-payloads/#delivery-headers).
    secret: Any = None
    # The URL to which the payloads will be delivered.
    url: Any = None
    username: Any = None

_Hook_ConfigFields = {
    "content_type": ubx.FieldSpec(wire_name="content_type"),
    "insecure_ssl": ubx.FieldSpec(wire_name="insecure_ssl"),
    "password": ubx.FieldSpec(wire_name="password"),
    "secret": ubx.FieldSpec(wire_name="secret"),
    "url": ubx.FieldSpec(wire_name="url"),
    "username": ubx.FieldSpec(wire_name="username"),
}

@dataclasses.dataclass
class HookConfig:
    # Determines if notifications are sent when the webhook is triggered. Set to `true` to send notifications.
    active: Any = None
    # Key/value pairs to provide settings for this webhook.
    config: Any = None
    # Determines what [events](https://docs.github.com/enterprise-cloud@latest/webhooks/event-payloads) the hook is triggered for. Set to `["*"]` to receive all possible events.
    events: Any = None
    # Must be passed as "web".
    name: Any = None
    # path parameter, not part of the API's own resource representation
    org: Any = None
    # path parameter, not part of the API's own resource representation
    hook_id: Any = None

@dataclasses.dataclass
class HookAttrs:
    # Determines if notifications are sent when the webhook is triggered. Set to `true` to send notifications.
    active: Any = None
    # Key/value pairs to provide settings for this webhook.
    config: Any = None
    # The timestamp of when the organization hook was created. (AI-inferred)
    created_at: Any = None
    # The URL to list the webhook deliveries for this organization webhook. (AI-inferred)
    deliveries_url: Any = None
    # Determines what [events](https://docs.github.com/enterprise-cloud@latest/webhooks/event-payloads) the hook is triggered for. Set to `["*"]` to receive all possible events.
    events: Any = None
    id: Any = None
    # Must be passed as "web".
    name: Any = None
    # The URL that can be pinged to trigger a test event for this organization webhook. (AI-inferred)
    ping_url: Any = None
    # The type of the organization webhook, such as 'web'. (AI-inferred)
    type: Any = None
    # The timestamp of the last update to the GitHub organization webhook, set by the system. (AI-inferred)
    updated_at: Any = None
    # The URL of the hook as returned by the GitHub API. This is the API endpoint for the hook itself (e.g., https://api.github.com/orgs/ORG/hooks/HOOK_ID), not the webhook receiver URL. (AI-inferred)
    url: Any = None
    # path parameter, not part of the API's own resource representation
    org: Any = None
    # path parameter, not part of the API's own resource representation
    hook_id: Any = None

Hook = ubx.ResourceBinding(
    wire_type="github_org_hook",
    fields={
        "active": ubx.FieldSpec(wire_name="active"),
        "config": ubx.FieldSpec(
            wire_name="config",
            kind="object",
            fields=_Hook_ConfigFields,
        ),
        "events": ubx.FieldSpec(wire_name="events"),
        "name": ubx.FieldSpec(wire_name="name"),
        "org": ubx.FieldSpec(wire_name="org"),
        "hook_id": ubx.FieldSpec(wire_name="hook_id"),
    },
)
