// Code generated by `ubx sdk gen` from github_key. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface KeyConfig {
  /** The public SSH key to add to your GitHub account. */
  key: string | Computed<string>;
  /** A descriptive name for the new key. */
  title?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  keyId: string | Computed<string>;
}

export interface KeyAttrs {
  createdAt: string;
  id: number;
  /** The public SSH key to add to your GitHub account. */
  key: string;
  lastUsed: string;
  readOnly: boolean;
  /** A descriptive name for the new key. */
  title: string;
  url: string;
  verified: boolean;
  /** path parameter, not part of the API's own resource representation */
  keyId: string;
}

export const Key: ResourceBinding<KeyConfig, KeyAttrs> = {
  wireType: "github_key",
  fields: {
    key: "key",
    title: "title",
    keyId: "key_id",
  },
};
