// Code generated by `ubx sdk gen` from github_milestone. DO NOT EDIT.
package milestone

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MilestoneConfig struct {
	MilestoneNumber any
	Owner any
	Page any
	PerPage any
	Repo any
}

type MilestoneAttrs struct {
	MilestoneNumber any
	Owner any
	Page any
	PerPage any
	Repo any
}

var Milestone = ubx.DataSourceBinding{
	WireType: "github_milestone",
	Fields: ubx.FieldMap{
		"MilestoneNumber": ubx.FieldSpec{WireName: "milestone_number"},
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
	},
}
