# Code generated by `ubx sdk gen` from github_branches_where_head. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class WhereHeadConfig:
    commit_sha: Any = None
    owner: Any = None
    repo: Any = None

@dataclasses.dataclass
class WhereHeadAttrs:
    commit_sha: Any = None
    owner: Any = None
    repo: Any = None

WhereHead = ubx.DataSourceBinding(
    wire_type="github_branches_where_head",
    fields={
        "commit_sha": ubx.FieldSpec(wire_name="commit_sha"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
