// Code generated by `ubx sdk gen` from github_code_scanning_variant_analysis_repo_task. DO NOT EDIT.
package code

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ScanningVariantAnalysisRepoTask_Repository_Owner struct {
	AvatarUrl         any
	Email             any
	EventsUrl         any
	FollowersUrl      any
	FollowingUrl      any
	GistsUrl          any
	GravatarId        any
	HtmlUrl           any
	Id                any
	Login             any
	Name              any
	NodeId            any
	OrganizationsUrl  any
	ReceivedEventsUrl any
	ReposUrl          any
	SiteAdmin         any
	StarredAt         any
	StarredUrl        any
	SubscriptionsUrl  any
	Type              any
	Url               any
	UserViewType      any
}

type ScanningVariantAnalysisRepoTask_Repository struct {
	// A template for the API URL to download the repository as an archive.
	ArchiveUrl any
	// A template for the API URL to list the available assignees for issues in the repository.
	AssigneesUrl any
	// A template for the API URL to create or retrieve a raw Git blob in the repository.
	BlobsUrl any
	// A template for the API URL to get information about branches in the repository.
	BranchesUrl any
	// A template for the API URL to get information about collaborators of the repository.
	CollaboratorsUrl any
	// A template for the API URL to get information about comments on the repository.
	CommentsUrl any
	// A template for the API URL to get information about commits on the repository.
	CommitsUrl any
	// A template for the API URL to compare two commits or refs.
	CompareUrl any
	// A template for the API URL to get the contents of the repository.
	ContentsUrl any
	// A template for the API URL to list the contributors to the repository.
	ContributorsUrl any
	// The API URL to list the deployments of the repository.
	DeploymentsUrl any
	// The repository description.
	Description any
	// The API URL to list the downloads on the repository.
	DownloadsUrl any
	// The API URL to list the events of the repository.
	EventsUrl any
	// Whether the repository is a fork.
	Fork any
	// The API URL to list the forks of the repository.
	ForksUrl any
	// The full, globally unique, name of the repository.
	FullName any
	// A template for the API URL to get information about Git commits of the repository.
	GitCommitsUrl any
	// A template for the API URL to get information about Git refs of the repository.
	GitRefsUrl any
	// A template for the API URL to get information about Git tags of the repository.
	GitTagsUrl any
	// The API URL to list the hooks on the repository.
	HooksUrl any
	// The URL to view the repository on GitHub.com.
	HtmlUrl any
	// A unique identifier of the repository.
	Id any
	// A template for the API URL to get information about issue comments on the repository.
	IssueCommentUrl any
	// A template for the API URL to get information about issue events on the repository.
	IssueEventsUrl any
	// A template for the API URL to get information about issues on the repository.
	IssuesUrl any
	// A template for the API URL to get information about deploy keys on the repository.
	KeysUrl any
	// A template for the API URL to get information about labels of the repository.
	LabelsUrl any
	// The API URL to get information about the languages of the repository.
	LanguagesUrl any
	// The API URL to merge branches in the repository.
	MergesUrl any
	// A template for the API URL to get information about milestones of the repository.
	MilestonesUrl any
	// The name of the repository.
	Name any
	// The GraphQL identifier of the repository.
	NodeId any
	// A template for the API URL to get information about notifications on the repository.
	NotificationsUrl any
	// A GitHub user.
	Owner any
	// Whether the repository is private.
	Private any
	// A template for the API URL to get information about pull requests on the repository.
	PullsUrl any
	// A template for the API URL to get information about releases on the repository.
	ReleasesUrl any
	// The API URL to list the stargazers on the repository.
	StargazersUrl any
	// A template for the API URL to get information about statuses of a commit.
	StatusesUrl any
	// The API URL to list the subscribers on the repository.
	SubscribersUrl any
	// The API URL to subscribe to notifications for this repository.
	SubscriptionUrl any
	// The API URL to get information about tags on the repository.
	TagsUrl any
	// The API URL to list the teams on the repository.
	TeamsUrl any
	// A template for the API URL to create or retrieve a raw Git tree of the repository.
	TreesUrl any
	// The URL to get more information about the repository from the GitHub API.
	Url any
}

type ScanningVariantAnalysisRepoTaskConfig struct {
	CodeqlVariantAnalysisId any
	Owner                   any
	Repo                    any
	RepoName                any
	RepoOwner               any
}

type ScanningVariantAnalysisRepoTaskAttrs struct {
	// The new status of the CodeQL variant analysis repository task.
	AnalysisStatus any
	// The size of the artifact. This is only available for successful analyses.
	ArtifactSizeInBytes any
	// The URL of the artifact. This is only available for successful analyses.
	ArtifactUrl             any
	CodeqlVariantAnalysisId any
	// The SHA of the commit the CodeQL database was built against. This is only available for successful analyses.
	DatabaseCommitSha any
	// The reason of the failure of this repo task. This is only available if the repository task has failed.
	FailureMessage any
	Owner          any
	Repo           any
	RepoName       any
	RepoOwner      any
	// A GitHub repository.
	Repository any
	// The number of results in the case of a successful analysis. This is only available for successful analyses.
	ResultCount any
	// The source location prefix to use. This is only available for successful analyses.
	SourceLocationPrefix any
}

var ScanningVariantAnalysisRepoTask = ubx.DataSourceBinding{
	WireType: "github_code_scanning_variant_analysis_repo_task",
	Fields: ubx.FieldMap{
		"CodeqlVariantAnalysisId": ubx.FieldSpec{WireName: "codeql_variant_analysis_id"},
		"Owner":                   ubx.FieldSpec{WireName: "owner"},
		"Repo":                    ubx.FieldSpec{WireName: "repo"},
		"RepoName":                ubx.FieldSpec{WireName: "repo_name"},
		"RepoOwner":               ubx.FieldSpec{WireName: "repo_owner"},
	},
}
