// Code generated by `ubx sdk gen` from github_check_immutable_releases. DO NOT EDIT.
package check

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type ImmutableReleasesConfig struct {
	Owner any
	Repo  any
}

type ImmutableReleasesAttrs struct {
	// Whether immutable releases are enabled for the repository.
	Enabled any
	// Whether immutable releases are enforced by the repository owner.
	EnforcedByOwner any
	Owner           any
	Repo            any
}

var ImmutableReleases = ubx.DataSourceBinding{
	WireType: "github_check_immutable_releases",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Repo":  ubx.FieldSpec{WireName: "repo"},
	},
}
