// Code generated by `ubx sdk gen` from github_custom_pattern. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface PatternConfig {
  after?: string | Computed<string>;
  before?: string | Computed<string>;
  direction?: string | Computed<string>;
  enterprise: string | Computed<string>;
  pushProtection?: string | Computed<string>;
  sort?: string | Computed<string>;
  state?: string | Computed<string>;
}

export interface PatternAttrs {
  after: string;
  before: string;
  direction: string;
  enterprise: string;
  pushProtection: string;
  sort: string;
  state: string;
}

export const Pattern: DataSourceBinding<PatternConfig, PatternAttrs> = {
  wireType: "github_custom_pattern",
  fields: {
    after: "after",
    before: "before",
    direction: "direction",
    enterprise: "enterprise",
    pushProtection: "push_protection",
    sort: "sort",
    state: "state",
  },
};
