# Code generated by `ubx sdk gen` from github_simple_user. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class UserConfig:
    # path parameter, not part of the API's own resource representation
    enterprise: Any = None
    # path parameter, not part of the API's own resource representation
    username: Any = None

@dataclasses.dataclass
class UserAttrs:
    # The URL of the user's avatar image. (AI-inferred)
    avatar_url: Any = None
    # The public email address of the user, as configured in their GitHub profile; may be null if not set. (AI-inferred)
    email: Any = None
    events_url: Any = None
    # The URL to retrieve the list of followers for this user. (AI-inferred)
    followers_url: Any = None
    # The URL to the GitHub API endpoint that lists the users this user follows. This field is computed by the API and read-only. (AI-inferred)
    following_url: Any = None
    # The URL template for the user's public gists, including an optional gist ID placeholder (e.g., https://api.github.com/users/{user}/gists{/gist_id}). (AI-inferred)
    gists_url: Any = None
    # The Gravatar ID for the user, used to construct their avatar URL. This is returned by the API and is typically an empty string when no Gravatar is associated. (AI-inferred)
    gravatar_id: Any = None
    # The HTML URL to the user's GitHub profile page. (AI-inferred)
    html_url: Any = None
    # The unique identifier for the user on GitHub. (AI-inferred)
    id: Any = None
    # The GitHub username of the user. (AI-inferred)
    login: Any = None
    # The display name of the user, as shown on their GitHub profile. This is a computed, read-only value and may be null if the user has not specified a name. (AI-inferred)
    name: Any = None
    # The unique node ID of the user, used by GitHub's GraphQL API to identify the resource. (AI-inferred)
    node_id: Any = None
    # The API endpoint URL to list the organizations that the user belongs to. This URL is generated by GitHub and used to fetch the user's organizations. (AI-inferred)
    organizations_url: Any = None
    # The API endpoint URL that lists events received by the user. (AI-inferred)
    received_events_url: Any = None
    # The URL to the user's repositories on GitHub. (AI-inferred)
    repos_url: Any = None
    # Indicates whether the user is a GitHub site administrator. (AI-inferred)
    site_admin: Any = None
    # The timestamp when the user starred the repository, in ISO 8601 format (e.g., 2023-01-01T12:00:00Z). (AI-inferred)
    starred_at: Any = None
    # The URL template to list repositories starred by the user, with placeholders for owner and repo. (AI-inferred)
    starred_url: Any = None
    # The URL to the user's subscriptions endpoint, providing a link to the resources the user is subscribed to. (AI-inferred)
    subscriptions_url: Any = None
    # The type of GitHub account, which is typically 'User' or 'Organization'. (AI-inferred)
    type: Any = None
    # The API URL for the user resource. (AI-inferred)
    url: Any = None
    user_view_type: Any = None
    # path parameter, not part of the API's own resource representation
    enterprise: Any = None
    # path parameter, not part of the API's own resource representation
    username: Any = None

User = ubx.ResourceBinding(
    wire_type="github_simple_user",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
        "username": ubx.FieldSpec(wire_name="username"),
    },
)
