// Code generated by `ubx sdk gen` from github_push_rule. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RuleConfig {
  enterprise: string | Computed<string>;
  organizationName?: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  requestStatus?: string | Computed<string>;
  requester?: string | Computed<string>;
  reviewer?: string | Computed<string>;
  timePeriod?: string | Computed<string>;
}

export interface RuleAttrs {
  enterprise: string;
  organizationName: string;
  page: number;
  perPage: number;
  requestStatus: string;
  requester: string;
  reviewer: string;
  timePeriod: string;
}

export const Rule: DataSourceBinding<RuleConfig, RuleAttrs> = {
  wireType: "github_push_rule",
  fields: {
    enterprise: "enterprise",
    organizationName: "organization_name",
    page: "page",
    perPage: "per_page",
    requestStatus: "request_status",
    requester: "requester",
    reviewer: "reviewer",
    timePeriod: "time_period",
  },
};
