// Code generated by `ubx sdk gen` from github_large_file. DO NOT EDIT.
package large

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FileConfig struct {
	Owner any
	Repo  any
}

type FileAttrs struct {
	Owner any
	Repo  any
}

var File = ubx.DataSourceBinding{
	WireType: "github_large_file",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Repo":  ubx.FieldSpec{WireName: "repo"},
	},
}
