// Code generated by `ubx sdk gen` from github_pull_request_review. DO NOT EDIT.
package pull

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RequestReview_Links_Html struct {
	Href any
}

type RequestReview_Links struct {
	Html        any
	PullRequest any
}

type RequestReview_Comments struct {
	Body      any
	Line      any
	Path      any
	Position  any
	Side      any
	StartLine any
	StartSide any
}

type RequestReview_User struct {
	AvatarUrl         any
	Email             any
	EventsUrl         any
	FollowersUrl      any
	FollowingUrl      any
	GistsUrl          any
	GravatarId        any
	HtmlUrl           any
	Id                any
	Login             any
	Name              any
	NodeId            any
	OrganizationsUrl  any
	ReceivedEventsUrl any
	ReposUrl          any
	SiteAdmin         any
	StarredAt         any
	StarredUrl        any
	SubscriptionsUrl  any
	Type              any
	Url               any
	UserViewType      any
}

var RequestReview_CommentsFields = ubx.FieldMap{
	"Body":      ubx.FieldSpec{WireName: "body"},
	"Line":      ubx.FieldSpec{WireName: "line"},
	"Path":      ubx.FieldSpec{WireName: "path"},
	"Position":  ubx.FieldSpec{WireName: "position"},
	"Side":      ubx.FieldSpec{WireName: "side"},
	"StartLine": ubx.FieldSpec{WireName: "start_line"},
	"StartSide": ubx.FieldSpec{WireName: "start_side"},
}

type RequestReviewConfig struct {
	// **Required** when using `REQUEST_CHANGES` or `COMMENT` for the `event` parameter. The body text of the pull request review.
	Body any
	// Use the following table to specify the location, destination, and contents of the draft review comment.
	Comments any
	// The SHA of the commit that needs a review. Not using the latest commit SHA may render your review comment outdated if a subsequent commit modifies the line you specify as the `position`. Defaults to the most recent commit in the pull request when you do not specify a value.
	CommitId any
	// The review action you want to perform. The review actions include: `APPROVE`, `REQUEST_CHANGES`, or `COMMENT`. By leaving this blank, you set the review action state to `PENDING`, which means you will need to [submit the pull request review](https://docs.github.com/enterprise-cloud@latest/rest/pulls/reviews#submit-a-review-for-a-pull-request) when you are ready.
	Event any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	PullNumber any
	// path parameter, not part of the API's own resource representation
	ReviewId any
}

type RequestReviewAttrs struct {
	Links any
	// How the author is associated with the repository.
	AuthorAssociation any
	// **Required** when using `REQUEST_CHANGES` or `COMMENT` for the `event` parameter. The body text of the pull request review.
	Body     any
	BodyHtml any
	BodyText any
	// Use the following table to specify the location, destination, and contents of the draft review comment.
	Comments any
	// The SHA of the commit that needs a review. Not using the latest commit SHA may render your review comment outdated if a subsequent commit modifies the line you specify as the `position`. Defaults to the most recent commit in the pull request when you do not specify a value.
	CommitId any
	// The review action you want to perform. The review actions include: `APPROVE`, `REQUEST_CHANGES`, or `COMMENT`. By leaving this blank, you set the review action state to `PENDING`, which means you will need to [submit the pull request review](https://docs.github.com/enterprise-cloud@latest/rest/pulls/reviews#submit-a-review-for-a-pull-request) when you are ready.
	Event   any
	HtmlUrl any
	// Unique identifier of the review
	Id             any
	NodeId         any
	PullRequestUrl any
	State          any
	SubmittedAt    any
	// A GitHub user.
	User any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	PullNumber any
	// path parameter, not part of the API's own resource representation
	ReviewId any
}

var RequestReview = ubx.ResourceBinding{
	WireType: "github_pull_request_review",
	Fields: ubx.FieldMap{
		"Body": ubx.FieldSpec{WireName: "body"},
		"Comments": ubx.FieldSpec{
			WireName: "comments",
			Kind:     "list",
			Fields:   RequestReview_CommentsFields,
		},
		"CommitId":   ubx.FieldSpec{WireName: "commit_id"},
		"Event":      ubx.FieldSpec{WireName: "event"},
		"Owner":      ubx.FieldSpec{WireName: "owner"},
		"Repo":       ubx.FieldSpec{WireName: "repo"},
		"PullNumber": ubx.FieldSpec{WireName: "pull_number"},
		"ReviewId":   ubx.FieldSpec{WireName: "review_id"},
	},
}
