# Code generated by `ubx sdk gen` from github_invitation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class InvitationConfig:
    invitation_source: Any = None
    org: Any = None
    page: Any = None
    per_page: Any = None
    role: Any = None

@dataclasses.dataclass
class InvitationAttrs:
    invitation_source: Any = None
    org: Any = None
    page: Any = None
    per_page: Any = None
    role: Any = None

Invitation = ubx.DataSourceBinding(
    wire_type="github_invitation",
    fields={
        "invitation_source": ubx.FieldSpec(wire_name="invitation_source"),
        "org": ubx.FieldSpec(wire_name="org"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "role": ubx.FieldSpec(wire_name="role"),
    },
)
