// Code generated by `ubx sdk gen` from github_dependabot_secret. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface SecretConfig {
  /** Value for your secret, encrypted with [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages) using the public key retrieved from the [Get a repository public key](https://docs.github.com/enterprise-cloud@latest/rest/dependabot/secrets#get-a-repository-public-key) endpoint. */
  encryptedValue?: string | Computed<string>;
  /** ID of the key you used to encrypt the secret. */
  keyId?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  owner: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  repo: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  secretName: string | Computed<string>;
}

export interface SecretAttrs {
  /** The real timestamp this object was created. (AI-inferred) */
  createdAt: string;
  /** Value for your secret, encrypted with [LibSodium](https://libsodium.gitbook.io/doc/bindings_for_other_languages) using the public key retrieved from the [Get a repository public key](https://docs.github.com/enterprise-cloud@latest/rest/dependabot/secrets#get-a-repository-public-key) endpoint. */
  encryptedValue: string;
  /** ID of the key you used to encrypt the secret. */
  keyId: string;
  /** The name of the secret. */
  name: string;
  /** The real timestamp this object was last updated. (AI-inferred) */
  updatedAt: string;
  /** path parameter, not part of the API's own resource representation */
  owner: string;
  /** path parameter, not part of the API's own resource representation */
  repo: string;
  /** path parameter, not part of the API's own resource representation */
  secretName: string;
}

export const Secret: ResourceBinding<SecretConfig, SecretAttrs> = {
  wireType: "github_dependabot_secret",
  fields: {
    encryptedValue: "encrypted_value",
    keyId: "key_id",
    owner: "owner",
    repo: "repo",
    secretName: "secret_name",
  },
};
