// Code generated by `ubx sdk gen` from github_immutable_releases_organization_settings. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ReleasesOrganizationSettingsConfig {
  org: string | Computed<string>;
}

export interface ReleasesOrganizationSettingsAttrs {
  /** The policy that controls how immutable releases are enforced in the organization. */
  enforcedRepositories: string;
  org: string;
  /** The API URL to use to get or set the selected repositories for immutable releases enforcement, when `enforced_repositories` is set to `selected`. */
  selectedRepositoriesUrl: string;
}

export const ReleasesOrganizationSettings: DataSourceBinding<ReleasesOrganizationSettingsConfig, ReleasesOrganizationSettingsAttrs> = {
  wireType: "github_immutable_releases_organization_settings",
  fields: {
    org: "org",
  },
};
