# Code generated by `ubx sdk gen` from github_pull_request. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Request_Links_Comments:
    # The URL to access the comments for this pull request via the GitHub API. (AI-inferred)
    href: Any = None

@dataclasses.dataclass
class Request_Links:
    # Hypermedia Link
    comments: Any = None
    # Hypermedia Link
    commits: Any = None
    # Hypermedia Link
    html: Any = None
    # Hypermedia Link
    issue: Any = None
    # Hypermedia Link
    review_comment: Any = None
    # Hypermedia Link
    review_comments: Any = None
    # Hypermedia Link
    self: Any = None
    # Hypermedia Link
    statuses: Any = None

@dataclasses.dataclass
class Request_Assignee:
    # The URL of the assignee's avatar image on GitHub. (AI-inferred)
    avatar_url: Any = None
    # The email address of the user assigned to the pull request, if publicly visible. (AI-inferred)
    email: Any = None
    # The URL to the events of the user assigned to the pull request, following the GitHub API user object format. (AI-inferred)
    events_url: Any = None
    # The URL to the GitHub API endpoint that returns the list of followers for the assignee. (AI-inferred)
    followers_url: Any = None
    # The API URL to list the users this user is following. This is a template URL that includes an optional `{/other_user}` placeholder to query a specific user's following relationship. (AI-inferred)
    following_url: Any = None
    # The URL to the assignee's list of gists on GitHub. (AI-inferred)
    gists_url: Any = None
    # The Gravatar ID of the assignee, used to fetch the user's avatar image from Gravatar. (AI-inferred)
    gravatar_id: Any = None
    # The HTML URL to the GitHub profile of the assignee. (AI-inferred)
    html_url: Any = None
    # The numeric identifier of the GitHub user assigned to the pull request. (AI-inferred)
    id: Any = None
    # The GitHub username of the user assigned to the pull request. (AI-inferred)
    login: Any = None
    # The display name of the user assigned to the pull request. This field is optional and may be null if the user has not set a name. (AI-inferred)
    name: Any = None
    # The global node ID of the user assigned to this pull request. (AI-inferred)
    node_id: Any = None
    # The API URL that lists the organizations to which the user (assignee) belongs. This is a standard field on GitHub user objects. (AI-inferred)
    organizations_url: Any = None
    # The URL of the GitHub API endpoint that lists events received by the assignee user. (AI-inferred)
    received_events_url: Any = None
    # The URL to list the repositories owned by the assignee user. (AI-inferred)
    repos_url: Any = None
    # Indicates whether the assignee is a GitHub site administrator. (AI-inferred)
    site_admin: Any = None
    starred_at: Any = None
    # URL template for listing the assignee's starred repositories, with placeholders for {owner} and {repo}. (AI-inferred)
    starred_url: Any = None
    # The API URL to list repositories that the assignee is subscribed to. (AI-inferred)
    subscriptions_url: Any = None
    # The type of the assignee's GitHub account, such as 'User' or 'Bot'. (AI-inferred)
    type: Any = None
    # The GitHub API URL for the user assigned to the pull request. (AI-inferred)
    url: Any = None
    # Specifies the user's view type, indicating whether the user is a public or private user. Possible values: 'public', 'private'. (AI-inferred)
    user_view_type: Any = None

@dataclasses.dataclass
class Request_AutoMerge:
    # Commit message for the merge commit.
    commit_message: Any = None
    # Title for the merge commit message.
    commit_title: Any = None
    # A GitHub user.
    enabled_by: Any = None
    # The merge method to use.
    merge_method: Any = None

@dataclasses.dataclass
class Request_Labels:
    # The label's color, represented as a six-character hex code (e.g., 'ffffff') without the leading '#'. (AI-inferred)
    color: Any = None
    # Indicates whether the label is a default label assigned by GitHub (e.g., bug, enhancement) rather than a custom label created by the repository owner. (AI-inferred)
    default: Any = None
    # A brief description of the label, explaining its meaning or purpose. (AI-inferred)
    description: Any = None
    # The unique numeric identifier of the label attached to the pull request. (AI-inferred)
    id: Any = None
    # The name of the label applied to the pull request. (AI-inferred)
    name: Any = None
    # The GraphQL global node ID for the label. (AI-inferred)
    node_id: Any = None
    # The API URL for this label. (AI-inferred)
    url: Any = None

@dataclasses.dataclass
class Request_Milestone:
    # The timestamp of when the milestone was closed, in ISO 8601 format. (AI-inferred)
    closed_at: Any = None
    # The number of issues associated with this milestone that are currently closed. (AI-inferred)
    closed_issues: Any = None
    # The timestamp of when the milestone was created, in ISO 8601 format (e.g., YYYY-MM-DDTHH:MM:SSZ). (AI-inferred)
    created_at: Any = None
    # A GitHub user.
    creator: Any = None
    # The description of the milestone associated with the pull request. (AI-inferred)
    description: Any = None
    # The due date of the milestone, in ISO 8601 format (e.g., YYYY-MM-DDTHH:MM:SSZ). This field is required, so it always has a value. (AI-inferred)
    due_on: Any = None
    # The URL to view the milestone on GitHub. (AI-inferred)
    html_url: Any = None
    id: Any = None
    # The URL for the labels endpoint of this milestone, which lists the labels associated with it. (AI-inferred)
    labels_url: Any = None
    # The node ID of the milestone in the GitHub GraphQL API. (AI-inferred)
    node_id: Any = None
    # The number of the milestone.
    number: Any = None
    # The number of open issues associated with this milestone. (AI-inferred)
    open_issues: Any = None
    # The state of the milestone.
    state: Any = None
    # The title of the milestone.
    title: Any = None
    # The timestamp of the last modification to the milestone associated with the pull request. (AI-inferred)
    updated_at: Any = None
    # The API URL for the milestone. (AI-inferred)
    url: Any = None

@dataclasses.dataclass
class Request_RequestedTeams:
    # The description of the team that is requested for review on the pull request. (AI-inferred)
    description: Any = None
    enterprise_id: Any = None
    # The URL to the team's page on GitHub. (AI-inferred)
    html_url: Any = None
    # The unique identifier assigned to the team in GitHub. (AI-inferred)
    id: Any = None
    # The LDAP distinguished name (DN) of the team that has been requested to review the pull request. (AI-inferred)
    ldap_dn: Any = None
    # URL to retrieve the members of this team, with a placeholder for a specific member. (AI-inferred)
    members_url: Any = None
    # The name of the team that is requested for review on this pull request. (AI-inferred)
    name: Any = None
    # The GraphQL node ID of the team. (AI-inferred)
    node_id: Any = None
    # The team's notification setting, indicating whether notifications are enabled or disabled. Possible values: 'notifications_enabled', 'notifications_disabled'. (AI-inferred)
    notification_setting: Any = None
    # The unique identifier of the organization that owns the team requested for review on this pull request. (AI-inferred)
    organization_id: Any = None
    # The level of access the team has to the repository (e.g., 'pull', 'push', 'admin'). (AI-inferred)
    permission: Any = None
    # The privacy level of the team. For GitHub teams, this can be either 'secret' or 'closed'. (AI-inferred)
    privacy: Any = None
    # The API URL that points to the list of repositories belonging to this requested team. (AI-inferred)
    repositories_url: Any = None
    # The slug of the team, a URL-friendly identifier used in the GitHub API to reference the team. (AI-inferred)
    slug: Any = None
    # The type of the requested team, either 'enterprise' or 'organization'. (AI-inferred)
    type: Any = None
    # The API URL for the team, used to retrieve team details from the GitHub API. (AI-inferred)
    url: Any = None

@dataclasses.dataclass
class Request_Stack_Base:
    # The base ref of the stack this pull request belongs to.
    ref: Any = None
    # The base SHA of the stack this pull request belongs to.
    sha: Any = None

@dataclasses.dataclass
class Request_Stack:
    # The pull request's base branch section, containing details such as the branch name, commit SHA, and repository information. (AI-inferred)
    base: Any = None
    # The ID of the stack that this pull request belongs to.
    id: Any = None
    # The number of the stack that this pull request belongs to.
    number: Any = None
    # The one-based position of this pull request within the stack, where 1 is the bottom of the stack.
    position: Any = None
    # The total number of pull requests in the stack.
    size: Any = None

@dataclasses.dataclass
class RequestConfig:
    # The name of the branch you want the changes pulled into. This should be an existing branch on the current repository. You cannot submit a pull request to one repository that requests a merge to a base of another repository.
    base: Any = None
    # The contents of the pull request.
    body: Any = None
    # Indicates whether the pull request is a draft. See "[Draft Pull Requests](https://docs.github.com/articles/about-pull-requests#draft-pull-requests)" in the GitHub Help documentation to learn more.
    draft: Any = None
    # The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace `head` with a user like this: `username:branch`.
    head: Any = None
    # The name of the repository where the changes in the pull request were made. This field is required for cross-repository pull requests if both repositories are owned by the same organization.
    head_repo: Any = None
    # An issue in the repository to convert to a pull request. The issue title, body, and comments will become the title, body, and comments on the new pull request. Required unless `title` is specified.
    issue: Any = None
    # Indicates whether [maintainers can modify](https://docs.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) the pull request.
    maintainer_can_modify: Any = None
    # The title of the new pull request. Required unless `issue` is specified.
    title: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    pull_number: Any = None

@dataclasses.dataclass
class RequestAttrs:
    # The hypermedia links associated with the pull request, including URLs for related resources such as the pull request itself, its HTML page, comments, and status checks. (AI-inferred)
    links: Any = None
    # The reason a pull request is currently locked, if any. Possible values include 'off-topic', 'too heated', 'resolved', and 'spam'. This field is null when the pull request is not locked. (AI-inferred)
    active_lock_reason: Any = None
    # The total number of lines added in the pull request's diff, as computed by GitHub. (AI-inferred)
    additions: Any = None
    # A GitHub user.
    assignee: Any = None
    # A list of GitHub user objects representing the users assigned to the pull request. Each object contains standard user attributes such as login, id, and node_id. (AI-inferred)
    assignees: Any = None
    # How the author is associated with the repository.
    author_association: Any = None
    # The status of auto merging a pull request.
    auto_merge: Any = None
    # The name of the branch you want the changes pulled into. This should be an existing branch on the current repository. You cannot submit a pull request to one repository that requests a merge to a base of another repository.
    base: Any = None
    # The contents of the pull request.
    body: Any = None
    # The number of files that have been changed in this pull request. (AI-inferred)
    changed_files: Any = None
    # The timestamp of when the pull request was closed, or null if the pull request is still open. (AI-inferred)
    closed_at: Any = None
    # Total number of comments on the pull request. (AI-inferred)
    comments: Any = None
    # The URL to retrieve comments for this pull request. (AI-inferred)
    comments_url: Any = None
    # The number of commits contained in the pull request. (AI-inferred)
    commits: Any = None
    # The URL to retrieve the list of commits made in the pull request. (AI-inferred)
    commits_url: Any = None
    # The timestamp at which the pull request was created, automatically set by the GitHub API. (AI-inferred)
    created_at: Any = None
    # The number of lines deleted in the pull request's diff. This is computed by GitHub and reflects the total deletions across all changed files. (AI-inferred)
    deletions: Any = None
    # The URL to the diff file for this pull request. (AI-inferred)
    diff_url: Any = None
    # Indicates whether the pull request is a draft. See "[Draft Pull Requests](https://docs.github.com/articles/about-pull-requests#draft-pull-requests)" in the GitHub Help documentation to learn more.
    draft: Any = None
    # The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace `head` with a user like this: `username:branch`.
    head: Any = None
    # The name of the repository where the changes in the pull request were made. This field is required for cross-repository pull requests if both repositories are owned by the same organization.
    head_repo: Any = None
    # The URL to the pull request's page on GitHub, typically used to open the pull request in a web browser. (AI-inferred)
    html_url: Any = None
    # The unique numeric identifier assigned to the pull request by GitHub. (AI-inferred)
    id: Any = None
    # An issue in the repository to convert to a pull request. The issue title, body, and comments will become the title, body, and comments on the new pull request. Required unless `title` is specified.
    issue: Any = None
    # The GitHub API URL for the issue associated with this pull request. Since pull requests are issues, this URL points to the pull request's issue endpoint. (AI-inferred)
    issue_url: Any = None
    labels: Any = None
    # Indicates whether the pull request conversation is locked, restricting commenting to users with write access. This is a read-only value set by GitHub. (AI-inferred)
    locked: Any = None
    # Indicates whether [maintainers can modify](https://docs.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) the pull request.
    maintainer_can_modify: Any = None
    # The SHA of the merge commit created when the pull request is merged. This value is computed by GitHub and is only populated after a successful merge. (AI-inferred)
    merge_commit_sha: Any = None
    # Whether the pull request is mergeable, based on absence of merge conflicts and passing of required status checks. This is computed and reflects the current state of the pull request. (AI-inferred)
    mergeable: Any = None
    # The mergeability state of the pull request, such as clean, unstable, blocked, draft, or unknown. (AI-inferred)
    mergeable_state: Any = None
    # Indicates whether the pull request has been merged (true) or not (false). (AI-inferred)
    merged: Any = None
    # The timestamp (in RFC3339 format) of when the pull request was merged, or null if it has not been merged. (AI-inferred)
    merged_at: Any = None
    # A GitHub user.
    merged_by: Any = None
    # A collection of related issues and pull requests.
    milestone: Any = None
    # The GraphQL node ID for the pull request, used to identify the resource in the GitHub GraphQL API. (AI-inferred)
    node_id: Any = None
    # Number uniquely identifying the pull request within its repository.
    number: Any = None
    # The URL to the patch file for this pull request. (AI-inferred)
    patch_url: Any = None
    # Whether the pull request can be rebased. (AI-inferred)
    rebaseable: Any = None
    # List of users and/or teams that have been requested to review the pull request. (AI-inferred)
    requested_reviewers: Any = None
    # Teams that have been requested to review this pull request. Each item contains team details such as id, name, slug, and permissions. (AI-inferred)
    requested_teams: Any = None
    # The URL to the review comments for this pull request, provided by the GitHub API. (AI-inferred)
    review_comment_url: Any = None
    # The number of review comments on the pull request. (AI-inferred)
    review_comments: Any = None
    # The API endpoint URL for the list of review comments on this pull request. (AI-inferred)
    review_comments_url: Any = None
    # The stack information associated with a pull request.
    stack: Any = None
    # State of this Pull Request. Either `open` or `closed`.
    state: Any = None
    # The API URL to query the commit statuses associated with the pull request's head commit. (AI-inferred)
    statuses_url: Any = None
    # The title of the new pull request. Required unless `issue` is specified.
    title: Any = None
    # The timestamp of the last update to the pull request, in ISO 8601 format (e.g., 2025-04-01T12:34:56Z). (AI-inferred)
    updated_at: Any = None
    # The API URL of the pull request, e.g., `https://api.github.com/repos/{owner}/{repo}/pulls/{number}`. (AI-inferred)
    url: Any = None
    # A GitHub user.
    user: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    pull_number: Any = None

Request = ubx.ResourceBinding(
    wire_type="github_pull_request",
    fields={
        "base": ubx.FieldSpec(wire_name="base"),
        "body": ubx.FieldSpec(wire_name="body"),
        "draft": ubx.FieldSpec(wire_name="draft"),
        "head": ubx.FieldSpec(wire_name="head"),
        "head_repo": ubx.FieldSpec(wire_name="head_repo"),
        "issue": ubx.FieldSpec(wire_name="issue"),
        "maintainer_can_modify": ubx.FieldSpec(wire_name="maintainer_can_modify"),
        "title": ubx.FieldSpec(wire_name="title"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
        "pull_number": ubx.FieldSpec(wire_name="pull_number"),
    },
)
