// Code generated by `ubx sdk gen` from github_interaction_limit. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface LimitConfig {
  org: string | Computed<string>;
}

export interface LimitAttrs {
  org: string;
}

export const Limit: DataSourceBinding<LimitConfig, LimitAttrs> = {
  wireType: "github_interaction_limit",
  fields: {
    org: "org",
  },
};
