// Code generated by `ubx sdk gen` from github_community_profile. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Profile_Files_CodeOfConduct {
  htmlUrl: string | Computed<string>;
  key: string | Computed<string>;
  name: string | Computed<string>;
  url: string | Computed<string>;
}

export interface Profile_Files_CodeOfConductFile {
  htmlUrl: string | Computed<string>;
  url: string | Computed<string>;
}

export interface Profile_Files_License {
  htmlUrl?: string | Computed<string>;
  key: string | Computed<string>;
  name: string | Computed<string>;
  nodeId: string | Computed<string>;
  spdxId: string | Computed<string>;
  url: string | Computed<string>;
}

export interface Profile_Files {
  /** Code of Conduct Simple */
  codeOfConduct: Profile_Files_CodeOfConduct | Computed<Profile_Files_CodeOfConduct>;
  codeOfConductFile: Profile_Files_CodeOfConductFile | Computed<Profile_Files_CodeOfConductFile>;
  contributing: Profile_Files_CodeOfConductFile | Computed<Profile_Files_CodeOfConductFile>;
  issueTemplate: Profile_Files_CodeOfConductFile | Computed<Profile_Files_CodeOfConductFile>;
  /** License Simple */
  license: Profile_Files_License | Computed<Profile_Files_License>;
  pullRequestTemplate: Profile_Files_CodeOfConductFile | Computed<Profile_Files_CodeOfConductFile>;
  readme: Profile_Files_CodeOfConductFile | Computed<Profile_Files_CodeOfConductFile>;
}

export interface ProfileConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface ProfileAttrs {
  contentReportsEnabled: boolean;
  description: string;
  documentation: string;
  files: Profile_Files;
  healthPercentage: number;
  owner: string;
  repo: string;
  updatedAt: string;
}

export const Profile: DataSourceBinding<ProfileConfig, ProfileAttrs> = {
  wireType: "github_community_profile",
  fields: {
    owner: "owner",
    repo: "repo",
  },
};
