// Code generated by `ubx sdk gen` from github_workflow_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface List_Workflows {
  badgeUrl?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  deletedAt?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  path?: string | Computed<string>;
  state?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface ListConfig {
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  repo: string | Computed<string>;
}

export interface ListAttrs {
  owner: string;
  page: number;
  perPage: number;
  repo: string;
  totalCount: number;
  workflows: List_Workflows[];
}

export const List: DataSourceBinding<ListConfig, ListAttrs> = {
  wireType: "github_workflow_list",
  fields: {
    owner: "owner",
    page: "page",
    perPage: "per_page",
    repo: "repo",
  },
};
