// Code generated by `ubx sdk gen` from github_task. DO NOT EDIT.
package task

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type TaskConfig struct {
	// Base ref for new branch/PR
	BaseRef any
	// Whether to create a PR.
	CreatePullRequest any
	// Optional identifier for a custom agent to use for this task. Use the custom agent's filename without the extension - for example, for a `.github/agents/performance-optimizer.agent.md` custom agent, use `performance-optimizer`.
	CustomAgent any
	// Head ref for existing branch/PR. If provided with `base_ref`, the agent looks up open PR context for `head_ref` targeting `base_ref` and commits to `head_ref` instead of creating a new branch.
	HeadRef any
	// The model to use for this task. The allowed models may change over time and depend on the user's GitHub Copilot plan and organization policies. Currently supported values: `claude-sonnet-4.6`, `claude-opus-4.6`, `gpt-5.2-codex`, `gpt-5.3-codex`, `gpt-5.4`, `claude-sonnet-4.5`, `claude-opus-4.5`
	Model any
	// The user's prompt for the agent
	Prompt any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	TaskId any
}

type TaskAttrs struct {
	// Base ref for new branch/PR
	BaseRef any
	// Whether to create a PR.
	CreatePullRequest any
	// Optional identifier for a custom agent to use for this task. Use the custom agent's filename without the extension - for example, for a `.github/agents/performance-optimizer.agent.md` custom agent, use `performance-optimizer`.
	CustomAgent any
	// Head ref for existing branch/PR. If provided with `base_ref`, the agent looks up open PR context for `head_ref` targeting `base_ref` and commits to `head_ref` instead of creating a new branch.
	HeadRef any
	// The model to use for this task. The allowed models may change over time and depend on the user's GitHub Copilot plan and organization policies. Currently supported values: `claude-sonnet-4.6`, `claude-opus-4.6`, `gpt-5.2-codex`, `gpt-5.3-codex`, `gpt-5.4`, `claude-sonnet-4.5`, `claude-opus-4.5`
	Model any
	// The user's prompt for the agent
	Prompt any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	TaskId any
}

var Task = ubx.ResourceBinding{
	WireType: "github_task",
	Fields: ubx.FieldMap{
		"BaseRef": ubx.FieldSpec{WireName: "base_ref"},
		"CreatePullRequest": ubx.FieldSpec{WireName: "create_pull_request"},
		"CustomAgent": ubx.FieldSpec{WireName: "custom_agent"},
		"HeadRef": ubx.FieldSpec{WireName: "head_ref"},
		"Model": ubx.FieldSpec{WireName: "model"},
		"Prompt": ubx.FieldSpec{WireName: "prompt"},
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
		"TaskId": ubx.FieldSpec{WireName: "task_id"},
	},
}
