# Code generated by `ubx sdk gen` from github_member. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Member_Seats_Assignee:
    avatar_url: Any = None
    email: Any = None
    events_url: Any = None
    followers_url: Any = None
    following_url: Any = None
    gists_url: Any = None
    gravatar_id: Any = None
    html_url: Any = None
    id: Any = None
    login: Any = None
    name: Any = None
    node_id: Any = None
    organizations_url: Any = None
    received_events_url: Any = None
    repos_url: Any = None
    site_admin: Any = None
    starred_at: Any = None
    starred_url: Any = None
    subscriptions_url: Any = None
    type: Any = None
    url: Any = None
    user_view_type: Any = None

@dataclasses.dataclass
class Member_Seats_AssigningTeam_Parent:
    description: Any = None
    enterprise_id: Any = None
    html_url: Any = None
    id: Any = None
    ldap_dn: Any = None
    members_url: Any = None
    name: Any = None
    node_id: Any = None
    notification_setting: Any = None
    organization_id: Any = None
    permission: Any = None
    privacy: Any = None
    repositories_url: Any = None
    slug: Any = None
    type: Any = None
    url: Any = None

@dataclasses.dataclass
class Member_Seats_AssigningTeam_Permissions:
    admin: Any = None
    maintain: Any = None
    pull: Any = None
    push: Any = None
    triage: Any = None

@dataclasses.dataclass
class Member_Seats_AssigningTeam:
    access_source: Any = None
    created_at: Any = None
    description: Any = None
    enterprise_id: Any = None
    group_id: Any = None
    group_name: Any = None
    html_url: Any = None
    id: Any = None
    members_url: Any = None
    name: Any = None
    node_id: Any = None
    notification_setting: Any = None
    organization_id: Any = None
    organization_selection_type: Any = None
    parent: Any = None
    permission: Any = None
    permissions: Any = None
    privacy: Any = None
    repositories_url: Any = None
    slug: Any = None
    sync_to_organizations: Any = None
    type: Any = None
    updated_at: Any = None
    url: Any = None

@dataclasses.dataclass
class Member_Seats_Organization:
    avatar_url: Any = None
    description: Any = None
    events_url: Any = None
    hooks_url: Any = None
    id: Any = None
    issues_url: Any = None
    login: Any = None
    members_url: Any = None
    node_id: Any = None
    public_members_url: Any = None
    repos_url: Any = None
    url: Any = None

@dataclasses.dataclass
class Member_Seats:
    assignee: Any = None
    assigning_team: Any = None
    created_at: Any = None
    last_activity_at: Any = None
    last_activity_editor: Any = None
    last_authenticated_at: Any = None
    organization: Any = None
    pending_cancellation_date: Any = None
    plan_type: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class MemberConfig:
    enterprise: Any = None
    username: Any = None

@dataclasses.dataclass
class MemberAttrs:
    enterprise: Any = None
    seats: Any = None
    # The total number of Copilot seats the enterprise is being billed for. Users with access through enterprise, enterprise teams or multiple organizations are only counted once.
    total_seats: Any = None
    username: Any = None

Member = ubx.DataSourceBinding(
    wire_type="github_member",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
        "username": ubx.FieldSpec(wire_name="username"),
    },
)
