// Code generated by `ubx sdk gen` from github_issue. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface IssueConfig {
  direction?: string | Computed<string>;
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  repo: string | Computed<string>;
  since?: string | Computed<string>;
  sort?: string | Computed<string>;
}

export interface IssueAttrs {
  direction: string;
  owner: string;
  page: number;
  perPage: number;
  repo: string;
  since: string;
  sort: string;
}

export const Issue: DataSourceBinding<IssueConfig, IssueAttrs> = {
  wireType: "github_issue",
  fields: {
    direction: "direction",
    owner: "owner",
    page: "page",
    perPage: "per_page",
    repo: "repo",
    since: "since",
    sort: "sort",
  },
};
