// Code generated by `ubx sdk gen` from github_issue_type. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface TypeConfig {
  org: string | Computed<string>;
}

export interface TypeAttrs {
  org: string;
}

export const Type: DataSourceBinding<TypeConfig, TypeAttrs> = {
  wireType: "github_issue_type",
  fields: {
    org: "org",
  },
};
