// Code generated by `ubx sdk gen` from github_task. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface TaskConfig {
  /** Base ref for new branch/PR */
  baseRef?: string | Computed<string>;
  /** Whether to create a PR. */
  createPullRequest?: boolean | Computed<boolean>;
  /** Optional identifier for a custom agent to use for this task. Use the custom agent's filename without the extension - for example, for a `.github/agents/performance-optimizer.agent.md` custom agent, use `performance-optimizer`. */
  customAgent?: string | Computed<string>;
  /** Head ref for existing branch/PR. If provided with `base_ref`, the agent looks up open PR context for `head_ref` targeting `base_ref` and commits to `head_ref` instead of creating a new branch. */
  headRef?: string | Computed<string>;
  /** The model to use for this task. The allowed models may change over time and depend on the user's GitHub Copilot plan and organization policies. Currently supported values: `claude-sonnet-4.6`, `claude-opus-4.6`, `gpt-5.2-codex`, `gpt-5.3-codex`, `gpt-5.4`, `claude-sonnet-4.5`, `claude-opus-4.5` */
  model?: string | Computed<string>;
  /** The user's prompt for the agent */
  prompt: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  owner: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  repo: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  taskId: string | Computed<string>;
}

export interface TaskAttrs {
  /** Base ref for new branch/PR */
  baseRef: string;
  /** Whether to create a PR. */
  createPullRequest: boolean;
  /** Optional identifier for a custom agent to use for this task. Use the custom agent's filename without the extension - for example, for a `.github/agents/performance-optimizer.agent.md` custom agent, use `performance-optimizer`. */
  customAgent: string;
  /** Head ref for existing branch/PR. If provided with `base_ref`, the agent looks up open PR context for `head_ref` targeting `base_ref` and commits to `head_ref` instead of creating a new branch. */
  headRef: string;
  /** The model to use for this task. The allowed models may change over time and depend on the user's GitHub Copilot plan and organization policies. Currently supported values: `claude-sonnet-4.6`, `claude-opus-4.6`, `gpt-5.2-codex`, `gpt-5.3-codex`, `gpt-5.4`, `claude-sonnet-4.5`, `claude-opus-4.5` */
  model: string;
  /** The user's prompt for the agent */
  prompt: string;
  /** path parameter, not part of the API's own resource representation */
  owner: string;
  /** path parameter, not part of the API's own resource representation */
  repo: string;
  /** path parameter, not part of the API's own resource representation */
  taskId: string;
}

export const Task: ResourceBinding<TaskConfig, TaskAttrs> = {
  wireType: "github_task",
  fields: {
    baseRef: "base_ref",
    createPullRequest: "create_pull_request",
    customAgent: "custom_agent",
    headRef: "head_ref",
    model: "model",
    prompt: "prompt",
    owner: "owner",
    repo: "repo",
    taskId: "task_id",
  },
};
