// Code generated by `ubx sdk gen` from github_member. DO NOT EDIT.
package member

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type MemberConfig struct {
	Filter  any
	Org     any
	Page    any
	PerPage any
	Role    any
}

type MemberAttrs struct {
	Filter  any
	Org     any
	Page    any
	PerPage any
	Role    any
}

var Member = ubx.DataSourceBinding{
	WireType: "github_member",
	Fields: ubx.FieldMap{
		"Filter":  ubx.FieldSpec{WireName: "filter"},
		"Org":     ubx.FieldSpec{WireName: "org"},
		"Page":    ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"Role":    ubx.FieldSpec{WireName: "role"},
	},
}
