// Code generated by `ubx sdk gen` from github_budget_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface List_Budgets_BudgetAlerting {
  alertRecipients?: string[] | Computed<string[]>;
  willAlert?: boolean | Computed<boolean>;
}

export interface List_Budgets {
  budgetAlerting?: List_Budgets_BudgetAlerting | Computed<List_Budgets_BudgetAlerting>;
  budgetAmount?: number | Computed<number>;
  budgetEntityName?: string | Computed<string>;
  budgetProductSku?: string | Computed<string>;
  budgetScope?: string | Computed<string>;
  budgetType?: string | Computed<string>;
  consumedAmount?: number | Computed<number>;
  expiresAt?: string | Computed<string>;
  id?: string | Computed<string>;
  preventFurtherUsage?: boolean | Computed<boolean>;
  user?: string | Computed<string>;
}

export interface List_EffectiveBudget {
  /** The budget amount for the effective budget. */
  budgetAmount: number | Computed<number>;
  /** The consumed amount for the specified user within the effective budget. */
  consumedAmount: number | Computed<number>;
  /** The unique identifier of the effective budget. */
  id: string | Computed<string>;
}

export interface ListConfig {
  enterprise: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  scope?: string | Computed<string>;
  user?: string | Computed<string>;
}

export interface ListAttrs {
  /** Array of budget objects for the enterprise */
  budgets: List_Budgets[];
  /** Effective user-level budget details returned when the response is scoped with the `user` query parameter. */
  effectiveBudget: List_EffectiveBudget;
  enterprise: string;
  /** Indicates if there are more pages of results available (maps to hasNextPage from billing platform) */
  hasNextPage: boolean;
  page: number;
  perPage: number;
  scope: string;
  /** Total number of budgets matching the query */
  totalCount: number;
  user: string;
}

export const List: DataSourceBinding<ListConfig, ListAttrs> = {
  wireType: "github_budget_list",
  fields: {
    enterprise: "enterprise",
    page: "page",
    perPage: "per_page",
    scope: "scope",
    user: "user",
  },
};
