# Code generated by `ubx sdk gen` from github_plan. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PlanConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class PlanAttrs:
    page: Any = None
    per_page: Any = None

Plan = ubx.DataSourceBinding(
    wire_type="github_plan",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
