// Code generated by `ubx sdk gen` from github_branch. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface BranchConfig {
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  protected?: boolean | Computed<boolean>;
  repo: string | Computed<string>;
}

export interface BranchAttrs {
  owner: string;
  page: number;
  perPage: number;
  protected: boolean;
  repo: string;
}

export const Branch: DataSourceBinding<BranchConfig, BranchAttrs> = {
  wireType: "github_branch",
  fields: {
    owner: "owner",
    page: "page",
    perPage: "per_page",
    protected: "protected",
    repo: "repo",
  },
};
