# Code generated by `ubx sdk gen` from github_assignment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class AssignmentConfig:
    classroom_id: Any = None
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class AssignmentAttrs:
    classroom_id: Any = None
    page: Any = None
    per_page: Any = None

Assignment = ubx.DataSourceBinding(
    wire_type="github_assignment",
    fields={
        "classroom_id": ubx.FieldSpec(wire_name="classroom_id"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
