# Code generated by `ubx sdk gen` from github_interaction_limit. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LimitConfig:
    org: Any = None

@dataclasses.dataclass
class LimitAttrs:
    org: Any = None

Limit = ubx.DataSourceBinding(
    wire_type="github_interaction_limit",
    fields={
        "org": ubx.FieldSpec(wire_name="org"),
    },
)
