// Code generated by `ubx sdk gen` from github_ruleset_version_with_state. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface VersionWithStateConfig {
  enterprise: string | Computed<string>;
  rulesetId: number | Computed<number>;
  versionId: number | Computed<number>;
}

export interface VersionWithStateAttrs {
  enterprise: string;
  rulesetId: number;
  versionId: number;
}

export const VersionWithState: DataSourceBinding<VersionWithStateConfig, VersionWithStateAttrs> = {
  wireType: "github_ruleset_version_with_state",
  fields: {
    enterprise: "enterprise",
    rulesetId: "ruleset_id",
    versionId: "version_id",
  },
};
