// Code generated by `ubx sdk gen` from github_issue. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Issue_ClosedBy {
  avatarUrl: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl: string | Computed<string>;
  followersUrl: string | Computed<string>;
  followingUrl: string | Computed<string>;
  gistsUrl: string | Computed<string>;
  gravatarId: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  id: number | Computed<number>;
  login: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId: string | Computed<string>;
  organizationsUrl: string | Computed<string>;
  receivedEventsUrl: string | Computed<string>;
  reposUrl: string | Computed<string>;
  siteAdmin: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  starredUrl: string | Computed<string>;
  subscriptionsUrl: string | Computed<string>;
  type: string | Computed<string>;
  url: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface Issue_IssueDependenciesSummary {
  blockedBy: number | Computed<number>;
  blocking: number | Computed<number>;
  totalBlockedBy: number | Computed<number>;
  totalBlocking: number | Computed<number>;
}

export interface Issue_IssueFieldValues {
  fieldId?: number | Computed<number>;
  value?: unknown | Computed<unknown>;
}

export interface Issue_PerformedViaGithubApp_Owner {
  avatarUrl?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  description?: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl?: string | Computed<string>;
  followersUrl?: string | Computed<string>;
  followingUrl?: string | Computed<string>;
  gistsUrl?: string | Computed<string>;
  gravatarId?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  login?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  organizationsUrl?: string | Computed<string>;
  receivedEventsUrl?: string | Computed<string>;
  reposUrl?: string | Computed<string>;
  siteAdmin?: boolean | Computed<boolean>;
  slug?: string | Computed<string>;
  starredAt?: string | Computed<string>;
  starredUrl?: string | Computed<string>;
  subscriptionsUrl?: string | Computed<string>;
  type?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  userViewType?: string | Computed<string>;
  websiteUrl?: string | Computed<string>;
}

export interface Issue_PerformedViaGithubApp_Permissions {
  checks?: string | Computed<string>;
  contents?: string | Computed<string>;
  deployments?: string | Computed<string>;
  issues?: string | Computed<string>;
  metadata?: string | Computed<string>;
}

export interface Issue_PerformedViaGithubApp {
  clientId?: string | Computed<string>;
  createdAt: string | Computed<string>;
  description: string | Computed<string>;
  /** The list of events for the GitHub app. Note that the `installation_target`, `security_advisory`, and `meta` events are not included because they are global events and not specific to an installation. */
  events: string[] | Computed<string[]>;
  externalUrl: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  /** Unique identifier of the GitHub app */
  id: number | Computed<number>;
  /** The number of installations associated with the GitHub app. Only returned when the integration is requesting details about itself. */
  installationsCount?: number | Computed<number>;
  /** The name of the GitHub app */
  name: string | Computed<string>;
  nodeId: string | Computed<string>;
  owner: Issue_PerformedViaGithubApp_Owner | Computed<Issue_PerformedViaGithubApp_Owner>;
  /** The set of permissions for the GitHub app */
  permissions: Issue_PerformedViaGithubApp_Permissions | Computed<Issue_PerformedViaGithubApp_Permissions>;
  /** The slug name of the GitHub app */
  slug?: string | Computed<string>;
  updatedAt: string | Computed<string>;
}

export interface Issue_PinnedComment_Minimized {
  /** The reason the comment was minimized. */
  reason: string | Computed<string>;
}

export interface Issue_PinnedComment_Pin {
  pinnedAt: string | Computed<string>;
  /** A GitHub user. */
  pinnedBy: Issue_ClosedBy | Computed<Issue_ClosedBy>;
}

export interface Issue_PinnedComment_Reactions {
  confused: number | Computed<number>;
  eyes: number | Computed<number>;
  heart: number | Computed<number>;
  hooray: number | Computed<number>;
  laugh: number | Computed<number>;
  rocket: number | Computed<number>;
  totalCount: number | Computed<number>;
  url: string | Computed<string>;
}

export interface Issue_PinnedComment {
  /** How the author is associated with the repository. */
  authorAssociation?: string | Computed<string>;
  /** Contents of the issue comment */
  body?: string | Computed<string>;
  bodyHtml?: string | Computed<string>;
  bodyText?: string | Computed<string>;
  createdAt: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  /** Unique identifier of the issue comment */
  id: number | Computed<number>;
  issueUrl: string | Computed<string>;
  /** Details about why an issue comment was minimized. */
  minimized?: Issue_PinnedComment_Minimized | Computed<Issue_PinnedComment_Minimized>;
  nodeId: string | Computed<string>;
  /** GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub. */
  performedViaGithubApp?: Issue_PerformedViaGithubApp | Computed<Issue_PerformedViaGithubApp>;
  /** Context around who pinned an issue comment and when it was pinned. */
  pin?: Issue_PinnedComment_Pin | Computed<Issue_PinnedComment_Pin>;
  reactions?: Issue_PinnedComment_Reactions | Computed<Issue_PinnedComment_Reactions>;
  updatedAt: string | Computed<string>;
  /** URL for the issue comment */
  url: string | Computed<string>;
  /** A GitHub user. */
  user: Issue_ClosedBy | Computed<Issue_ClosedBy>;
}

export interface Issue_PullRequest {
  diffUrl: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  mergedAt?: string | Computed<string>;
  patchUrl: string | Computed<string>;
  url: string | Computed<string>;
}

export interface Issue_Repository_CodeSearchIndexStatus {
  lexicalCommitSha?: string | Computed<string>;
  lexicalSearchOk?: boolean | Computed<boolean>;
}

export interface Issue_Repository_License {
  htmlUrl?: string | Computed<string>;
  key: string | Computed<string>;
  name: string | Computed<string>;
  nodeId: string | Computed<string>;
  spdxId: string | Computed<string>;
  url: string | Computed<string>;
}

export interface Issue_Repository_Permissions {
  admin: boolean | Computed<boolean>;
  maintain?: boolean | Computed<boolean>;
  pull: boolean | Computed<boolean>;
  push: boolean | Computed<boolean>;
  triage?: boolean | Computed<boolean>;
}

export interface Issue_Repository {
  /** Whether to allow Auto-merge to be used on pull requests. */
  allowAutoMerge?: boolean | Computed<boolean>;
  /** Whether to allow forking this repo */
  allowForking?: boolean | Computed<boolean>;
  /** Whether to allow merge commits for pull requests. */
  allowMergeCommit?: boolean | Computed<boolean>;
  /** Whether to allow rebase merges for pull requests. */
  allowRebaseMerge?: boolean | Computed<boolean>;
  /** Whether to allow squash merges for pull requests. */
  allowSquashMerge?: boolean | Computed<boolean>;
  /** Whether or not a pull request head branch that is behind its base branch can always be updated even if it is not required to be up to date before merging. */
  allowUpdateBranch?: boolean | Computed<boolean>;
  /** Whether anonymous git access is enabled for this repository */
  anonymousAccessEnabled?: boolean | Computed<boolean>;
  archiveUrl: string | Computed<string>;
  /** Whether the repository is archived. */
  archived: boolean | Computed<boolean>;
  assigneesUrl: string | Computed<string>;
  blobsUrl: string | Computed<string>;
  branchesUrl: string | Computed<string>;
  cloneUrl: string | Computed<string>;
  /** The status of the code search index for this repository */
  codeSearchIndexStatus?: Issue_Repository_CodeSearchIndexStatus | Computed<Issue_Repository_CodeSearchIndexStatus>;
  collaboratorsUrl: string | Computed<string>;
  commentsUrl: string | Computed<string>;
  commitsUrl: string | Computed<string>;
  compareUrl: string | Computed<string>;
  contentsUrl: string | Computed<string>;
  contributorsUrl: string | Computed<string>;
  createdAt: string | Computed<string>;
  /** The default branch of the repository. */
  defaultBranch: string | Computed<string>;
  /** Whether to delete head branches when pull requests are merged */
  deleteBranchOnMerge?: boolean | Computed<boolean>;
  deploymentsUrl: string | Computed<string>;
  description: string | Computed<string>;
  /** Returns whether or not this repository disabled. */
  disabled: boolean | Computed<boolean>;
  downloadsUrl: string | Computed<string>;
  eventsUrl: string | Computed<string>;
  fork: boolean | Computed<boolean>;
  forks: number | Computed<number>;
  forksCount: number | Computed<number>;
  forksUrl: string | Computed<string>;
  fullName: string | Computed<string>;
  gitCommitsUrl: string | Computed<string>;
  gitRefsUrl: string | Computed<string>;
  gitTagsUrl: string | Computed<string>;
  gitUrl: string | Computed<string>;
  /** Whether discussions are enabled. */
  hasDiscussions?: boolean | Computed<boolean>;
  /** Whether downloads are enabled. */
  hasDownloads: boolean | Computed<boolean>;
  /** Whether issues are enabled. */
  hasIssues: boolean | Computed<boolean>;
  hasPages: boolean | Computed<boolean>;
  /** Whether projects are enabled. */
  hasProjects: boolean | Computed<boolean>;
  /** Whether pull requests are enabled. */
  hasPullRequests?: boolean | Computed<boolean>;
  /** Whether the wiki is enabled. */
  hasWiki: boolean | Computed<boolean>;
  homepage: string | Computed<string>;
  hooksUrl: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  /** Unique identifier of the repository */
  id: number | Computed<number>;
  /** Whether this repository acts as a template that can be used to generate new repositories. */
  isTemplate?: boolean | Computed<boolean>;
  issueCommentUrl: string | Computed<string>;
  issueEventsUrl: string | Computed<string>;
  issuesUrl: string | Computed<string>;
  keysUrl: string | Computed<string>;
  labelsUrl: string | Computed<string>;
  language: string | Computed<string>;
  languagesUrl: string | Computed<string>;
  /** License Simple */
  license: Issue_Repository_License | Computed<Issue_Repository_License>;
  masterBranch?: string | Computed<string>;
  /** The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. - `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message. */
  mergeCommitMessage?: string | Computed<string>;
  /** The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. - `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name). */
  mergeCommitTitle?: string | Computed<string>;
  mergesUrl: string | Computed<string>;
  milestonesUrl: string | Computed<string>;
  mirrorUrl: string | Computed<string>;
  /** The name of the repository. */
  name: string | Computed<string>;
  nodeId: string | Computed<string>;
  notificationsUrl: string | Computed<string>;
  openIssues: number | Computed<number>;
  openIssuesCount: number | Computed<number>;
  /** A GitHub user. */
  owner: Issue_ClosedBy | Computed<Issue_ClosedBy>;
  permissions?: Issue_Repository_Permissions | Computed<Issue_Repository_Permissions>;
  /** Whether the repository is private or public. */
  private: boolean | Computed<boolean>;
  /** The policy controlling who can create pull requests: all or collaborators_only. */
  pullRequestCreationPolicy?: string | Computed<string>;
  pullsUrl: string | Computed<string>;
  pushedAt: string | Computed<string>;
  releasesUrl: string | Computed<string>;
  /** The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0. */
  size: number | Computed<number>;
  /** The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. - `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message. */
  squashMergeCommitMessage?: string | Computed<string>;
  /** The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. - `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit). */
  squashMergeCommitTitle?: string | Computed<string>;
  sshUrl: string | Computed<string>;
  stargazersCount: number | Computed<number>;
  stargazersUrl: string | Computed<string>;
  starredAt?: string | Computed<string>;
  statusesUrl: string | Computed<string>;
  subscribersUrl: string | Computed<string>;
  subscriptionUrl: string | Computed<string>;
  svnUrl: string | Computed<string>;
  tagsUrl: string | Computed<string>;
  teamsUrl: string | Computed<string>;
  tempCloneToken?: string | Computed<string>;
  topics?: string[] | Computed<string[]>;
  treesUrl: string | Computed<string>;
  updatedAt: string | Computed<string>;
  url: string | Computed<string>;
  /** Whether a squash merge commit can use the pull request title as default. **This property is closing down. Please use `squash_merge_commit_title` instead. */
  useSquashPrTitleAsDefault?: boolean | Computed<boolean>;
  /** The repository visibility: public, private, or internal. */
  visibility?: string | Computed<string>;
  watchers: number | Computed<number>;
  watchersCount: number | Computed<number>;
  /** Whether to require contributors to sign off on web-based commits */
  webCommitSignoffRequired?: boolean | Computed<boolean>;
}

export interface Issue_SubIssuesSummary {
  completed: number | Computed<number>;
  percentCompleted: number | Computed<number>;
  total: number | Computed<number>;
}

const Issue_IssueFieldValuesFields: FieldMap = {
  fieldId: "field_id",
  value: "value",
};

export interface IssueConfig {
  /** Login for the user that this issue should be assigned to. _NOTE: Only users with push access can set the assignee for new issues. The assignee is silently dropped otherwise. **This field is closing down.**_ */
  assignee?: string | Computed<string>;
  /** Logins for Users to assign to this issue. _NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise._ */
  assignees?: string[] | Computed<string[]>;
  /** The contents of the issue. */
  body?: string | Computed<string>;
  /** An array of issue field values to set on this issue. Each field value must include the field ID and the value to set. Issue fields are only available for organization-owned repositories with the feature enabled. Field values are silently dropped otherwise. */
  issueFieldValues?: Issue_IssueFieldValues[] | Computed<Issue_IssueFieldValues[]>;
  /** Labels to associate with this issue. _NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise._ */
  labels?: unknown[] | Computed<unknown[]>;
  milestone?: unknown | Computed<unknown>;
  /** The id of the parent issue to add this issue to as a sub-issue. _NOTE: Only users with triage access to both the parent issue's repository and this repository can set the parent issue._ */
  parentIssueId?: number | Computed<number>;
  /** The title of the issue. */
  title: unknown | Computed<unknown>;
  /** The name of the issue type to associate with this issue. _NOTE: Only users with push access can set the type for new issues. The type is silently dropped otherwise._ */
  type?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  owner: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  repo: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  issueNumber: string | Computed<string>;
}

export interface IssueAttrs {
  activeLockReason: string;
  /** Login for the user that this issue should be assigned to. _NOTE: Only users with push access can set the assignee for new issues. The assignee is silently dropped otherwise. **This field is closing down.**_ */
  assignee: string;
  /** Logins for Users to assign to this issue. _NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise._ */
  assignees: string[];
  /** How the author is associated with the repository. */
  authorAssociation: string;
  /** The contents of the issue. */
  body: string;
  bodyHtml: string;
  bodyText: string;
  closedAt: string;
  /** A GitHub user. */
  closedBy: Issue_ClosedBy;
  comments: number;
  commentsUrl: string;
  createdAt: string;
  draft: boolean;
  eventsUrl: string;
  htmlUrl: string;
  id: number;
  issueDependenciesSummary: Issue_IssueDependenciesSummary;
  /** An array of issue field values to set on this issue. Each field value must include the field ID and the value to set. Issue fields are only available for organization-owned repositories with the feature enabled. Field values are silently dropped otherwise. */
  issueFieldValues: Issue_IssueFieldValues[];
  /** Labels to associate with this issue. _NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise._ */
  labels: unknown[];
  labelsUrl: string;
  locked: boolean;
  milestone: unknown;
  nodeId: string;
  /** Number uniquely identifying the issue within its repository */
  number: number;
  /** The id of the parent issue to add this issue to as a sub-issue. _NOTE: Only users with triage access to both the parent issue's repository and this repository can set the parent issue._ */
  parentIssueId: number;
  /** URL to get the parent issue of this issue, if it is a sub-issue */
  parentIssueUrl: string;
  /** GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub. */
  performedViaGithubApp: Issue_PerformedViaGithubApp;
  /** Comments provide a way for people to collaborate on an issue. */
  pinnedComment: Issue_PinnedComment;
  pullRequest: Issue_PullRequest;
  reactions: Issue_PinnedComment_Reactions;
  /** A repository on GitHub. */
  repository: Issue_Repository;
  repositoryUrl: string;
  /** State of the issue; either 'open' or 'closed' */
  state: string;
  /** The reason for the current state */
  stateReason: string;
  subIssuesSummary: Issue_SubIssuesSummary;
  timelineUrl: string;
  /** The title of the issue. */
  title: unknown;
  /** The name of the issue type to associate with this issue. _NOTE: Only users with push access can set the type for new issues. The type is silently dropped otherwise._ */
  type: string;
  updatedAt: string;
  /** URL for the issue */
  url: string;
  /** A GitHub user. */
  user: Issue_ClosedBy;
  /** path parameter, not part of the API's own resource representation */
  owner: string;
  /** path parameter, not part of the API's own resource representation */
  repo: string;
  /** path parameter, not part of the API's own resource representation */
  issueNumber: string;
}

export const Issue: ResourceBinding<IssueConfig, IssueAttrs> = {
  wireType: "github_issue",
  fields: {
    assignee: "assignee",
    assignees: "assignees",
    body: "body",
    issueFieldValues: {
      wireName: "issue_field_values",
      kind: "list",
      fields: Issue_IssueFieldValuesFields,
    },
    labels: "labels",
    milestone: "milestone",
    parentIssueId: "parent_issue_id",
    title: "title",
    type: "type",
    owner: "owner",
    repo: "repo",
    issueNumber: "issue_number",
  },
};
