// Code generated by `ubx sdk gen` from github_issue. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Issue_ClosedBy {
  /** The URL of the avatar image for the user who closed the issue. (AI-inferred) */
  avatarUrl: string | Computed<string>;
  /** The email address of the user who closed the issue. This is only present if the user has a public email associated with their GitHub account; otherwise it is null. (AI-inferred) */
  email?: string | Computed<string>;
  /** The URL to fetch the events associated with the user who closed the issue. This is a standard GitHub API user attribute, providing a link to the user's public events. (AI-inferred) */
  eventsUrl: string | Computed<string>;
  /** The URL to the followers list of the user who closed the issue. (AI-inferred) */
  followersUrl: string | Computed<string>;
  /** The URL to retrieve the list of users that this user follows. This is a template URL that can include the placeholder {/other_user} to check if a specific user is followed. (AI-inferred) */
  followingUrl: string | Computed<string>;
  /** The URL to access the gists of the user who closed the issue, via the GitHub API. (AI-inferred) */
  gistsUrl: string | Computed<string>;
  /** The unique Gravatar ID for the user, used to generate avatar image URLs. (AI-inferred) */
  gravatarId: string | Computed<string>;
  /** The HTML URL of the GitHub profile for the user who closed the issue. (AI-inferred) */
  htmlUrl: string | Computed<string>;
  /** The unique numeric identifier of the user who closed the issue. (AI-inferred) */
  id: number | Computed<number>;
  /** The username of the user who closed the issue. (AI-inferred) */
  login: string | Computed<string>;
  /** The display name of the user who closed the issue, as provided by the user's GitHub profile. This field is optional and may be absent if the user has not set a name. (AI-inferred) */
  name?: string | Computed<string>;
  /** The GraphQL node ID of the user who closed the issue. (AI-inferred) */
  nodeId: string | Computed<string>;
  /** The URL to the GitHub API endpoint listing the organizations that this user belongs to. (AI-inferred) */
  organizationsUrl: string | Computed<string>;
  /** The URL to the user's received events feed, for the user who closed the issue. (AI-inferred) */
  receivedEventsUrl: string | Computed<string>;
  /** URL to the GitHub API endpoint listing the repositories owned by the user who closed the issue. (AI-inferred) */
  reposUrl: string | Computed<string>;
  /** Indicates whether the user is a GitHub site administrator. (AI-inferred) */
  siteAdmin: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  /** The URL template for the user's starred repositories, with placeholders for {owner} and {repo} parameters. (AI-inferred) */
  starredUrl: string | Computed<string>;
  /** The URL to view the subscriptions of the user who closed the issue. This field is part of the user object returned in the `closed_by` field of an issue. (AI-inferred) */
  subscriptionsUrl: string | Computed<string>;
  /** The type of GitHub account that closed the issue, such as 'User' or 'Bot'. (AI-inferred) */
  type: string | Computed<string>;
  /** The REST API URL for the user who closed the issue. (AI-inferred) */
  url: string | Computed<string>;
  /** Indicates the user's profile visibility type, either 'public' or 'private'. In the context of the user who closed the issue. (AI-inferred) */
  userViewType?: string | Computed<string>;
}

export interface Issue_IssueDependenciesSummary {
  /** The number of issues that are blocking this issue, i.e., the count of dependencies that must be resolved before this issue can be completed. (AI-inferred) */
  blockedBy: number | Computed<number>;
  /** The number of issues whose implementation is blocked by this issue, based on declared issue dependencies. (AI-inferred) */
  blocking: number | Computed<number>;
  /** The total number of issues that this issue is blocked by. (AI-inferred) */
  totalBlockedBy: number | Computed<number>;
  totalBlocking: number | Computed<number>;
}

export interface Issue_IssueFieldValues {
  /** The unique identifier of the project field that this value is associated with. (AI-inferred) */
  fieldId?: number | Computed<number>;
  /** The value assigned to the custom issue field. The type is dynamic and depends on the custom field's definition (e.g., text, number, date, or selection). (AI-inferred) */
  value?: unknown | Computed<unknown>;
}

export interface Issue_PerformedViaGithubApp_Owner {
  /** The URL of the avatar image for the owner (user or organization) of the GitHub App that performed the action. (AI-inferred) */
  avatarUrl?: string | Computed<string>;
  /** The timestamp (as a string in ISO 8601 format) of when the GitHub App owner account was created. (AI-inferred) */
  createdAt?: string | Computed<string>;
  /** The description of the organization that owns the GitHub App. This field is only populated when the owner is an organization. (AI-inferred) */
  description?: string | Computed<string>;
  email?: string | Computed<string>;
  /** The URL to the events for this GitHub user or organization. (AI-inferred) */
  eventsUrl?: string | Computed<string>;
  /** The URL to the list of followers of the owner (user or organization) of the GitHub App that performed the issue. (AI-inferred) */
  followersUrl?: string | Computed<string>;
  /** The URL template for the list of users this owner is following, with a placeholder for the username (e.g., https://api.github.com/users/{username}/following). (AI-inferred) */
  followingUrl?: string | Computed<string>;
  /** The URL to fetch the owner's public gists, following the standard GitHub API URL format for user gists. (AI-inferred) */
  gistsUrl?: string | Computed<string>;
  /** The Gravatar ID of the GitHub App owner, used to construct the owner's avatar URL from Gravatar. (AI-inferred) */
  gravatarId?: string | Computed<string>;
  /** The URL to the GitHub profile of the app owner. (AI-inferred) */
  htmlUrl?: string | Computed<string>;
  /** The unique numeric identifier of the user or organization that owns the GitHub App. (AI-inferred) */
  id?: number | Computed<number>;
  /** The GitHub username of the owner of the GitHub App that performed the action. (AI-inferred) */
  login?: string | Computed<string>;
  /** The display name of the user or organization that owns the GitHub App. (AI-inferred) */
  name?: string | Computed<string>;
  /** The GraphQL node ID of the user or organization that owns the GitHub App. (AI-inferred) */
  nodeId?: string | Computed<string>;
  /** The URL to retrieve the list of organizations associated with this GitHub App owner, as defined by the GitHub API. (AI-inferred) */
  organizationsUrl?: string | Computed<string>;
  /** The URL to the user's received events endpoint on GitHub, containing the user's incoming events. (AI-inferred) */
  receivedEventsUrl?: string | Computed<string>;
  /** The URL to the list of repositories belonging to this owner (user or organization). (AI-inferred) */
  reposUrl?: string | Computed<string>;
  /** Indicates whether the owner is a site administrator for the GitHub instance (e.g., on GitHub Enterprise). (AI-inferred) */
  siteAdmin?: boolean | Computed<boolean>;
  /** The slug of the owner of the GitHub App that performed the action on the issue. For users and organizations, this is the lowercased, URL-friendly identifier (e.g., 'octocat'). (AI-inferred) */
  slug?: string | Computed<string>;
  starredAt?: string | Computed<string>;
  /** The URL to the list of repositories starred by this owner (user or organization) of the GitHub App. (AI-inferred) */
  starredUrl?: string | Computed<string>;
  /** The API endpoint URL for the owner's subscriptions, indicating resources the owner follows or is subscribed to on GitHub. (AI-inferred) */
  subscriptionsUrl?: string | Computed<string>;
  /** The type of GitHub account that owns the app, either `User` or `Organization`. (AI-inferred) */
  type?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  /** The API URL for the GitHub account (user or organization) that owns the GitHub App. (AI-inferred) */
  url?: string | Computed<string>;
  /** The user's profile view type, either 'public' or 'private'. (AI-inferred) */
  userViewType?: string | Computed<string>;
  /** The website URL of the user or organization that owns the GitHub App which performed the action on the issue. (AI-inferred) */
  websiteUrl?: string | Computed<string>;
}

export interface Issue_PerformedViaGithubApp_Permissions {
  /** The permission level for the Checks API. Set to 'read' or 'write' to grant the GitHub App access. (AI-inferred) */
  checks?: string | Computed<string>;
  /** The permission level granted to the GitHub App for accessing repository contents. (AI-inferred) */
  contents?: string | Computed<string>;
  /** The permission level for deployments granted to the GitHub App. Allowed values are 'read', 'write', or 'none'. (AI-inferred) */
  deployments?: string | Computed<string>;
  /** The permission level for issues granted to the GitHub App that performed the issue. (AI-inferred) */
  issues?: string | Computed<string>;
  /** The permission level for metadata access granted to the GitHub App, typically 'read' or 'write'. (AI-inferred) */
  metadata?: string | Computed<string>;
}

export interface Issue_PerformedViaGithubApp {
  /** The client ID of the GitHub App that performed the action. (AI-inferred) */
  clientId?: string | Computed<string>;
  /** The ISO 8601 timestamp of when the GitHub App was created. (AI-inferred) */
  createdAt: string | Computed<string>;
  /** The description of the GitHub App that performed the action. (AI-inferred) */
  description: string | Computed<string>;
  /** The list of events for the GitHub app. Note that the `installation_target`, `security_advisory`, and `meta` events are not included because they are global events and not specific to an installation. */
  events: string[] | Computed<string[]>;
  /** The URL of the GitHub App's homepage or external reference site. (AI-inferred) */
  externalUrl: string | Computed<string>;
  /** The URL to the GitHub App's public page on GitHub. (AI-inferred) */
  htmlUrl: string | Computed<string>;
  /** Unique identifier of the GitHub app */
  id: number | Computed<number>;
  /** The number of installations associated with the GitHub app. Only returned when the integration is requesting details about itself. */
  installationsCount?: number | Computed<number>;
  /** The name of the GitHub app */
  name: string | Computed<string>;
  /** The GraphQL global node ID for the issue, usable as an identifier in GraphQL queries. (AI-inferred) */
  nodeId: string | Computed<string>;
  /** The user or organization that owns the GitHub app. (AI-inferred) */
  owner: Issue_PerformedViaGithubApp_Owner | Computed<Issue_PerformedViaGithubApp_Owner>;
  /** The set of permissions for the GitHub app */
  permissions: Issue_PerformedViaGithubApp_Permissions | Computed<Issue_PerformedViaGithubApp_Permissions>;
  /** The slug name of the GitHub app */
  slug?: string | Computed<string>;
  /** The timestamp of when the GitHub App was last updated, in ISO 8601 format. (AI-inferred) */
  updatedAt: string | Computed<string>;
}

export interface Issue_PinnedComment_Minimized {
  /** The reason the comment was minimized. */
  reason: string | Computed<string>;
}

export interface Issue_PinnedComment_Pin {
  /** The timestamp indicating when the comment was pinned. (AI-inferred) */
  pinnedAt: string | Computed<string>;
  /** A GitHub user. */
  pinnedBy: Issue_ClosedBy | Computed<Issue_ClosedBy>;
}

export interface Issue_PinnedComment_Reactions {
  /** The number of confused reactions (the 😕 emoji) on the pinned comment. (AI-inferred) */
  confused: number | Computed<number>;
  /** The number of eyes (👀) reactions on this pinned comment. (AI-inferred) */
  eyes: number | Computed<number>;
  /** The number of heart reactions on the pinned comment. (AI-inferred) */
  heart: number | Computed<number>;
  /** The number of hooray reactions on this comment. (AI-inferred) */
  hooray: number | Computed<number>;
  /** The number of 'laugh' reactions (the 😆 emoji) on the pinned comment. (AI-inferred) */
  laugh: number | Computed<number>;
  /** The number of rocket (🚀) reactions on the pinned comment. (AI-inferred) */
  rocket: number | Computed<number>;
  /** The total number of reactions (of all types) on the pinned comment. (AI-inferred) */
  totalCount: number | Computed<number>;
  /** The API URL where this reaction can be accessed. (AI-inferred) */
  url: string | Computed<string>;
}

export interface Issue_PinnedComment {
  /** How the author is associated with the repository. */
  authorAssociation?: string | Computed<string>;
  /** Contents of the issue comment */
  body?: string | Computed<string>;
  /** The HTML-rendered version of the comment's body content. This field is only present if the comment body has been processed by GitHub's markdown renderer. (AI-inferred) */
  bodyHtml?: string | Computed<string>;
  /** The plain-text body of the pinned comment, with any Markdown or HTML formatting removed. (AI-inferred) */
  bodyText?: string | Computed<string>;
  /** The timestamp indicating when the pinned comment was created. (AI-inferred) */
  createdAt: string | Computed<string>;
  /** The URL to view the pinned comment on the GitHub website. (AI-inferred) */
  htmlUrl: string | Computed<string>;
  /** Unique identifier of the issue comment */
  id: number | Computed<number>;
  /** The URL of the issue to which this comment is pinned. (AI-inferred) */
  issueUrl: string | Computed<string>;
  /** Details about why an issue comment was minimized. */
  minimized?: Issue_PinnedComment_Minimized | Computed<Issue_PinnedComment_Minimized>;
  nodeId: string | Computed<string>;
  /** GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub. */
  performedViaGithubApp?: Issue_PerformedViaGithubApp | Computed<Issue_PerformedViaGithubApp>;
  /** Context around who pinned an issue comment and when it was pinned. */
  pin?: Issue_PinnedComment_Pin | Computed<Issue_PinnedComment_Pin>;
  /** The object summarizing reactions to the pinned comment, including total_count and per-type counts for reaction types such as +1, -1, laugh, confused, heart, hooray, rocket, and eyes. (AI-inferred) */
  reactions?: Issue_PinnedComment_Reactions | Computed<Issue_PinnedComment_Reactions>;
  /** The timestamp of when the pinned comment was last updated (in RFC3339 format). (AI-inferred) */
  updatedAt: string | Computed<string>;
  /** URL for the issue comment */
  url: string | Computed<string>;
  /** A GitHub user. */
  user: Issue_ClosedBy | Computed<Issue_ClosedBy>;
}

export interface Issue_PullRequest {
  /** The URL to the diff for this pull request. (AI-inferred) */
  diffUrl: string | Computed<string>;
  /** The URL to view the pull request on GitHub. (AI-inferred) */
  htmlUrl: string | Computed<string>;
  /** The timestamp of when the pull request was merged, if applicable. (AI-inferred) */
  mergedAt?: string | Computed<string>;
  /** The URL to the patch file for this pull request. (AI-inferred) */
  patchUrl: string | Computed<string>;
  /** The URL of the pull request. (AI-inferred) */
  url: string | Computed<string>;
}

export interface Issue_Repository_CodeSearchIndexStatus {
  /** The SHA of the commit that the lexical code search index is based on. (AI-inferred) */
  lexicalCommitSha?: string | Computed<string>;
  /** Indicates whether the repository's lexical search index is currently functional, allowing lexical code search to work. (AI-inferred) */
  lexicalSearchOk?: boolean | Computed<boolean>;
}

export interface Issue_Repository_License {
  /** The URL to the HTML page for this license on GitHub. (AI-inferred) */
  htmlUrl?: string | Computed<string>;
  /** The SPDX license key for the repository's license (e.g., MIT, Apache-2.0, GPL-3.0). (AI-inferred) */
  key: string | Computed<string>;
  /** The full name of the license, such as 'MIT License' or 'Apache License 2.0'. (AI-inferred) */
  name: string | Computed<string>;
  /** The unique identifier for this license in GitHub's GraphQL API. (AI-inferred) */
  nodeId: string | Computed<string>;
  /** The SPDX license identifier for the repository's license, such as 'MIT' or 'Apache-2.0'. (AI-inferred) */
  spdxId: string | Computed<string>;
  /** The API URL for the license information on GitHub. (AI-inferred) */
  url: string | Computed<string>;
}

export interface Issue_Repository_Permissions {
  /** Whether the current user has admin permissions on the repository. (AI-inferred) */
  admin: boolean | Computed<boolean>;
  /** Whether the user has 'maintain' permission for the repository. (AI-inferred) */
  maintain?: boolean | Computed<boolean>;
  /** Whether the authenticated user has permission to pull (clone/fetch) the repository's contents. (AI-inferred) */
  pull: boolean | Computed<boolean>;
  /** Indicates whether the authenticated user has push (write) access to the repository. (AI-inferred) */
  push: boolean | Computed<boolean>;
  /** Indicates whether the user has triage permission on the repository. (AI-inferred) */
  triage?: boolean | Computed<boolean>;
}

export interface Issue_Repository {
  /** Whether to allow Auto-merge to be used on pull requests. */
  allowAutoMerge?: boolean | Computed<boolean>;
  /** Whether to allow forking this repo */
  allowForking?: boolean | Computed<boolean>;
  /** Whether to allow merge commits for pull requests. */
  allowMergeCommit?: boolean | Computed<boolean>;
  /** Whether to allow rebase merges for pull requests. */
  allowRebaseMerge?: boolean | Computed<boolean>;
  /** Whether to allow squash merges for pull requests. */
  allowSquashMerge?: boolean | Computed<boolean>;
  /** Whether or not a pull request head branch that is behind its base branch can always be updated even if it is not required to be up to date before merging. */
  allowUpdateBranch?: boolean | Computed<boolean>;
  /** Whether anonymous git access is enabled for this repository */
  anonymousAccessEnabled?: boolean | Computed<boolean>;
  /** The URL template for downloading the repository's source code archive, with placeholders for archive format and reference (e.g., zipball and ref). (AI-inferred) */
  archiveUrl: string | Computed<string>;
  /** Whether the repository is archived. */
  archived: boolean | Computed<boolean>;
  /** The API URL template for managing repository assignees, with an optional placeholder for a specific assignee. (AI-inferred) */
  assigneesUrl: string | Computed<string>;
  /** The URL template for accessing git blobs in the repository, with a placeholder for the blob SHA (e.g., `http://api.github.com/repos/{owner}/{repo}/git/blobs{/sha}`). (AI-inferred) */
  blobsUrl: string | Computed<string>;
  /** The URL to access the list of branches in this repository. (AI-inferred) */
  branchesUrl: string | Computed<string>;
  /** The URL used to clone the repository, typically in HTTPS or SSH format. (AI-inferred) */
  cloneUrl: string | Computed<string>;
  /** The status of the code search index for this repository */
  codeSearchIndexStatus?: Issue_Repository_CodeSearchIndexStatus | Computed<Issue_Repository_CodeSearchIndexStatus>;
  /** The URL template to access the list of collaborators for the repository. In the GitHub API, this typically takes the form: https://api.github.com/repos/{owner}/{repo}/collaborators{/collaborator}. (AI-inferred) */
  collaboratorsUrl: string | Computed<string>;
  /** The API URL to retrieve the list of comments on this issue. (AI-inferred) */
  commentsUrl: string | Computed<string>;
  /** The URL template for the commits in the repository associated with this issue, often including a placeholder for a commit SHA. (AI-inferred) */
  commitsUrl: string | Computed<string>;
  /** The URL template for comparing commits in the repository, typically in the form of `https://api.github.com/repos/{owner}/{repo}/compare/{base}...{head}`. (AI-inferred) */
  compareUrl: string | Computed<string>;
  /** The API URL template for accessing the contents of the repository, as defined by GitHub's REST API. (AI-inferred) */
  contentsUrl: string | Computed<string>;
  /** The URL to access the list of contributors for this repository via the GitHub API. (AI-inferred) */
  contributorsUrl: string | Computed<string>;
  /** The creation timestamp of the repository. (AI-inferred) */
  createdAt: string | Computed<string>;
  /** The default branch of the repository. */
  defaultBranch: string | Computed<string>;
  /** Whether to delete head branches when pull requests are merged */
  deleteBranchOnMerge?: boolean | Computed<boolean>;
  /** The API endpoint URL for accessing the list of deployments for this repository. (AI-inferred) */
  deploymentsUrl: string | Computed<string>;
  /** The description of the GitHub repository associated with the issue. (AI-inferred) */
  description: string | Computed<string>;
  /** Returns whether or not this repository disabled. */
  disabled: boolean | Computed<boolean>;
  /** The URL to the repository's downloads endpoint, which provides access to the downloads associated with the repository. (AI-inferred) */
  downloadsUrl: string | Computed<string>;
  /** The URL to retrieve events for the repository. (AI-inferred) */
  eventsUrl: string | Computed<string>;
  /** Indicates whether the repository is a fork of another repository. (AI-inferred) */
  fork: boolean | Computed<boolean>;
  /** The number of times this repository has been forked. (AI-inferred) */
  forks: number | Computed<number>;
  /** The total number of times the repository has been forked. (AI-inferred) */
  forksCount: number | Computed<number>;
  /** The URL to list the forks of the repository. (AI-inferred) */
  forksUrl: string | Computed<string>;
  /** The full name of the repository, including the owner and repository name (e.g., 'octocat/hello-world'). (AI-inferred) */
  fullName: string | Computed<string>;
  /** URL template for the git commits of the repository, with a placeholder for the commit SHA, e.g., `https://api.github.com/repos/{owner}/{repo}/git/commits{/sha}`. (AI-inferred) */
  gitCommitsUrl: string | Computed<string>;
  /** The URL to access the git references (e.g., branches and tags) for the repository. This URL can be used to list or retrieve refs via the GitHub API. (AI-inferred) */
  gitRefsUrl: string | Computed<string>;
  /** The API endpoint URL for accessing the repository's git tags. (AI-inferred) */
  gitTagsUrl: string | Computed<string>;
  /** The URL to the Git repository associated with the GitHub repository, typically in the format git://github.com/owner/repository.git, used for cloning and remote operations. (AI-inferred) */
  gitUrl: string | Computed<string>;
  /** Whether discussions are enabled. */
  hasDiscussions?: boolean | Computed<boolean>;
  /** Whether downloads are enabled. */
  hasDownloads: boolean | Computed<boolean>;
  /** Whether issues are enabled. */
  hasIssues: boolean | Computed<boolean>;
  /** Whether the repository has GitHub Pages enabled. (AI-inferred) */
  hasPages: boolean | Computed<boolean>;
  /** Whether projects are enabled. */
  hasProjects: boolean | Computed<boolean>;
  /** Whether pull requests are enabled. */
  hasPullRequests?: boolean | Computed<boolean>;
  /** Whether the wiki is enabled. */
  hasWiki: boolean | Computed<boolean>;
  /** The URL of the repository's homepage. (AI-inferred) */
  homepage: string | Computed<string>;
  /** The URL to the repository's webhooks API endpoint, used to manage hooks for the repository. (AI-inferred) */
  hooksUrl: string | Computed<string>;
  /** The URL of the repository on GitHub. (AI-inferred) */
  htmlUrl: string | Computed<string>;
  /** Unique identifier of the repository */
  id: number | Computed<number>;
  /** Whether this repository acts as a template that can be used to generate new repositories. */
  isTemplate?: boolean | Computed<boolean>;
  /** The URL to the issue comments endpoint for this repository. (AI-inferred) */
  issueCommentUrl: string | Computed<string>;
  /** The API URL template for accessing issue events in this repository, typically containing placeholders for event numbers. (AI-inferred) */
  issueEventsUrl: string | Computed<string>;
  /** The API URL to the repository's issues endpoint, which may include a placeholder for a specific issue number. (AI-inferred) */
  issuesUrl: string | Computed<string>;
  /** The URL endpoint for the repository's deploy keys, with an optional template placeholder for a specific key ID. (AI-inferred) */
  keysUrl: string | Computed<string>;
  /** The API endpoint URL for accessing the labels of the repository, possibly containing a templated placeholder (e.g., '/labels{/name}') for a specific label name. (AI-inferred) */
  labelsUrl: string | Computed<string>;
  /** The primary programming language of the repository. (AI-inferred) */
  language: string | Computed<string>;
  /** The URL to retrieve the list of programming languages used in the repository. (AI-inferred) */
  languagesUrl: string | Computed<string>;
  /** License Simple */
  license: Issue_Repository_License | Computed<Issue_Repository_License>;
  /** The name of the repository's master branch. (AI-inferred) */
  masterBranch?: string | Computed<string>;
  /** The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. - `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message. */
  mergeCommitMessage?: string | Computed<string>;
  /** The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. - `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name). */
  mergeCommitTitle?: string | Computed<string>;
  /** The URL template for the merge endpoint, used to merge branches in this repository via the GitHub API. (AI-inferred) */
  mergesUrl: string | Computed<string>;
  /** The URL template for accessing milestones in the repository, with a placeholder for the specific milestone number (e.g., `.../milestones{/number}`). (AI-inferred) */
  milestonesUrl: string | Computed<string>;
  /** The URL of the original repository if this repository is a mirror of another source. This is typically set for repositories that are mirrored from an external Git repository. (AI-inferred) */
  mirrorUrl: string | Computed<string>;
  /** The name of the repository. */
  name: string | Computed<string>;
  /** The unique global node identifier (GraphQL ID) for the repository associated with the issue. (AI-inferred) */
  nodeId: string | Computed<string>;
  /** The URL to access notifications for this repository. (AI-inferred) */
  notificationsUrl: string | Computed<string>;
  /** The number of open issues currently in the repository. (AI-inferred) */
  openIssues: number | Computed<number>;
  /** The number of open issues in the repository. (AI-inferred) */
  openIssuesCount: number | Computed<number>;
  /** A GitHub user. */
  owner: Issue_ClosedBy | Computed<Issue_ClosedBy>;
  /** An object indicating the permission levels the authenticated user has on this repository, typically including flags such as admin, push, and pull. (AI-inferred) */
  permissions?: Issue_Repository_Permissions | Computed<Issue_Repository_Permissions>;
  /** Whether the repository is private or public. */
  private: boolean | Computed<boolean>;
  /** The policy controlling who can create pull requests: all or collaborators_only. */
  pullRequestCreationPolicy?: string | Computed<string>;
  /** The API endpoint URL for pull requests in this repository, with a template placeholder for the pull request number. (AI-inferred) */
  pullsUrl: string | Computed<string>;
  /** The timestamp of the last push to the repository, in ISO 8601 format (e.g., '2023-01-01T12:00:00Z'). (AI-inferred) */
  pushedAt: string | Computed<string>;
  /** The URL to the releases page of the repository. (AI-inferred) */
  releasesUrl: string | Computed<string>;
  /** The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0. */
  size: number | Computed<number>;
  /** The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. - `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message. */
  squashMergeCommitMessage?: string | Computed<string>;
  /** The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. - `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit). */
  squashMergeCommitTitle?: string | Computed<string>;
  /** The SSH URL for accessing the repository over SSH, used for Git operations. (AI-inferred) */
  sshUrl: string | Computed<string>;
  /** The total number of users who have starred the repository. (AI-inferred) */
  stargazersCount: number | Computed<number>;
  /** The URL to the GitHub API endpoint that lists the users who have starred (stargazers) this repository. (AI-inferred) */
  stargazersUrl: string | Computed<string>;
  /** The ISO 8601 timestamp of when the repository was starred by the authenticated user. (AI-inferred) */
  starredAt?: string | Computed<string>;
  /** URL template to access commit statuses for the repository; replace {sha} with a commit SHA to list statuses for that commit. (AI-inferred) */
  statusesUrl: string | Computed<string>;
  /** The URL to retrieve the list of users subscribed to the repository. (AI-inferred) */
  subscribersUrl: string | Computed<string>;
  /** The API endpoint URL to manage the authenticated user's subscription to this repository's notifications. (AI-inferred) */
  subscriptionUrl: string | Computed<string>;
  /** The URL to access this repository via Subversion (SVN). (AI-inferred) */
  svnUrl: string | Computed<string>;
  /** The API URL to list the tags of the repository. (AI-inferred) */
  tagsUrl: string | Computed<string>;
  /** The URL to the teams endpoint for this repository. (AI-inferred) */
  teamsUrl: string | Computed<string>;
  /** A temporary clone token that allows cloning the repository without authentication for a limited time. It is typically provided only for private repositories and expires after a short period. (AI-inferred) */
  tempCloneToken?: string | Computed<string>;
  /** List of topics (tags) associated with the repository that contains the issue. (AI-inferred) */
  topics?: string[] | Computed<string[]>;
  /** URL template for accessing the repository's git trees. Replace the `{sha}` placeholder with a commit SHA to retrieve a specific tree. (AI-inferred) */
  treesUrl: string | Computed<string>;
  /** The timestamp of the last update to the repository, in ISO 8601 format. (AI-inferred) */
  updatedAt: string | Computed<string>;
  /** The URL of the repository. (AI-inferred) */
  url: string | Computed<string>;
  /** Whether a squash merge commit can use the pull request title as default. **This property is closing down. Please use `squash_merge_commit_title` instead. */
  useSquashPrTitleAsDefault?: boolean | Computed<boolean>;
  /** The repository visibility: public, private, or internal. */
  visibility?: string | Computed<string>;
  /** The number of users watching (subscribed to) the repository. (AI-inferred) */
  watchers: number | Computed<number>;
  /** The number of users watching the repository. (AI-inferred) */
  watchersCount: number | Computed<number>;
  /** Whether to require contributors to sign off on web-based commits */
  webCommitSignoffRequired?: boolean | Computed<boolean>;
}

export interface Issue_SubIssuesSummary {
  /** The number of sub-issues that have been completed, as tracked in the sub-issues summary for this GitHub issue. (AI-inferred) */
  completed: number | Computed<number>;
  /** The overall completion percentage of the sub-issues in this summary, as a number between 0 and 100. (AI-inferred) */
  percentCompleted: number | Computed<number>;
  /** The total number of sub-issues associated with this issue, as reported in the sub-issues summary. (AI-inferred) */
  total: number | Computed<number>;
}

const Issue_IssueFieldValuesFields: FieldMap = {
  fieldId: "field_id",
  value: "value",
};

export interface IssueConfig {
  /** Login for the user that this issue should be assigned to. _NOTE: Only users with push access can set the assignee for new issues. The assignee is silently dropped otherwise. **This field is closing down.**_ */
  assignee?: string | Computed<string>;
  /** Logins for Users to assign to this issue. _NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise._ */
  assignees?: string[] | Computed<string[]>;
  /** The contents of the issue. */
  body?: string | Computed<string>;
  /** An array of issue field values to set on this issue. Each field value must include the field ID and the value to set. Issue fields are only available for organization-owned repositories with the feature enabled. Field values are silently dropped otherwise. */
  issueFieldValues?: Issue_IssueFieldValues[] | Computed<Issue_IssueFieldValues[]>;
  /** Labels to associate with this issue. _NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise._ */
  labels?: unknown[] | Computed<unknown[]>;
  /** The milestone associated with the issue, if any. This field is computed and read-only; it cannot be set from the client. (AI-inferred) */
  milestone?: unknown | Computed<unknown>;
  /** The title of the issue. */
  title: unknown | Computed<unknown>;
  /** The name of the issue type to associate with this issue. _NOTE: Only users with push access can set the type for new issues. The type is silently dropped otherwise._ */
  type?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  owner: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  repo: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  issueNumber: string | Computed<string>;
}

export interface IssueAttrs {
  /** The reason the issue is locked, if applicable. Possible values are `off-topic`, `too heated`, `resolved`, and `spam`. (AI-inferred) */
  activeLockReason: string;
  /** Login for the user that this issue should be assigned to. _NOTE: Only users with push access can set the assignee for new issues. The assignee is silently dropped otherwise. **This field is closing down.**_ */
  assignee: string;
  /** Logins for Users to assign to this issue. _NOTE: Only users with push access can set assignees for new issues. Assignees are silently dropped otherwise._ */
  assignees: string[];
  /** How the author is associated with the repository. */
  authorAssociation: string;
  /** The contents of the issue. */
  body: string;
  /** The HTML-rendered version of the issue body. (AI-inferred) */
  bodyHtml: string;
  /** The plain-text version of the issue body, with Markdown removed. (AI-inferred) */
  bodyText: string;
  /** The timestamp when the issue was closed, in RFC3339 format (e.g., 2023-01-01T00:00:00Z). (AI-inferred) */
  closedAt: string;
  /** A GitHub user. */
  closedBy: Issue_ClosedBy;
  /** The number of comments on the GitHub issue. This value is computed and provided by GitHub. (AI-inferred) */
  comments: number;
  /** The API endpoint URL that returns the comments for this issue. (AI-inferred) */
  commentsUrl: string;
  /** The creation timestamp of the GitHub issue, set by the provider and returned as a string in ISO 8601 format (e.g., 2023-01-01T12:00:00Z). (AI-inferred) */
  createdAt: string;
  /** A boolean indicating whether the issue is a draft. Draft issues are hidden from non-collaborators and are not ready for review. (AI-inferred) */
  draft: boolean;
  /** The URL to retrieve the events associated with this issue, such as labeling, closing, or reopening. (AI-inferred) */
  eventsUrl: string;
  /** The URL to view the issue on GitHub's website. (AI-inferred) */
  htmlUrl: string;
  id: number;
  issueDependenciesSummary: Issue_IssueDependenciesSummary;
  /** An array of issue field values to set on this issue. Each field value must include the field ID and the value to set. Issue fields are only available for organization-owned repositories with the feature enabled. Field values are silently dropped otherwise. */
  issueFieldValues: Issue_IssueFieldValues[];
  /** Labels to associate with this issue. _NOTE: Only users with push access can set labels for new issues. Labels are silently dropped otherwise._ */
  labels: unknown[];
  /** The API endpoint URL for querying the labels of this issue. (AI-inferred) */
  labelsUrl: string;
  /** Indicates whether the issue is locked for comments, meaning only users with write access can comment. (AI-inferred) */
  locked: boolean;
  /** The milestone associated with the issue, if any. This field is computed and read-only; it cannot be set from the client. (AI-inferred) */
  milestone: unknown;
  /** The Node ID of the issue, used by GitHub's GraphQL API. (AI-inferred) */
  nodeId: string;
  /** Number uniquely identifying the issue within its repository */
  number: number;
  /** URL to get the parent issue of this issue, if it is a sub-issue */
  parentIssueUrl: string;
  /** GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub. */
  performedViaGithubApp: Issue_PerformedViaGithubApp;
  /** Comments provide a way for people to collaborate on an issue. */
  pinnedComment: Issue_PinnedComment;
  /** The pull_request object is present when the issue is also a pull request, and contains metadata about the pull request such as its URL and merge status. (AI-inferred) */
  pullRequest: Issue_PullRequest;
  /** The reactions summary for the issue, containing counts of user reactions by type (e.g., thumbs up, thumbs down, laugh, hooray, confused, heart, rocket, eyes). (AI-inferred) */
  reactions: Issue_PinnedComment_Reactions;
  /** A repository on GitHub. */
  repository: Issue_Repository;
  /** The URL of the repository in which the issue is located. (AI-inferred) */
  repositoryUrl: string;
  /** State of the issue; either 'open' or 'closed' */
  state: string;
  /** The reason for the current state */
  stateReason: string;
  subIssuesSummary: Issue_SubIssuesSummary;
  /** The URL to retrieve the timeline of events for this issue via the GitHub API. (AI-inferred) */
  timelineUrl: string;
  /** The title of the issue. */
  title: unknown;
  /** The name of the issue type to associate with this issue. _NOTE: Only users with push access can set the type for new issues. The type is silently dropped otherwise._ */
  type: string;
  /** The timestamp when the issue was last updated, in ISO 8601 format (e.g., 2023-01-15T10:30:00Z). This field is computed and read-only. (AI-inferred) */
  updatedAt: string;
  /** URL for the issue */
  url: string;
  /** A GitHub user. */
  user: Issue_ClosedBy;
  /** path parameter, not part of the API's own resource representation */
  owner: string;
  /** path parameter, not part of the API's own resource representation */
  repo: string;
  /** path parameter, not part of the API's own resource representation */
  issueNumber: string;
}

export const Issue: ResourceBinding<IssueConfig, IssueAttrs> = {
  wireType: "github_issue",
  fields: {
    assignee: "assignee",
    assignees: "assignees",
    body: "body",
    issueFieldValues: {
      wireName: "issue_field_values",
      kind: "list",
      fields: Issue_IssueFieldValuesFields,
    },
    labels: "labels",
    milestone: "milestone",
    title: "title",
    type: "type",
    owner: "owner",
    repo: "repo",
    issueNumber: "issue_number",
  },
};
