// Code generated by `ubx sdk gen` from github_runner_label_list. DO NOT EDIT.
package runner

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LabelList_Labels struct {
	Id any
	Name any
	Type any
}

type LabelListConfig struct {
	Enterprise any
	RunnerId any
}

type LabelListAttrs struct {
	Busy any
	Enterprise any
	Ephemeral any
	// The ID of the runner.
	Id any
	Labels any
	// The name of the runner.
	Name any
	// The Operating System of the runner.
	Os any
	// The ID of the runner group.
	RunnerGroupId any
	RunnerId any
	// The status of the runner.
	Status any
	// The version of the GitHub Actions Runner software. This is only set if the runner has connected to the service at least once.
	Version any
}

var LabelList = ubx.DataSourceBinding{
	WireType: "github_runner_label_list",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
		"RunnerId": ubx.FieldSpec{WireName: "runner_id"},
	},
}
