# Code generated by `ubx sdk gen` from github_runner_groups_org. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class GroupsOrgConfig:
    # Whether the runner group can be used by `public` repositories.
    allows_public_repositories: Any = None
    # Name of the runner group.
    name: Any = None
    # The identifier of a hosted compute network configuration.
    network_configuration_id: Any = None
    # If `true`, the runner group will be restricted to running only the workflows specified in the `selected_workflows` array.
    restricted_to_workflows: Any = None
    # List of runner IDs to add to the runner group.
    runners: Any = None
    # List of repository IDs that can access the runner group.
    selected_repository_ids: Any = None
    # List of workflows the runner group should be allowed to run. This setting will be ignored unless `restricted_to_workflows` is set to `true`.
    selected_workflows: Any = None
    # Visibility of a runner group. You can select all repositories, select individual repositories, or limit access to private repositories.
    visibility: Any = None
    # path parameter, not part of the API's own resource representation
    org: Any = None
    # path parameter, not part of the API's own resource representation
    runner_group_id: Any = None

@dataclasses.dataclass
class GroupsOrgAttrs:
    # Whether the runner group can be used by `public` repositories.
    allows_public_repositories: Any = None
    default: Any = None
    hosted_runners_url: Any = None
    id: Any = None
    inherited: Any = None
    inherited_allows_public_repositories: Any = None
    # Name of the runner group.
    name: Any = None
    # The identifier of a hosted compute network configuration.
    network_configuration_id: Any = None
    # If `true`, the runner group will be restricted to running only the workflows specified in the `selected_workflows` array.
    restricted_to_workflows: Any = None
    # List of runner IDs to add to the runner group.
    runners: Any = None
    runners_url: Any = None
    # Link to the selected repositories resource for this runner group. Not present unless visibility was set to `selected`
    selected_repositories_url: Any = None
    # List of repository IDs that can access the runner group.
    selected_repository_ids: Any = None
    # List of workflows the runner group should be allowed to run. This setting will be ignored unless `restricted_to_workflows` is set to `true`.
    selected_workflows: Any = None
    # Visibility of a runner group. You can select all repositories, select individual repositories, or limit access to private repositories.
    visibility: Any = None
    # If `true`, the `restricted_to_workflows` and `selected_workflows` fields cannot be modified.
    workflow_restrictions_read_only: Any = None
    # path parameter, not part of the API's own resource representation
    org: Any = None
    # path parameter, not part of the API's own resource representation
    runner_group_id: Any = None

GroupsOrg = ubx.ResourceBinding(
    wire_type="github_runner_groups_org",
    fields={
        "allows_public_repositories": ubx.FieldSpec(wire_name="allows_public_repositories"),
        "name": ubx.FieldSpec(wire_name="name"),
        "network_configuration_id": ubx.FieldSpec(wire_name="network_configuration_id"),
        "restricted_to_workflows": ubx.FieldSpec(wire_name="restricted_to_workflows"),
        "runners": ubx.FieldSpec(wire_name="runners"),
        "selected_repository_ids": ubx.FieldSpec(wire_name="selected_repository_ids"),
        "selected_workflows": ubx.FieldSpec(wire_name="selected_workflows"),
        "visibility": ubx.FieldSpec(wire_name="visibility"),
        "org": ubx.FieldSpec(wire_name="org"),
        "runner_group_id": ubx.FieldSpec(wire_name="runner_group_id"),
    },
)
