# Code generated by `ubx sdk gen` from github_gitignore_template. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class TemplateConfig:
    name: Any = None

@dataclasses.dataclass
class TemplateAttrs:
    name: Any = None
    source: Any = None

Template = ubx.DataSourceBinding(
    wire_type="github_gitignore_template",
    fields={
        "name": ubx.FieldSpec(wire_name="name"),
    },
)
