# Code generated by `ubx sdk gen` from github_visual_studio_subscription_assignment. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class StudioSubscriptionAssignment_VisualStudioSubscriptions:
    manual_match: Any = None
    subscription_id: Any = None
    username: Any = None
    visual_studio_subscription_email: Any = None

@dataclasses.dataclass
class StudioSubscriptionAssignmentConfig:
    enterprise: Any = None
    is_unmatched_only: Any = None
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class StudioSubscriptionAssignmentAttrs:
    enterprise: Any = None
    is_unmatched_only: Any = None
    page: Any = None
    per_page: Any = None
    total_count: Any = None
    visual_studio_subscriptions: Any = None

StudioSubscriptionAssignment = ubx.DataSourceBinding(
    wire_type="github_visual_studio_subscription_assignment",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
        "is_unmatched_only": ubx.FieldSpec(wire_name="is_unmatched_only"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
