// Code generated by `ubx sdk gen` from github_job. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Job_Deployments {
  deploymentName?: string | Computed<string>;
  digest?: string | Computed<string>;
  githubRepository?: string | Computed<string>;
  name?: string | Computed<string>;
  runtimeRisks?: string[] | Computed<string[]>;
  status?: string | Computed<string>;
  tags?: Record<string, string> | Computed<Record<string, string>>;
  version?: string | Computed<string>;
}

const Job_DeploymentsFields: FieldMap = {
  deploymentName: "deployment_name",
  digest: "digest",
  githubRepository: "github_repository",
  name: "name",
  runtimeRisks: "runtime_risks",
  status: "status",
  tags: "tags",
  version: "version",
};

export interface JobConfig {
  /** The list of deployments to record. */
  deployments: Job_Deployments[] | Computed<Job_Deployments[]>;
  /** The stage of the deployment. */
  logicalEnvironment: string | Computed<string>;
  /** The physical region of the deployment. */
  physicalEnvironment?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  org: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  cluster: string | Computed<string>;
}

export interface JobAttrs {
  /** The list of deployments to record. */
  deployments: Job_Deployments[];
  /** Processing errors (only present when completed or failed). */
  errors: unknown[];
  /** The ID of the job. */
  jobId: number;
  /** The stage of the deployment. */
  logicalEnvironment: string;
  /** The physical region of the deployment. */
  physicalEnvironment: string;
  /** When the job started processing (only present when processing, completed, or failed). */
  startedAt: string;
  /** The current status of the job. */
  status: string;
  /** The number of records successfully mutated (only present when completed). */
  totalCount: number;
  /** path parameter, not part of the API's own resource representation */
  org: string;
  /** path parameter, not part of the API's own resource representation */
  cluster: string;
}

export const Job: ResourceBinding<JobConfig, JobAttrs> = {
  wireType: "github_job",
  fields: {
    deployments: {
      wireName: "deployments",
      kind: "list",
      fields: Job_DeploymentsFields,
    },
    logicalEnvironment: "logical_environment",
    physicalEnvironment: "physical_environment",
    org: "org",
    cluster: "cluster",
  },
};
