// Code generated by `ubx sdk gen` from github_user. DO NOT EDIT.
package user

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type UserConfig struct {
	Page any
	PerPage any
}

type UserAttrs struct {
	Page any
	PerPage any
}

var User = ubx.DataSourceBinding{
	WireType: "github_user",
	Fields: ubx.FieldMap{
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
