// Code generated by `ubx sdk gen` from github_network. DO NOT EDIT.
package network

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type NetworkConfig struct {
	Owner any
	Page any
	PerPage any
	Repo any
}

type NetworkAttrs struct {
	Owner any
	Page any
	PerPage any
	Repo any
}

var Network = ubx.DataSourceBinding{
	WireType: "github_network",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
	},
}
