# Code generated by `ubx sdk gen` from github_subscription. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SubscriptionConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class SubscriptionAttrs:
    page: Any = None
    per_page: Any = None

Subscription = ubx.DataSourceBinding(
    wire_type="github_subscription",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
