// Code generated by `ubx sdk gen` from github_actions_cache_usage_org_enterprise. DO NOT EDIT.
package actions

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CacheUsageOrgEnterpriseConfig struct {
	Enterprise any
}

type CacheUsageOrgEnterpriseAttrs struct {
	Enterprise any
	// The count of active caches across all repositories of an enterprise or an organization.
	TotalActiveCachesCount any
	// The total size in bytes of all active cache items across all repositories of an enterprise or an organization.
	TotalActiveCachesSizeInBytes any
}

var CacheUsageOrgEnterprise = ubx.DataSourceBinding{
	WireType: "github_actions_cache_usage_org_enterprise",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
	},
}
