// Code generated by `ubx sdk gen` from github_actions_cache_storage_limit_for_enterprise. DO NOT EDIT.
package actions

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type CacheStorageLimitForEnterpriseConfig struct {
	Enterprise any
}

type CacheStorageLimitForEnterpriseAttrs struct {
	Enterprise any
	// For repositories & organizations in an enterprise, the maximum size limit for the sum of all caches in a repository, in gigabytes.
	MaxCacheSizeGb any
}

var CacheStorageLimitForEnterprise = ubx.DataSourceBinding{
	WireType: "github_actions_cache_storage_limit_for_enterprise",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
	},
}
