// Code generated by `ubx sdk gen` from github_actions_hosted_runner_custom_image_version_list. DO NOT EDIT.
package actions

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type HostedRunnerCustomImageVersionList_ImageVersions struct {
	CreatedOn any
	SizeGb any
	State any
	StateDetails any
	Version any
}

type HostedRunnerCustomImageVersionListConfig struct {
	Enterprise any
	ImageDefinitionId any
}

type HostedRunnerCustomImageVersionListAttrs struct {
	Enterprise any
	ImageDefinitionId any
	ImageVersions any
	TotalCount any
}

var HostedRunnerCustomImageVersionList = ubx.DataSourceBinding{
	WireType: "github_actions_hosted_runner_custom_image_version_list",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
		"ImageDefinitionId": ubx.FieldSpec{WireName: "image_definition_id"},
	},
}
