// Code generated by `ubx sdk gen` from github_actions_secret. DO NOT EDIT.
package actions

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type SecretConfig struct {
	Owner any
	Repo any
	SecretName any
}

type SecretAttrs struct {
	CreatedAt any
	// The name of the secret.
	Name any
	Owner any
	Repo any
	SecretName any
	UpdatedAt any
}

var Secret = ubx.DataSourceBinding{
	WireType: "github_actions_secret",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
		"SecretName": ubx.FieldSpec{WireName: "secret_name"},
	},
}
