# Code generated by `ubx sdk gen` from github_organization_fine_grained_permission. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FineGrainedPermissionConfig:
    org: Any = None

@dataclasses.dataclass
class FineGrainedPermissionAttrs:
    org: Any = None

FineGrainedPermission = ubx.DataSourceBinding(
    wire_type="github_organization_fine_grained_permission",
    fields={
        "org": ubx.FieldSpec(wire_name="org"),
    },
)
