// Code generated by `ubx sdk gen` from github_task. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Task_Tasks_Artifacts_Data {
  baseRef?: string | Computed<string>;
  globalId?: string | Computed<string>;
  headRef?: string | Computed<string>;
  id?: number | Computed<number>;
}

export interface Task_Tasks_Artifacts {
  data?: Task_Tasks_Artifacts_Data | Computed<Task_Tasks_Artifacts_Data>;
  provider?: string | Computed<string>;
  type?: string | Computed<string>;
}

export interface Task_Tasks_Creator {
  id?: number | Computed<number>;
}

export interface Task_Tasks_CustomAgent {
  id?: string | Computed<string>;
}

export interface Task_Tasks {
  archivedAt?: string | Computed<string>;
  artifacts?: Task_Tasks_Artifacts[] | Computed<Task_Tasks_Artifacts[]>;
  createdAt?: string | Computed<string>;
  creator?: Task_Tasks_Creator | Computed<Task_Tasks_Creator>;
  creatorType?: string | Computed<string>;
  customAgent?: Task_Tasks_CustomAgent | Computed<Task_Tasks_CustomAgent>;
  htmlUrl?: string | Computed<string>;
  id?: string | Computed<string>;
  name?: string | Computed<string>;
  owner?: Task_Tasks_Creator | Computed<Task_Tasks_Creator>;
  repository?: Task_Tasks_Creator | Computed<Task_Tasks_Creator>;
  sessionCount?: number | Computed<number>;
  state?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  userCollaborators?: Task_Tasks_Creator[] | Computed<Task_Tasks_Creator[]>;
}

export interface TaskConfig {
  creatorId?: number[] | Computed<number[]>;
  direction?: string | Computed<string>;
  isArchived?: boolean | Computed<boolean>;
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  repo: string | Computed<string>;
  since?: string | Computed<string>;
  sort?: string | Computed<string>;
  state?: string | Computed<string>;
}

export interface TaskAttrs {
  creatorId: number[];
  direction: string;
  isArchived: boolean;
  owner: string;
  page: number;
  perPage: number;
  repo: string;
  since: string;
  sort: string;
  state: string;
  /** List of tasks */
  tasks: Task_Tasks[];
  /** Total count of active (non-archived) tasks */
  totalActiveCount: number;
  /** Total count of archived tasks */
  totalArchivedCount: number;
}

export const Task: DataSourceBinding<TaskConfig, TaskAttrs> = {
  wireType: "github_task",
  fields: {
    creatorId: "creator_id",
    direction: "direction",
    isArchived: "is_archived",
    owner: "owner",
    page: "page",
    perPage: "per_page",
    repo: "repo",
    since: "since",
    sort: "sort",
    state: "state",
  },
};
