// Code generated by `ubx sdk gen` from github_api_insights_user_stats. DO NOT EDIT.
package api

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type InsightsUserStatsConfig struct {
	ActorNameSubstring any
	Direction          any
	MaxTimestamp       any
	MinTimestamp       any
	Org                any
	Page               any
	PerPage            any
	Sort               any
	UserId             any
}

type InsightsUserStatsAttrs struct {
	ActorNameSubstring any
	Direction          any
	MaxTimestamp       any
	MinTimestamp       any
	Org                any
	Page               any
	PerPage            any
	Sort               any
	UserId             any
}

var InsightsUserStats = ubx.DataSourceBinding{
	WireType: "github_api_insights_user_stats",
	Fields: ubx.FieldMap{
		"ActorNameSubstring": ubx.FieldSpec{WireName: "actor_name_substring"},
		"Direction":          ubx.FieldSpec{WireName: "direction"},
		"MaxTimestamp":       ubx.FieldSpec{WireName: "max_timestamp"},
		"MinTimestamp":       ubx.FieldSpec{WireName: "min_timestamp"},
		"Org":                ubx.FieldSpec{WireName: "org"},
		"Page":               ubx.FieldSpec{WireName: "page"},
		"PerPage":            ubx.FieldSpec{WireName: "per_page"},
		"Sort":               ubx.FieldSpec{WireName: "sort"},
		"UserId":             ubx.FieldSpec{WireName: "user_id"},
	},
}
