# Code generated by `ubx sdk gen` from github_agent. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Agent_Tasks_Artifacts_Data:
    base_ref: Any = None
    global_id: Any = None
    head_ref: Any = None
    id: Any = None

@dataclasses.dataclass
class Agent_Tasks_Artifacts:
    data: Any = None
    provider: Any = None
    type: Any = None

@dataclasses.dataclass
class Agent_Tasks_Creator:
    id: Any = None

@dataclasses.dataclass
class Agent_Tasks_CustomAgent:
    id: Any = None

@dataclasses.dataclass
class Agent_Tasks:
    archived_at: Any = None
    artifacts: Any = None
    created_at: Any = None
    creator: Any = None
    creator_type: Any = None
    custom_agent: Any = None
    html_url: Any = None
    id: Any = None
    name: Any = None
    owner: Any = None
    repository: Any = None
    session_count: Any = None
    state: Any = None
    updated_at: Any = None
    url: Any = None
    user_collaborators: Any = None

@dataclasses.dataclass
class AgentConfig:
    direction: Any = None
    is_archived: Any = None
    page: Any = None
    per_page: Any = None
    since: Any = None
    sort: Any = None
    state: Any = None

@dataclasses.dataclass
class AgentAttrs:
    direction: Any = None
    is_archived: Any = None
    page: Any = None
    per_page: Any = None
    since: Any = None
    sort: Any = None
    state: Any = None
    # List of tasks
    tasks: Any = None
    # Total count of active (non-archived) tasks
    total_active_count: Any = None
    # Total count of archived tasks
    total_archived_count: Any = None

Agent = ubx.DataSourceBinding(
    wire_type="github_agent",
    fields={
        "direction": ubx.FieldSpec(wire_name="direction"),
        "is_archived": ubx.FieldSpec(wire_name="is_archived"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "since": ubx.FieldSpec(wire_name="since"),
        "sort": ubx.FieldSpec(wire_name="sort"),
        "state": ubx.FieldSpec(wire_name="state"),
    },
)
