// Code generated by `ubx sdk gen` from github_codespaces_secret. DO NOT EDIT.
package codespaces

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Secret_Secrets struct {
	CreatedAt               any
	Name                    any
	SelectedRepositoriesUrl any
	UpdatedAt               any
	Visibility              any
}

type SecretConfig struct {
	Page    any
	PerPage any
}

type SecretAttrs struct {
	Page       any
	PerPage    any
	Secrets    any
	TotalCount any
}

var Secret = ubx.DataSourceBinding{
	WireType: "github_codespaces_secret",
	Fields: ubx.FieldMap{
		"Page":    ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
