// Code generated by `ubx sdk gen` from github_codespaces_user_public_key. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface UserPublicKeyConfig {
}

export interface UserPublicKeyAttrs {
  /** The Base64 encoded public key. */
  key: string;
  /** The identifier for the key. */
  keyId: string;
}

export const UserPublicKey: DataSourceBinding<UserPublicKeyConfig, UserPublicKeyAttrs> = {
  wireType: "github_codespaces_user_public_key",
  fields: {
  },
};
