# Code generated by `ubx sdk gen` from github_ssh_signing_key. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SigningKeyConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class SigningKeyAttrs:
    page: Any = None
    per_page: Any = None

SigningKey = ubx.DataSourceBinding(
    wire_type="github_ssh_signing_key",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
