// Code generated by `ubx sdk gen` from github_deployment_protection_rule_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ProtectionRuleList_CustomDeploymentProtectionRules_App {
  id?: number | Computed<number>;
  integrationUrl?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  slug?: string | Computed<string>;
}

export interface ProtectionRuleList_CustomDeploymentProtectionRules {
  app?: ProtectionRuleList_CustomDeploymentProtectionRules_App | Computed<ProtectionRuleList_CustomDeploymentProtectionRules_App>;
  enabled?: boolean | Computed<boolean>;
  id?: number | Computed<number>;
  nodeId?: string | Computed<string>;
}

export interface ProtectionRuleListConfig {
  environmentName: string | Computed<string>;
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface ProtectionRuleListAttrs {
  customDeploymentProtectionRules: ProtectionRuleList_CustomDeploymentProtectionRules[];
  environmentName: string;
  owner: string;
  repo: string;
  /** The number of enabled custom deployment protection rules for this environment */
  totalCount: number;
}

export const ProtectionRuleList: DataSourceBinding<ProtectionRuleListConfig, ProtectionRuleListAttrs> = {
  wireType: "github_deployment_protection_rule_list",
  fields: {
    environmentName: "environment_name",
    owner: "owner",
    repo: "repo",
  },
};
