# Code generated by `ubx sdk gen` from github_deprecation. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class DeprecationConfig:
    enterprise: Any = None
    version: Any = None

@dataclasses.dataclass
class DeprecationAttrs:
    enterprise: Any = None
    # The date after which this runner version can no longer register. Null if no schedule is set.
    registration_deprecates_at: Any = None
    # The runner version string.
    runner_version: Any = None
    # The date after which jobs will no longer be dispatched to runners on this version.
    runtime_deprecates_at: Any = None
    version: Any = None

Deprecation = ubx.DataSourceBinding(
    wire_type="github_deprecation",
    fields={
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
        "version": ubx.FieldSpec(wire_name="version"),
    },
)
