// Code generated by `ubx sdk gen` from github_billing_premium_request_usage_report_ghe. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface PremiumRequestUsageReportGhe_CostCenter {
  /** The unique identifier of the cost center. */
  id: string | Computed<string>;
  /** The name of the cost center. */
  name: string | Computed<string>;
}

export interface PremiumRequestUsageReportGhe_TimePeriod {
  /** The day for the usage report. */
  day?: number | Computed<number>;
  /** The month for the usage report. */
  month?: number | Computed<number>;
  /** The year for the usage report. */
  year: number | Computed<number>;
}

export interface PremiumRequestUsageReportGhe_UsageItems {
  discountAmount?: number | Computed<number>;
  discountQuantity?: number | Computed<number>;
  grossAmount?: number | Computed<number>;
  grossQuantity?: number | Computed<number>;
  model?: string | Computed<string>;
  netAmount?: number | Computed<number>;
  netQuantity?: number | Computed<number>;
  pricePerUnit?: number | Computed<number>;
  product?: string | Computed<string>;
  sku?: string | Computed<string>;
  unitType?: string | Computed<string>;
}

export interface PremiumRequestUsageReportGheConfig {
  costCenterId?: string | Computed<string>;
  day?: number | Computed<number>;
  enterprise: string | Computed<string>;
  model?: string | Computed<string>;
  month?: number | Computed<number>;
  organization?: string | Computed<string>;
  product?: string | Computed<string>;
  user?: string | Computed<string>;
  year?: number | Computed<number>;
}

export interface PremiumRequestUsageReportGheAttrs {
  costCenter: PremiumRequestUsageReportGhe_CostCenter;
  costCenterId: string;
  day: number;
  enterprise: string;
  model: string;
  month: number;
  organization: string;
  product: string;
  timePeriod: PremiumRequestUsageReportGhe_TimePeriod;
  usageItems: PremiumRequestUsageReportGhe_UsageItems[];
  user: string;
  year: number;
}

export const PremiumRequestUsageReportGhe: DataSourceBinding<PremiumRequestUsageReportGheConfig, PremiumRequestUsageReportGheAttrs> = {
  wireType: "github_billing_premium_request_usage_report_ghe",
  fields: {
    costCenterId: "cost_center_id",
    day: "day",
    enterprise: "enterprise",
    model: "model",
    month: "month",
    organization: "organization",
    product: "product",
    user: "user",
    year: "year",
  },
};
