// Code generated by `ubx sdk gen` from github_billing_usage_report. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface UsageReport_UsageItems {
  date?: string | Computed<string>;
  discountAmount?: number | Computed<number>;
  grossAmount?: number | Computed<number>;
  netAmount?: number | Computed<number>;
  organizationName?: string | Computed<string>;
  pricePerUnit?: number | Computed<number>;
  product?: string | Computed<string>;
  quantity?: number | Computed<number>;
  repositoryName?: string | Computed<string>;
  sku?: string | Computed<string>;
  unitType?: string | Computed<string>;
}

export interface UsageReportConfig {
  costCenterId?: string | Computed<string>;
  day?: number | Computed<number>;
  enterprise: string | Computed<string>;
  month?: number | Computed<number>;
  year?: number | Computed<number>;
}

export interface UsageReportAttrs {
  costCenterId: string;
  day: number;
  enterprise: string;
  month: number;
  usageItems: UsageReport_UsageItems[];
  year: number;
}

export const UsageReport: DataSourceBinding<UsageReportConfig, UsageReportAttrs> = {
  wireType: "github_billing_usage_report",
  fields: {
    costCenterId: "cost_center_id",
    day: "day",
    enterprise: "enterprise",
    month: "month",
    year: "year",
  },
};
