// Code generated by `ubx sdk gen` from github_oidc_custom_sub. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CustomSubConfig {
  org: string | Computed<string>;
}

export interface CustomSubAttrs {
  /** Array of unique strings. Each claim key can only contain alphanumeric characters and underscores. */
  includeClaimKeys: string[];
  org: string;
  /** Whether to opt in to the immutable OIDC subject claim format for the organization. When `true`, new OIDC tokens will use a stable, repository-ID-based `sub` claim instead of the name-based format. */
  useImmutableSubject: boolean;
}

export const CustomSub: DataSourceBinding<CustomSubConfig, CustomSubAttrs> = {
  wireType: "github_oidc_custom_sub",
  fields: {
    org: "org",
  },
};
