// Code generated by `ubx sdk gen` from github_bypass_response. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Response_Data {
  ruleType?: string | Computed<string>;
  rulesetId?: number | Computed<number>;
  rulesetName?: string | Computed<string>;
  totalViolations?: number | Computed<number>;
}

export interface Response_Organization {
  /** The ID of the organization. */
  id?: number | Computed<number>;
  /** The name of the organization. */
  name?: string | Computed<string>;
}

export interface Response_Repository {
  /** The full name of the repository the bypass request is for. */
  fullName?: string | Computed<string>;
  /** The ID of the repository the bypass request is for. */
  id?: number | Computed<number>;
  /** The name of the repository the bypass request is for. */
  name?: string | Computed<string>;
}

export interface Response_Requester {
  /** The ID of the GitHub user who requested the bypass. */
  actorId?: number | Computed<number>;
  /** The name of the GitHub user who requested the bypass. */
  actorName?: string | Computed<string>;
}

export interface Response_Responses {
  createdAt?: string | Computed<string>;
  id?: number | Computed<number>;
  reviewer?: Response_Requester | Computed<Response_Requester>;
  status?: string | Computed<string>;
}

export interface ResponseConfig {
  bypassRequestNumber: number | Computed<number>;
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface ResponseAttrs {
  bypassRequestNumber: number;
  /** The date and time the bypass request was created. */
  createdAt: string;
  /** Data describing the push rules that are being requested to be bypassed. */
  data: Response_Data[];
  /** The date and time the bypass request will expire. */
  expiresAt: string;
  /** The URL to view the bypass request in a browser. */
  htmlUrl: string;
  /** The unique identifier of the bypass request. */
  id: number;
  /** The number uniquely identifying the bypass request within its repository. */
  number: number;
  /** The organization associated with the repository the bypass request is for. */
  organization: Response_Organization;
  owner: string;
  repo: string;
  /** The repository the bypass request is for. */
  repository: Response_Repository;
  /** The type of request. */
  requestType: string;
  /** The user who requested the bypass. */
  requester: Response_Requester;
  /** The comment the requester provided when creating the bypass request. */
  requesterComment: string;
  /** The unique identifier for the request type of the bypass request. For example, a commit SHA. */
  resourceIdentifier: string;
  /** The responses to the bypass request. */
  responses: Response_Responses[];
  /** The status of the bypass request. */
  status: string;
  url: string;
}

export const Response: DataSourceBinding<ResponseConfig, ResponseAttrs> = {
  wireType: "github_bypass_response",
  fields: {
    bypassRequestNumber: "bypass_request_number",
    owner: "owner",
    repo: "repo",
  },
};
