// Code generated by `ubx sdk gen` from github_gpg_key. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface KeyConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface KeyAttrs {
  page: number;
  perPage: number;
}

export const Key: DataSourceBinding<KeyConfig, KeyAttrs> = {
  wireType: "github_gpg_key",
  fields: {
    page: "page",
    perPage: "per_page",
  },
};
