// Code generated by `ubx sdk gen` from github_repository_ruleset. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Ruleset_Links_Html {
  /** The html URL of the ruleset */
  href?: string | Computed<string>;
}

export interface Ruleset_Links {
  html?: Ruleset_Links_Html | Computed<Ruleset_Links_Html>;
  self?: Ruleset_Links_Html | Computed<Ruleset_Links_Html>;
}

export interface Ruleset_BypassActors {
  actorId?: number | Computed<number>;
  actorType?: string | Computed<string>;
  bypassMode?: string | Computed<string>;
}

export interface Ruleset_Conditions {
}

export interface Ruleset_Rules_Parameters {
  updateAllowsFetchAndMerge?: boolean | Computed<boolean>;
}

export interface Ruleset_Rules {
  parameters?: Ruleset_Rules_Parameters | Computed<Ruleset_Rules_Parameters>;
  type?: string | Computed<string>;
}

const Ruleset_BypassActorsFields: FieldMap = {
  actorId: "actor_id",
  actorType: "actor_type",
  bypassMode: "bypass_mode",
};

const Ruleset_ConditionsFields: FieldMap = {
};

const Ruleset_Rules_ParametersFields: FieldMap = {
  updateAllowsFetchAndMerge: "update_allows_fetch_and_merge",
};

const Ruleset_RulesFields: FieldMap = {
  parameters: {
    wireName: "parameters",
    kind: "object",
    fields: Ruleset_Rules_ParametersFields,
  },
  type: "type",
};

export interface RulesetConfig {
  /** The actors that can bypass the rules in this ruleset */
  bypassActors?: Ruleset_BypassActors[] | Computed<Ruleset_BypassActors[]>;
  /** Conditions for an enterprise ruleset. The `conditions` object supports either of the following combinations: - `organization_id` and `repository_name` - `organization_id` and `repository_property` - `organization_name` and `repository_name` - `organization_name` and `repository_property` - `organization_property` and `repository_name` - `organization_property` and `repository_property` For branch and tag rulesets, the `conditions` object should also contain the `ref_name` property. */
  conditions?: Ruleset_Conditions | Computed<Ruleset_Conditions>;
  /** The enforcement level of the ruleset. `evaluate` allows admins to test rules before enforcing them. Admins can view insights on the Rule Insights page. `evaluate` is not available for the `repository` target. */
  enforcement: string | Computed<string>;
  /** The name of the ruleset. */
  name: string | Computed<string>;
  /** An array of rules within the ruleset. */
  rules?: Ruleset_Rules[] | Computed<Ruleset_Rules[]>;
  /** The target of the ruleset */
  target?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  enterprise: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  rulesetId: string | Computed<string>;
}

export interface RulesetAttrs {
  links: Ruleset_Links;
  /** The actors that can bypass the rules in this ruleset */
  bypassActors: Ruleset_BypassActors[];
  /** Conditions for an enterprise ruleset. The `conditions` object supports either of the following combinations: - `organization_id` and `repository_name` - `organization_id` and `repository_property` - `organization_name` and `repository_name` - `organization_name` and `repository_property` - `organization_property` and `repository_name` - `organization_property` and `repository_property` For branch and tag rulesets, the `conditions` object should also contain the `ref_name` property. */
  conditions: Ruleset_Conditions;
  createdAt: string;
  /** The bypass type of the user making the API request for this ruleset. This field is only returned when querying the repository-level endpoint. */
  currentUserCanBypass: string;
  /** The enforcement level of the ruleset. `evaluate` allows admins to test rules before enforcing them. Admins can view insights on the Rule Insights page. `evaluate` is not available for the `repository` target. */
  enforcement: string;
  /** The ID of the ruleset */
  id: number;
  /** The name of the ruleset. */
  name: string;
  nodeId: string;
  /** An array of rules within the ruleset. */
  rules: Ruleset_Rules[];
  /** The name of the source */
  source: string;
  /** The type of the source of the ruleset */
  sourceType: string;
  /** The target of the ruleset */
  target: string;
  updatedAt: string;
  /** path parameter, not part of the API's own resource representation */
  enterprise: string;
  /** path parameter, not part of the API's own resource representation */
  rulesetId: string;
}

export const Ruleset: ResourceBinding<RulesetConfig, RulesetAttrs> = {
  wireType: "github_repository_ruleset",
  fields: {
    bypassActors: {
      wireName: "bypass_actors",
      kind: "list",
      fields: Ruleset_BypassActorsFields,
    },
    conditions: {
      wireName: "conditions",
      kind: "object",
      fields: Ruleset_ConditionsFields,
    },
    enforcement: "enforcement",
    name: "name",
    rules: {
      wireName: "rules",
      kind: "list",
      fields: Ruleset_RulesFields,
    },
    target: "target",
    enterprise: "enterprise",
    rulesetId: "ruleset_id",
  },
};
