# Code generated by `ubx sdk gen` from github_git_tag. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Tag_Tagger:
    # When this object was tagged. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
    date: Any = None
    # The email of the author of the tag
    email: Any = None
    # The name of the author of the tag
    name: Any = None

@dataclasses.dataclass
class Tag_Verification:
    payload: Any = None
    reason: Any = None
    signature: Any = None
    verified: Any = None
    verified_at: Any = None

_Tag_TaggerFields = {
    "date": ubx.FieldSpec(wire_name="date"),
    "email": ubx.FieldSpec(wire_name="email"),
    "name": ubx.FieldSpec(wire_name="name"),
}

@dataclasses.dataclass
class TagConfig:
    # The tag message.
    message: Any = None
    # The SHA of the git object this is tagging.
    object: Any = None
    # The tag's name. This is typically a version (e.g., "v0.0.1").
    tag: Any = None
    # An object with information about the individual creating the tag.
    tagger: Any = None
    # The type of the object we're tagging. Normally this is a `commit` but it can also be a `tree` or a `blob`.
    type: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    tag_sha: Any = None

@dataclasses.dataclass
class TagAttrs:
    # The tag message.
    message: Any = None
    node_id: Any = None
    # The SHA of the git object this is tagging.
    object: Any = None
    sha: Any = None
    # The tag's name. This is typically a version (e.g., "v0.0.1").
    tag: Any = None
    # An object with information about the individual creating the tag.
    tagger: Any = None
    # The type of the object we're tagging. Normally this is a `commit` but it can also be a `tree` or a `blob`.
    type: Any = None
    # URL for the tag
    url: Any = None
    verification: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    tag_sha: Any = None

Tag = ubx.ResourceBinding(
    wire_type="github_git_tag",
    fields={
        "message": ubx.FieldSpec(wire_name="message"),
        "object": ubx.FieldSpec(wire_name="object"),
        "tag": ubx.FieldSpec(wire_name="tag"),
        "tagger": ubx.FieldSpec(
            wire_name="tagger",
            kind="object",
            fields=_Tag_TaggerFields,
        ),
        "type": ubx.FieldSpec(wire_name="type"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
        "tag_sha": ubx.FieldSpec(wire_name="tag_sha"),
    },
)
