// Code generated by `ubx sdk gen` from github_view_traffic. DO NOT EDIT.
package view

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Traffic_Views struct {
	Count any
	Timestamp any
	Uniques any
}

type TrafficConfig struct {
	Owner any
	Per any
	Repo any
}

type TrafficAttrs struct {
	Count any
	Owner any
	Per any
	Repo any
	Uniques any
	Views any
}

var Traffic = ubx.DataSourceBinding{
	WireType: "github_view_traffic",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Per": ubx.FieldSpec{WireName: "per"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
	},
}
