// Code generated by `ubx sdk gen` from github_rate_limit_overview. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface LimitOverview_Rate {
  limit: number | Computed<number>;
  remaining: number | Computed<number>;
  reset: number | Computed<number>;
  used: number | Computed<number>;
}

export interface LimitOverview_Resources {
  actionsRunnerRegistration?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  codeScanningAutofix?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  codeSearch?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  copilotUsageRecords?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  core: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  dependencySbom?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  dependencySnapshots?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  graphql?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  integrationManifest?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  scim?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  search: LimitOverview_Rate | Computed<LimitOverview_Rate>;
  sourceImport?: LimitOverview_Rate | Computed<LimitOverview_Rate>;
}

export interface LimitOverviewConfig {
}

export interface LimitOverviewAttrs {
  rate: LimitOverview_Rate;
  resources: LimitOverview_Resources;
}

export const LimitOverview: DataSourceBinding<LimitOverviewConfig, LimitOverviewAttrs> = {
  wireType: "github_rate_limit_overview",
  fields: {
  },
};
