// Code generated by `ubx sdk gen` from github_version. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface VersionConfig {
  org: string | Computed<string>;
  packageName: string | Computed<string>;
  packageType: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  state?: string | Computed<string>;
}

export interface VersionAttrs {
  org: string;
  packageName: string;
  packageType: string;
  page: number;
  perPage: number;
  state: string;
}

export const Version: DataSourceBinding<VersionConfig, VersionAttrs> = {
  wireType: "github_version",
  fields: {
    org: "org",
    packageName: "package_name",
    packageType: "package_type",
    page: "page",
    perPage: "per_page",
    state: "state",
  },
};
