// Code generated by `ubx sdk gen` from github_billing_usage_summary_report_ghe. DO NOT EDIT.
package billing

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type UsageSummaryReportGhe_CostCenter struct {
	// The unique identifier of the cost center.
	Id any
	// The name of the cost center.
	Name any
}

type UsageSummaryReportGhe_TimePeriod struct {
	// The day for the usage report.
	Day any
	// The month for the usage report.
	Month any
	// The year for the usage report.
	Year any
}

type UsageSummaryReportGhe_UsageItems struct {
	DiscountAmount any
	DiscountQuantity any
	GrossAmount any
	GrossQuantity any
	NetAmount any
	NetQuantity any
	PricePerUnit any
	Product any
	Sku any
	UnitType any
}

type UsageSummaryReportGheConfig struct {
	CostCenterId any
	Day any
	Enterprise any
	Month any
	Organization any
	Product any
	Repository any
	Sku any
	Year any
}

type UsageSummaryReportGheAttrs struct {
	CostCenter any
	CostCenterId any
	Day any
	Enterprise any
	Month any
	Organization any
	Product any
	Repository any
	Sku any
	TimePeriod any
	UsageItems any
	Year any
}

var UsageSummaryReportGhe = ubx.DataSourceBinding{
	WireType: "github_billing_usage_summary_report_ghe",
	Fields: ubx.FieldMap{
		"CostCenterId": ubx.FieldSpec{WireName: "cost_center_id"},
		"Day": ubx.FieldSpec{WireName: "day"},
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
		"Month": ubx.FieldSpec{WireName: "month"},
		"Organization": ubx.FieldSpec{WireName: "organization"},
		"Product": ubx.FieldSpec{WireName: "product"},
		"Repository": ubx.FieldSpec{WireName: "repository"},
		"Sku": ubx.FieldSpec{WireName: "sku"},
		"Year": ubx.FieldSpec{WireName: "year"},
	},
}
