# Code generated by `ubx sdk gen` from github@dynamic. DO NOT EDIT.
# This file is committed to git like any other reviewable generated code
# (docs/sdk.md — "ubx sdk gen: local, pinned, offline-after-generation") --
# re-run `ubx sdk gen` to regenerate after a provider version bump.
SOURCE_PROVENANCE = {"source": "github", "version": "dynamic"}

from .dependabot import Dependabot, DependabotConfig
from .alert import Alert, AlertConfig
from .public_key import PublicKey, PublicKeyConfig
from .repository_access_details import RepositoryAccessDetails, RepositoryAccessDetailsConfig
from .secret import Secret, SecretConfig
