// Code generated by `ubx sdk gen` from github_membership. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface MembershipConfig {
  enterprise: string | Computed<string>;
  enterpriseTeam: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface MembershipAttrs {
  enterprise: string;
  enterpriseTeam: string;
  page: number;
  perPage: number;
}

export const Membership: DataSourceBinding<MembershipConfig, MembershipAttrs> = {
  wireType: "github_membership",
  fields: {
    enterprise: "enterprise",
    enterpriseTeam: "enterprise_team",
    page: "page",
    perPage: "per_page",
  },
};
