// Code generated by `ubx sdk gen` from github_full_repository. DO NOT EDIT.
package full

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Repository_CodeOfConduct struct {
	// The URL to the HTML page for this code of conduct. (AI-inferred)
	HtmlUrl any
	// A short identifier for the code of conduct, such as 'contributor_covenant'. (AI-inferred)
	Key any
	// The name of the code of conduct, such as 'Contributor Covenant'. (AI-inferred)
	Name any
	// The API URL for this code of conduct. (AI-inferred)
	Url any
}

type Repository_License struct {
	// The URL to view the license on GitHub, if a license is present. (AI-inferred)
	HtmlUrl any
	// The SPDX license key, e.g., 'mit' or 'apache-2.0'. (AI-inferred)
	Key any
	// The name of the license for the repository, such as 'MIT License'. (AI-inferred)
	Name any
	// The unique node identifier for the license, used by GitHub's GraphQL API. (AI-inferred)
	NodeId any
	// The SPDX license identifier for the repository's license (e.g., 'MIT' or 'Apache-2.0'), used to identify the license in a machine-readable format. (AI-inferred)
	SpdxId any
	// The URL to the license resource on the GitHub API, where detailed information about the license can be retrieved. (AI-inferred)
	Url any
}

type Repository_Organization struct {
	// The URL of the organization's avatar image. (AI-inferred)
	AvatarUrl any
	// The organization's contact email address, if provided. (AI-inferred)
	Email any
	// The URL endpoint for retrieving events associated with this organization. (AI-inferred)
	EventsUrl any
	// The URL to retrieve the followers of this organization. (AI-inferred)
	FollowersUrl any
	// The URL to the GitHub API endpoint that lists the accounts this organization follows. (AI-inferred)
	FollowingUrl any
	// The URL to the organization's gists on GitHub. (AI-inferred)
	GistsUrl any
	// The Gravatar ID for the organization. May be an empty string if no Gravatar is associated. (AI-inferred)
	GravatarId any
	// The URL to the organization's GitHub web page. (AI-inferred)
	HtmlUrl any
	Id any
	// The unique GitHub username (login) for the organization. (AI-inferred)
	Login any
	// The name of the organization that owns the repository. (AI-inferred)
	Name any
	// The GraphQL node ID for the organization, used for identifying the organization in GitHub's GraphQL API. (AI-inferred)
	NodeId any
	OrganizationsUrl any
	// The API URL that lists events received by the organization. This points to the organization's received events endpoint in the GitHub API. (AI-inferred)
	ReceivedEventsUrl any
	// The URL to the organization's repositories endpoint in the GitHub API, typically used to fetch the list of repositories belonging to the organization. (AI-inferred)
	ReposUrl any
	// Whether this organization account has site administrator privileges on GitHub. (AI-inferred)
	SiteAdmin any
	StarredAt any
	StarredUrl any
	// The API endpoint that returns the subscriptions for the organization. (AI-inferred)
	SubscriptionsUrl any
	// The type of account; for an organization, this is always 'Organization'. (AI-inferred)
	Type any
	// The URL of the organization. (AI-inferred)
	Url any
	UserViewType any
}

type Repository_Parent_CodeSearchIndexStatus struct {
	// The commit SHA that the lexical code search index is currently synchronized to. (AI-inferred)
	LexicalCommitSha any
	// A boolean flag indicating whether lexical search is functioning correctly within the code search index status. (AI-inferred)
	LexicalSearchOk any
}

type Repository_Parent_Permissions struct {
	// Whether the current user has administrative permissions on the repository. (AI-inferred)
	Admin any
	// Whether the current user has maintain permission on this repository. (AI-inferred)
	Maintain any
	// Whether the user has permission to pull (read) from the parent repository. (AI-inferred)
	Pull any
	// Whether the authenticated user has push access to the repository. (AI-inferred)
	Push any
	// Whether the user has triage permission on the repository, allowing them to manage issues and pull requests without having write access to the code. (AI-inferred)
	Triage any
}

type Repository_Parent struct {
	// Whether to allow Auto-merge to be used on pull requests.
	AllowAutoMerge any
	// Whether to allow forking this repo
	AllowForking any
	// Whether to allow merge commits for pull requests.
	AllowMergeCommit any
	// Whether to allow rebase merges for pull requests.
	AllowRebaseMerge any
	// Whether to allow squash merges for pull requests.
	AllowSquashMerge any
	// Whether or not a pull request head branch that is behind its base branch can always be updated even if it is not required to be up to date before merging.
	AllowUpdateBranch any
	// Whether anonymous git access is enabled for this repository
	AnonymousAccessEnabled any
	// The template URL for downloading an archive (tarball or zipball) of the repository. It contains placeholders for the archive format and reference, e.g., 'https://api.github.com/repos/{owner}/{repo}/{archive_format}{/ref}'. (AI-inferred)
	ArchiveUrl any
	// Whether the repository is archived.
	Archived any
	// The API URL template for the repository's assignees endpoint, used to list or manage assignees for issues in the repository. (AI-inferred)
	AssigneesUrl any
	// URL template for the repository's git blobs, with a placeholder for the blob SHA. (AI-inferred)
	BlobsUrl any
	// The URL to access the branches of the parent repository. (AI-inferred)
	BranchesUrl any
	// The HTTPS URL to clone the parent repository, typically in the format https://github.com/{owner}/{repo}.git (AI-inferred)
	CloneUrl any
	// The status of the code search index for this repository
	CodeSearchIndexStatus any
	// The URL to the API endpoint for managing collaborators of the parent repository. (AI-inferred)
	CollaboratorsUrl any
	// The URL template for the comments on commits in this repository. (AI-inferred)
	CommentsUrl any
	// URL endpoint to retrieve a list of commits for the repository (or its parent, if this is a fork). (AI-inferred)
	CommitsUrl any
	// The URL template for comparing commits or references in the parent repository. (AI-inferred)
	CompareUrl any
	// The API URL to access the repository's contents, with a {+path} placeholder for the file or directory path. (AI-inferred)
	ContentsUrl any
	// URL to the API endpoint that lists contributors of the parent repository. (AI-inferred)
	ContributorsUrl any
	// The timestamp indicating when the parent repository was created. (AI-inferred)
	CreatedAt any
	// The default branch of the repository.
	DefaultBranch any
	// Whether to delete head branches when pull requests are merged
	DeleteBranchOnMerge any
	// The URL template to access the deployments of the repository, typically in the form `https://api.github.com/repos/{owner}/{repo}/deployments{/id}`. This field is always present in the repository object. (AI-inferred)
	DeploymentsUrl any
	// The description of the parent repository, as set by its owner. This is the same description that appears on the parent repository's main page. (AI-inferred)
	Description any
	// Returns whether or not this repository disabled.
	Disabled any
	// The URL of the downloads endpoint for the parent repository. This is a GitHub API endpoint to interact with the repository's download functionality. (AI-inferred)
	DownloadsUrl any
	// The URL to retrieve the events for the parent repository, typically in the context of a forked repository. (AI-inferred)
	EventsUrl any
	// A boolean value indicating whether the repository is a fork of another repository. (AI-inferred)
	Fork any
	// The number of forks of the parent repository. (AI-inferred)
	Forks any
	// The number of times this repository has been forked. Always present in the parent repository object. (AI-inferred)
	ForksCount any
	// The API endpoint URL for listing the forks of the parent repository. (AI-inferred)
	ForksUrl any
	// The full name of the repository, including the owner and repository name, formatted as 'owner/repo' (e.g., 'octocat/Hello-World'). (AI-inferred)
	FullName any
	// The URL for the git commits of the parent repository. (AI-inferred)
	GitCommitsUrl any
	// URL template for accessing git references (e.g., branches, tags) in the repository. The template includes a placeholder for a specific ref SHA (typically `{/sha}`), allowing clients to construct URLs for individual references. (AI-inferred)
	GitRefsUrl any
	// The URL to the git tags for the parent repository. (AI-inferred)
	GitTagsUrl any
	// The git URL of the parent repository, used for cloning via the git protocol. (AI-inferred)
	GitUrl any
	// Whether discussions are enabled.
	HasDiscussions any
	// Whether downloads are enabled.
	HasDownloads any
	// Whether issues are enabled.
	HasIssues any
	// Indicates whether GitHub Pages is enabled for this repository. (AI-inferred)
	HasPages any
	// Whether projects are enabled.
	HasProjects any
	// Whether pull requests are enabled.
	HasPullRequests any
	// Whether the wiki is enabled.
	HasWiki any
	// The URL of the repository's homepage, or null if none is set. (AI-inferred)
	Homepage any
	// The API endpoint URL for managing webhooks on the parent repository. (AI-inferred)
	HooksUrl any
	// The URL to view the parent repository in a web browser. (AI-inferred)
	HtmlUrl any
	// Unique identifier of the repository
	Id any
	// Whether this repository acts as a template that can be used to generate new repositories.
	IsTemplate any
	// The URL template for accessing issue comments in the parent repository, typically following the pattern of an API endpoint with a placeholder for the comment number. (AI-inferred)
	IssueCommentUrl any
	// The API URL template for issue events in the repository, e.g., https://api.github.com/repos/{owner}/{repo}/issues/events{/number}. (AI-inferred)
	IssueEventsUrl any
	// The URL to access the issues for this repository. (AI-inferred)
	IssuesUrl any
	// URL to retrieve the deploy keys for this repository. (AI-inferred)
	KeysUrl any
	// API endpoint URL template for the repository's labels, typically including a `{/name}` placeholder for a specific label. (AI-inferred)
	LabelsUrl any
	// The primary programming language of the repository, as detected by GitHub. (AI-inferred)
	Language any
	// URL to the languages endpoint for this repository, which returns the programming languages used and their byte counts. (AI-inferred)
	LanguagesUrl any
	// License Simple
	License any
	// The name of the master branch of the parent repository. (AI-inferred)
	MasterBranch any
	// The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. - `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message.
	MergeCommitMessage any
	// The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. - `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name).
	MergeCommitTitle any
	// The URL to the merges endpoint for the parent repository. (AI-inferred)
	MergesUrl any
	// The URL template for accessing milestones in this repository, with an optional placeholder for a specific milestone number. (AI-inferred)
	MilestonesUrl any
	// The URL of the mirror repository, if the parent repository is a mirror; otherwise null. (AI-inferred)
	MirrorUrl any
	// The name of the repository.
	Name any
	// The unique GraphQL node identifier for the repository, used to reference it in the GitHub GraphQL API. This field is always present. (AI-inferred)
	NodeId any
	// The API URL for notifications related to the parent repository in the context of a fork. (AI-inferred)
	NotificationsUrl any
	// The number of open issues in the repository. (AI-inferred)
	OpenIssues any
	// The number of open issues in the parent repository. (AI-inferred)
	OpenIssuesCount any
	// A GitHub user.
	Owner any
	// An object representing the permissions the authenticated user has on the repository, indicating the access level granted. (AI-inferred)
	Permissions any
	// Whether the repository is private or public.
	Private any
	// The policy controlling who can create pull requests: all or collaborators_only.
	PullRequestCreationPolicy any
	// The URL template for accessing pull requests in the repository. It includes a placeholder for a specific pull request number (e.g., {/number}) and is required in the GitHub full repository resource. (AI-inferred)
	PullsUrl any
	// The timestamp of the last push to the parent repository. (AI-inferred)
	PushedAt any
	// API URL for the releases of this repository. This is a template URL with a placeholder for the release ID, e.g., https://api.github.com/repos/{owner}/{repo}/releases{/id}. (AI-inferred)
	ReleasesUrl any
	// The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0.
	Size any
	// The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. - `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message.
	SquashMergeCommitMessage any
	// The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. - `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit).
	SquashMergeCommitTitle any
	// The SSH URL of the parent repository, used for cloning and remote access via SSH (e.g., git@github.com:owner/repo.git). (AI-inferred)
	SshUrl any
	// The number of users who have starred the repository. In a fork's parent object, this is the parent repository's stargazers count. (AI-inferred)
	StargazersCount any
	// The URL to access the list of users who have starred the parent repository. (AI-inferred)
	StargazersUrl any
	StarredAt any
	// The URL template for accessing commit statuses associated with the repository, with `{sha}` as the commit SHA placeholder. (AI-inferred)
	StatusesUrl any
	// The API URL for listing subscribers (watchers) of the parent repository. This is part of the GitHub Repository object and follows the standard GitHub API URL format. (AI-inferred)
	SubscribersUrl any
	// The API URL for subscribing to the parent repository's notifications. (AI-inferred)
	SubscriptionUrl any
	// The URL to access the repository via SVN. (AI-inferred)
	SvnUrl any
	// The URL to the repository's tags endpoint, which lists the tags associated with the repository. (AI-inferred)
	TagsUrl any
	// The URL to access the teams associated with the parent repository. (AI-inferred)
	TeamsUrl any
	TempCloneToken any
	// The list of topics associated with the parent repository. (AI-inferred)
	Topics any
	// The URL template for accessing the Git trees of this repository. Append a commit SHA to retrieve the tree for that specific commit, as defined in the GitHub API. (AI-inferred)
	TreesUrl any
	// The timestamp of the last update to the parent repository, in ISO 8601 format. (AI-inferred)
	UpdatedAt any
	// The GitHub API URL of the parent repository (the repository from which this one was forked). (AI-inferred)
	Url any
	// Whether a squash merge commit can use the pull request title as default. **This property is closing down. Please use `squash_merge_commit_title` instead.
	UseSquashPrTitleAsDefault any
	// The repository visibility: public, private, or internal.
	Visibility any
	// Number of users who have subscribed to watch the repository. (AI-inferred)
	Watchers any
	// The number of users who have starred (watched) the parent repository, typically equal to stargazers_count. (AI-inferred)
	WatchersCount any
	// Whether to require contributors to sign off on web-based commits
	WebCommitSignoffRequired any
}

type Repository_SecurityAndAnalysis_AdvancedSecurity struct {
	// Whether advanced security is enabled or disabled for the repository. Allowed values: enabled, disabled. (AI-inferred)
	Status any
}

type Repository_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions_Reviewers struct {
	// The role of the reviewer in the delegated bypass workflow. ALWAYS means the reviewer is always required to approve requests to bypass secret scanning protection, while EXEMPT means the reviewer is exempt from the normal review process and can bypass without approval. (AI-inferred)
	Mode any
	// The numeric ID of the GitHub user or team that is assigned as a reviewer for delegated secret scanning bypass requests. (AI-inferred)
	ReviewerId any
	// The type of reviewer for secret scanning delegated bypass: either TEAM (a GitHub team) or ROLE (a repository role). (AI-inferred)
	ReviewerType any
}

type Repository_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions struct {
	// The bypass reviewers for secret scanning delegated bypass
	Reviewers any
}

type Repository_SecurityAndAnalysis struct {
	// Enable or disable GitHub Advanced Security for the repository. For standalone Code Scanning or Secret Protection products, this parameter cannot be used.
	AdvancedSecurity any
	CodeSecurity any
	// Enable or disable Dependabot security updates for the repository.
	DependabotSecurityUpdates any
	// The secret scanning configuration and status for the repository, which detects known types of secrets accidentally committed to the repository. (AI-inferred)
	SecretScanning any
	// The secret scanning AI detection settings, including its status (e.g., 'enabled' or 'disabled'). (AI-inferred)
	SecretScanningAiDetection any
	// Configuration for delegated alert dismissal in secret scanning, allowing a designated group of reviewers to dismiss secret scanning alerts. (AI-inferred)
	SecretScanningDelegatedAlertDismissal any
	// Configures delegated bypass for secret scanning, enabling certain users to bypass push protection when secrets are detected. (AI-inferred)
	SecretScanningDelegatedBypass any
	// Settings for delegating bypass of secret scanning push protection. Use this to specify which actors can bypass secret scanning alerts and optionally require reviews for bypasses. (AI-inferred)
	SecretScanningDelegatedBypassOptions any
	SecretScanningNonProviderPatterns any
	// Configuration for secret scanning push protection, which blocks pushes that contain detected secrets from being successfully pushed to the repository. (AI-inferred)
	SecretScanningPushProtection any
	SecretScanningValidityChecks any
}

type RepositoryConfig struct {
	// Whether to allow Auto-merge to be used on pull requests.
	AllowAutoMerge any
	// Whether to allow merge commits for pull requests.
	AllowMergeCommit any
	// Whether to allow rebase merges for pull requests.
	AllowRebaseMerge any
	// Whether to allow squash merges for pull requests.
	AllowSquashMerge any
	// Whether the repository is initialized with a minimal README.
	AutoInit any
	// Whether to delete head branches when pull requests are merged
	DeleteBranchOnMerge any
	// A short description of the repository.
	Description any
	// The desired language or platform to apply to the .gitignore.
	GitignoreTemplate any
	// Whether discussions are enabled.
	HasDiscussions any
	// Whether downloads are enabled.
	HasDownloads any
	// Whether issues are enabled.
	HasIssues any
	// Whether projects are enabled.
	HasProjects any
	// Whether the wiki is enabled.
	HasWiki any
	// A URL with more information about the repository.
	Homepage any
	// Whether this repository acts as a template that can be used to generate new repositories.
	IsTemplate any
	// The license keyword of the open source license for this repository.
	LicenseTemplate any
	// The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. - `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message.
	MergeCommitMessage any
	// Required when using `merge_commit_message`. The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. - `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name).
	MergeCommitTitle any
	// The name of the repository.
	Name any
	// Whether the repository is private.
	Private any
	// The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. - `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message.
	SquashMergeCommitMessage any
	// Required when using `squash_merge_commit_message`. The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. - `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit).
	SquashMergeCommitTitle any
	// The id of the team that will be granted access to this repository. This is only valid when creating a repository in an organization.
	TeamId any
	// path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute)
	OwnerPath any
	// path parameter, not part of the API's own resource representation
	Repo any
}

type RepositoryAttrs struct {
	// Whether to allow Auto-merge to be used on pull requests.
	AllowAutoMerge any
	// Whether users can fork the repository. This value is computed and read-only, taken from the repository's current settings. (AI-inferred)
	AllowForking any
	// Whether to allow merge commits for pull requests.
	AllowMergeCommit any
	// Whether to allow rebase merges for pull requests.
	AllowRebaseMerge any
	// Whether to allow squash merges for pull requests.
	AllowSquashMerge any
	// A computed boolean that reports whether the repository's 'Allow update branch' feature is enabled, permitting users with push access to update a branch via a pull request. (AI-inferred)
	AllowUpdateBranch any
	// Whether anonymous git access is allowed.
	AnonymousAccessEnabled any
	// The URL template for downloading a repository archive, with placeholders for archive format and reference. (AI-inferred)
	ArchiveUrl any
	// Whether the repository is archived. (AI-inferred)
	Archived any
	// The URL to the repository's assignees endpoint, optionally templated for a specific user (e.g., {/user}). (AI-inferred)
	AssigneesUrl any
	// Whether the repository is initialized with a minimal README.
	AutoInit any
	// The URL template for accessing blob objects in the repository's Git database, with a placeholder for the blob SHA (e.g., `http://api.github.com/repos/{owner}/{repo}/git/blobs{/sha}`). (AI-inferred)
	BlobsUrl any
	// The API endpoint URL for listing branches in this repository. (AI-inferred)
	BranchesUrl any
	// The HTTPS URL used to clone the repository. (AI-inferred)
	CloneUrl any
	// Code of Conduct Simple
	CodeOfConduct any
	// The URL to the collaborators endpoint for this repository, used to access the list of collaborators via the GitHub API. (AI-inferred)
	CollaboratorsUrl any
	// The API URL template for retrieving repository comments, optionally including a comment number. Example: https://api.github.com/repos/{owner}/{repo}/comments{/number} (AI-inferred)
	CommentsUrl any
	// The API endpoint URL for accessing the repository's commits, including a template placeholder '{/sha}' for targeting individual commits. (AI-inferred)
	CommitsUrl any
	// The URL used to compare two revisions of the repository, such as branches or tags. (AI-inferred)
	CompareUrl any
	// The URL template to access repository contents via the GitHub API, with a placeholder for the file path (e.g., https://api.github.com/repos/{owner}/{repo}/contents/{+path}). (AI-inferred)
	ContentsUrl any
	// The API URL to retrieve the list of contributors for the repository. (AI-inferred)
	ContributorsUrl any
	// The system-generated timestamp of when the repository was created. (AI-inferred)
	CreatedAt any
	// The custom properties that were defined for the repository. The keys are the custom property names, and the values are the corresponding custom property values.
	CustomProperties any
	// The name of the repository's default Git branch, such as 'main' or 'master', as set by GitHub. (AI-inferred)
	DefaultBranch any
	// Whether to delete head branches when pull requests are merged
	DeleteBranchOnMerge any
	// The API endpoint URL for accessing and managing deployments of the repository. (AI-inferred)
	DeploymentsUrl any
	// A short description of the repository.
	Description any
	// Returns whether or not this repository disabled.
	Disabled any
	// The API endpoint URL for the downloads associated with this repository. (AI-inferred)
	DownloadsUrl any
	// The URL to the events endpoint for the repository, providing information about repository events. (AI-inferred)
	EventsUrl any
	// Whether the repository is a fork of another repository. (AI-inferred)
	Fork any
	// The number of forks of this repository. (AI-inferred)
	Forks any
	// Number of forks of the repository. (AI-inferred)
	ForksCount any
	// The API URL for listing the forks of the repository. (AI-inferred)
	ForksUrl any
	// The full repository name in the format 'owner/name'. (AI-inferred)
	FullName any
	// The API URL template for accessing the repository's git commits, typically with an optional SHA placeholder. (AI-inferred)
	GitCommitsUrl any
	// The URL to the git refs endpoint for the repository. (AI-inferred)
	GitRefsUrl any
	// The URL to the repository's git tags. (AI-inferred)
	GitTagsUrl any
	// The git:// protocol URL for the repository, as returned by the GitHub API. (AI-inferred)
	GitUrl any
	// The desired language or platform to apply to the .gitignore.
	GitignoreTemplate any
	// Whether discussions are enabled.
	HasDiscussions any
	// Whether downloads are enabled.
	HasDownloads any
	// Whether issues are enabled.
	HasIssues any
	// Indicates whether GitHub Pages is enabled for this repository. (AI-inferred)
	HasPages any
	// Whether projects are enabled.
	HasProjects any
	// Whether pull requests are enabled for this repository. (AI-inferred)
	HasPullRequests any
	// Whether the wiki is enabled.
	HasWiki any
	// A URL with more information about the repository.
	Homepage any
	// The API endpoint URL for managing webhooks on the repository. (AI-inferred)
	HooksUrl any
	// The URL to the repository's HTML page on GitHub. (AI-inferred)
	HtmlUrl any
	// The repository's unique numeric identifier assigned by GitHub. (AI-inferred)
	Id any
	// Whether this repository acts as a template that can be used to generate new repositories.
	IsTemplate any
	// The API URL template for accessing issue comments in the repository, with a placeholder for the comment number. (AI-inferred)
	IssueCommentUrl any
	// The API URL for events related to issues in the repository. This is a computed value provided by the GitHub API. (AI-inferred)
	IssueEventsUrl any
	// The URL to access the list of issues for this repository. (AI-inferred)
	IssuesUrl any
	// The API endpoint URL to retrieve the deploy keys for this repository. This field is computed and read-only. (AI-inferred)
	KeysUrl any
	// The URL to the labels in the repository, as provided by the GitHub API. (AI-inferred)
	LabelsUrl any
	// The primary language used in the repository. (AI-inferred)
	Language any
	// The API endpoint URL that returns the programming languages used in the repository, with the byte count for each language. (AI-inferred)
	LanguagesUrl any
	// License Simple
	License any
	// The license keyword of the open source license for this repository.
	LicenseTemplate any
	// The name of the default branch of the repository, typically 'master' or 'main', as configured for the GitHub repository. (AI-inferred)
	MasterBranch any
	// The default value for a merge commit message. - `PR_TITLE` - default to the pull request's title. - `PR_BODY` - default to the pull request's body. - `BLANK` - default to a blank commit message.
	MergeCommitMessage any
	// Required when using `merge_commit_message`. The default value for a merge commit title. - `PR_TITLE` - default to the pull request's title. - `MERGE_MESSAGE` - default to the classic title for a merge message (e.g., Merge pull request #123 from branch-name).
	MergeCommitTitle any
	// The API endpoint URL for merging branches or pull requests in the repository. (AI-inferred)
	MergesUrl any
	// The API URL for the milestones of this repository. (AI-inferred)
	MilestonesUrl any
	// The URL of the original repository if this repository is a mirror; otherwise, null. This value is set by GitHub. (AI-inferred)
	MirrorUrl any
	// The name of the repository.
	Name any
	// The number of forks of the repository. (AI-inferred)
	NetworkCount any
	// A stable, unique identifier for the repository, generated by GitHub and used to reference the repository in the GraphQL API. (AI-inferred)
	NodeId any
	// The URL to the repository's notifications API endpoint. (AI-inferred)
	NotificationsUrl any
	// The number of open issues currently tracked in the repository. (AI-inferred)
	OpenIssues any
	// The number of open issues in the repository, as reported by the GitHub API. (AI-inferred)
	OpenIssuesCount any
	// A GitHub user.
	Organization any
	// A GitHub user.
	Owner any
	// A repository on GitHub.
	Parent any
	// The repository permissions object contains boolean flags indicating the level of access the authenticated user has for the repository, such as 'admin', 'push', and 'pull'. (AI-inferred)
	Permissions any
	// Whether the repository is private.
	Private any
	// The policy controlling who can create pull requests: all or collaborators_only.
	PullRequestCreationPolicy any
	// The API URL for pull requests in this repository (e.g., https://api.github.com/repos/{owner}/{repo}/pulls{/number}). (AI-inferred)
	PullsUrl any
	// The timestamp of the last push to the repository, in ISO 8601 format. (AI-inferred)
	PushedAt any
	// URL template for accessing the releases of the repository. It may include a placeholder for a specific release ID and is intended for use with API requests. (AI-inferred)
	ReleasesUrl any
	// The security and analysis settings for the repository, such as whether advanced security, secret scanning, and push protection are enabled. This field is computed by GitHub and read-only. (AI-inferred)
	SecurityAndAnalysis any
	// The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0.
	Size any
	// A repository on GitHub.
	Source any
	// The default value for a squash merge commit message: - `PR_BODY` - default to the pull request's body. - `COMMIT_MESSAGES` - default to the branch's commit messages. - `BLANK` - default to a blank commit message.
	SquashMergeCommitMessage any
	// Required when using `squash_merge_commit_message`. The default value for a squash merge commit title: - `PR_TITLE` - default to the pull request's title. - `COMMIT_OR_PR_TITLE` - default to the commit's title (if only one commit) or the pull request's title (when more than one commit).
	SquashMergeCommitTitle any
	// The URL to clone the repository over SSH. (AI-inferred)
	SshUrl any
	// The number of users who have starred the repository on GitHub. (AI-inferred)
	StargazersCount any
	// The URL to the GitHub API endpoint that lists the users who have starred this repository. (AI-inferred)
	StargazersUrl any
	// The URL template for the commit statuses of the repository, with the placeholder {sha} to be replaced by a specific commit SHA. (AI-inferred)
	StatusesUrl any
	// The number of subscribers (users who have subscribed to repository notifications) for this GitHub repository. This is a computed value provided by the GitHub API. (AI-inferred)
	SubscribersCount any
	// URL to retrieve the list of users who have subscribed to (watching) this repository. (AI-inferred)
	SubscribersUrl any
	// The API URL to subscribe to notifications for this repository. (AI-inferred)
	SubscriptionUrl any
	// The URL to access the repository through Subversion (SVN), e.g., https://github.com/owner/repo. (AI-inferred)
	SvnUrl any
	// The URL to fetch the repository's tags via the GitHub API. (AI-inferred)
	TagsUrl any
	// The id of the team that will be granted access to this repository. This is only valid when creating a repository in an organization.
	TeamId any
	// The API URL for the teams associated with this repository. (AI-inferred)
	TeamsUrl any
	// A temporary token that can be used to clone the repository. (AI-inferred)
	TempCloneToken any
	// A repository on GitHub.
	TemplateRepository any
	// The list of topic names associated with the repository. (AI-inferred)
	Topics any
	// URL template for the repository's git trees, used to access tree objects. Contains a placeholder for the tree SHA. (AI-inferred)
	TreesUrl any
	// The timestamp of when the repository was last updated, in ISO 8601 format. This value is set by the system and cannot be modified. (AI-inferred)
	UpdatedAt any
	// The GitHub API URL for the repository (e.g., https://api.github.com/repos/owner/repo). This field is computed and read-only. (AI-inferred)
	Url any
	// True if the repository's squash merge default commit title is configured to use the pull request title; false if it uses something else. (AI-inferred)
	UseSquashPrTitleAsDefault any
	// The repository visibility: public, private, or internal.
	Visibility any
	// The number of users who are watching the repository, i.e., have subscribed to receive notifications for activity in the repository. This is a computed, read-only field. (AI-inferred)
	Watchers any
	// The number of users who are watching the repository (i.e., subscribed to receive notifications about it). This is typically equal to the repository's subscribers count. (AI-inferred)
	WatchersCount any
	// Indicates whether the repository requires contributors to sign off on web-based commits. When true, commits made through the GitHub web interface must include a 'Signed-off-by' trailer. (AI-inferred)
	WebCommitSignoffRequired any
	// path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute)
	OwnerPath any
	// path parameter, not part of the API's own resource representation
	Repo any
}

var Repository = ubx.ResourceBinding{
	WireType: "github_full_repository",
	Fields: ubx.FieldMap{
		"AllowAutoMerge": ubx.FieldSpec{WireName: "allow_auto_merge"},
		"AllowMergeCommit": ubx.FieldSpec{WireName: "allow_merge_commit"},
		"AllowRebaseMerge": ubx.FieldSpec{WireName: "allow_rebase_merge"},
		"AllowSquashMerge": ubx.FieldSpec{WireName: "allow_squash_merge"},
		"AutoInit": ubx.FieldSpec{WireName: "auto_init"},
		"DeleteBranchOnMerge": ubx.FieldSpec{WireName: "delete_branch_on_merge"},
		"Description": ubx.FieldSpec{WireName: "description"},
		"GitignoreTemplate": ubx.FieldSpec{WireName: "gitignore_template"},
		"HasDiscussions": ubx.FieldSpec{WireName: "has_discussions"},
		"HasDownloads": ubx.FieldSpec{WireName: "has_downloads"},
		"HasIssues": ubx.FieldSpec{WireName: "has_issues"},
		"HasProjects": ubx.FieldSpec{WireName: "has_projects"},
		"HasWiki": ubx.FieldSpec{WireName: "has_wiki"},
		"Homepage": ubx.FieldSpec{WireName: "homepage"},
		"IsTemplate": ubx.FieldSpec{WireName: "is_template"},
		"LicenseTemplate": ubx.FieldSpec{WireName: "license_template"},
		"MergeCommitMessage": ubx.FieldSpec{WireName: "merge_commit_message"},
		"MergeCommitTitle": ubx.FieldSpec{WireName: "merge_commit_title"},
		"Name": ubx.FieldSpec{WireName: "name"},
		"Private": ubx.FieldSpec{WireName: "private"},
		"SquashMergeCommitMessage": ubx.FieldSpec{WireName: "squash_merge_commit_message"},
		"SquashMergeCommitTitle": ubx.FieldSpec{WireName: "squash_merge_commit_title"},
		"TeamId": ubx.FieldSpec{WireName: "team_id"},
		"OwnerPath": ubx.FieldSpec{WireName: "owner_path"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
	},
}
