// Code generated by `ubx sdk gen` from github_enterprise_role_list. DO NOT EDIT.
package enterprise

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RoleList_Roles_Enterprise struct {
	AvatarUrl   any
	CreatedAt   any
	Description any
	HtmlUrl     any
	Id          any
	Name        any
	NodeId      any
	Slug        any
	UpdatedAt   any
	WebsiteUrl  any
}

type RoleList_Roles struct {
	CreatedAt   any
	Description any
	Enterprise  any
	Id          any
	Name        any
	Permissions any
	Source      any
	UpdatedAt   any
}

type RoleListConfig struct {
	Enterprise any
}

type RoleListAttrs struct {
	Enterprise any
	// The list of enterprise roles available to the enterprise.
	Roles any
	// The total number of enterprise roles available to the enterprise.
	TotalCount any
}

var RoleList = ubx.DataSourceBinding{
	WireType: "github_enterprise_role_list",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
	},
}
