// Code generated by `ubx sdk gen` from github_team_repository. DO NOT EDIT.
import type { Computed, FieldMap, ResourceBinding } from "@ubx/sdk";

export interface Repository_License {
  htmlUrl?: string | Computed<string>;
  key: string | Computed<string>;
  name: string | Computed<string>;
  nodeId: string | Computed<string>;
  spdxId: string | Computed<string>;
  url: string | Computed<string>;
}

export interface Repository_Owner {
  avatarUrl: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl: string | Computed<string>;
  followersUrl: string | Computed<string>;
  followingUrl: string | Computed<string>;
  gistsUrl: string | Computed<string>;
  gravatarId: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  id: number | Computed<number>;
  login: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId: string | Computed<string>;
  organizationsUrl: string | Computed<string>;
  receivedEventsUrl: string | Computed<string>;
  reposUrl: string | Computed<string>;
  siteAdmin: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  starredUrl: string | Computed<string>;
  subscriptionsUrl: string | Computed<string>;
  type: string | Computed<string>;
  url: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface Repository_Permissions {
  admin: boolean | Computed<boolean>;
  maintain?: boolean | Computed<boolean>;
  pull: boolean | Computed<boolean>;
  push: boolean | Computed<boolean>;
  triage?: boolean | Computed<boolean>;
}

export interface RepositoryConfig {
  /** The permission to grant the team on this repository. We accept the following permissions to be set: `pull`, `triage`, `push`, `maintain`, `admin` and you can also specify a custom repository role name, if the owning organization has defined any. If no permission is specified, the team's `permission` attribute will be used to determine what permission to grant the team on this repository. */
  permission?: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  org: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  teamSlug: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute) */
  ownerPath: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation */
  repo: string | Computed<string>;
  /** path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute) */
  ownerPath2: string | Computed<string>;
}

export interface RepositoryAttrs {
  /** Whether to allow Auto-merge to be used on pull requests. */
  allowAutoMerge: boolean;
  /** Whether to allow forking this repo */
  allowForking: boolean;
  /** Whether to allow merge commits for pull requests. */
  allowMergeCommit: boolean;
  /** Whether to allow rebase merges for pull requests. */
  allowRebaseMerge: boolean;
  /** Whether to allow squash merges for pull requests. */
  allowSquashMerge: boolean;
  /** The URL template for downloading a repository archive, with placeholders for archive format and reference. (AI-inferred) */
  archiveUrl: string;
  /** Whether the repository is archived. */
  archived: boolean;
  /** The URL to the repository's assignees endpoint, optionally templated for a specific user (e.g., {/user}). (AI-inferred) */
  assigneesUrl: string;
  /** The URL template for accessing blob objects in the repository's Git database, with a placeholder for the blob SHA (e.g., `http://api.github.com/repos/{owner}/{repo}/git/blobs{/sha}`). (AI-inferred) */
  blobsUrl: string;
  /** The API endpoint URL for listing branches in this repository. (AI-inferred) */
  branchesUrl: string;
  /** The HTTPS URL used to clone the repository. (AI-inferred) */
  cloneUrl: string;
  /** The URL to the collaborators endpoint for this repository, used to access the list of collaborators via the GitHub API. (AI-inferred) */
  collaboratorsUrl: string;
  /** The API URL template for retrieving repository comments, optionally including a comment number. Example: https://api.github.com/repos/{owner}/{repo}/comments{/number} (AI-inferred) */
  commentsUrl: string;
  /** The API endpoint URL for accessing the repository's commits, including a template placeholder '{/sha}' for targeting individual commits. (AI-inferred) */
  commitsUrl: string;
  /** The URL used to compare two revisions of the repository, such as branches or tags. (AI-inferred) */
  compareUrl: string;
  /** The URL template to access repository contents via the GitHub API, with a placeholder for the file path (e.g., https://api.github.com/repos/{owner}/{repo}/contents/{+path}). (AI-inferred) */
  contentsUrl: string;
  /** The API URL to retrieve the list of contributors for the repository. (AI-inferred) */
  contributorsUrl: string;
  /** The system-generated timestamp of when the repository was created. (AI-inferred) */
  createdAt: string;
  /** The default branch of the repository. */
  defaultBranch: string;
  /** Whether to delete head branches when pull requests are merged */
  deleteBranchOnMerge: boolean;
  /** The API endpoint URL for accessing and managing deployments of the repository. (AI-inferred) */
  deploymentsUrl: string;
  /** A short description of the repository. Optional; if omitted, computed by GitHub. (AI-inferred) */
  description: string;
  /** Returns whether or not this repository disabled. */
  disabled: boolean;
  /** The API endpoint URL for the downloads associated with this repository. (AI-inferred) */
  downloadsUrl: string;
  /** The URL to the events endpoint for the repository, providing information about repository events. (AI-inferred) */
  eventsUrl: string;
  /** Whether the repository is a fork of another repository. (AI-inferred) */
  fork: boolean;
  /** The number of forks of this repository. (AI-inferred) */
  forks: number;
  /** Number of forks of the repository. (AI-inferred) */
  forksCount: number;
  /** The API URL for listing the forks of the repository. (AI-inferred) */
  forksUrl: string;
  /** The full repository name in the format 'owner/name'. (AI-inferred) */
  fullName: string;
  /** The API URL template for accessing the repository's git commits, typically with an optional SHA placeholder. (AI-inferred) */
  gitCommitsUrl: string;
  /** The URL to the git refs endpoint for the repository. (AI-inferred) */
  gitRefsUrl: string;
  /** The URL to the repository's git tags. (AI-inferred) */
  gitTagsUrl: string;
  /** The git:// protocol URL for the repository, as returned by the GitHub API. (AI-inferred) */
  gitUrl: string;
  /** Whether downloads are enabled. */
  hasDownloads: boolean;
  /** Whether issues are enabled. */
  hasIssues: boolean;
  /** Indicates whether GitHub Pages is enabled for this repository. (AI-inferred) */
  hasPages: boolean;
  /** Whether projects are enabled. */
  hasProjects: boolean;
  /** Whether the wiki is enabled. */
  hasWiki: boolean;
  /** A URL with more information about the repository. Optional; if omitted, computed by GitHub. (AI-inferred) */
  homepage: string;
  /** The API endpoint URL for managing webhooks on the repository. (AI-inferred) */
  hooksUrl: string;
  /** The URL to the repository's HTML page on GitHub. (AI-inferred) */
  htmlUrl: string;
  /** Unique identifier of the repository */
  id: number;
  /** Whether this repository acts as a template that can be used to generate new repositories. */
  isTemplate: boolean;
  /** The API URL template for accessing issue comments in the repository, with a placeholder for the comment number. (AI-inferred) */
  issueCommentUrl: string;
  /** The API URL for events related to issues in the repository. This is a computed value provided by the GitHub API. (AI-inferred) */
  issueEventsUrl: string;
  /** The URL to access the list of issues for this repository. (AI-inferred) */
  issuesUrl: string;
  /** The API endpoint URL to retrieve the deploy keys for this repository. This field is computed and read-only. (AI-inferred) */
  keysUrl: string;
  /** The URL to the labels in the repository, as provided by the GitHub API. (AI-inferred) */
  labelsUrl: string;
  /** The primary language used in the repository. (AI-inferred) */
  language: string;
  /** The API endpoint URL that returns the programming languages used in the repository, with the byte count for each language. (AI-inferred) */
  languagesUrl: string;
  /** License Simple */
  license: Repository_License;
  /** The name of the default branch of the repository, typically 'master' or 'main', as configured for the GitHub repository. (AI-inferred) */
  masterBranch: string;
  /** The API endpoint URL for merging branches or pull requests in the repository. (AI-inferred) */
  mergesUrl: string;
  /** The API URL for the milestones of this repository. (AI-inferred) */
  milestonesUrl: string;
  /** The URL of the original repository if this repository is a mirror; otherwise, null. This value is set by GitHub. (AI-inferred) */
  mirrorUrl: string;
  /** The name of the repository. */
  name: string;
  /** The number of forks of the repository. (AI-inferred) */
  networkCount: number;
  /** A stable, unique identifier for the repository, generated by GitHub and used to reference the repository in the GraphQL API. (AI-inferred) */
  nodeId: string;
  /** The URL to the repository's notifications API endpoint. (AI-inferred) */
  notificationsUrl: string;
  /** The number of open issues currently tracked in the repository. (AI-inferred) */
  openIssues: number;
  /** The number of open issues in the repository, as reported by the GitHub API. (AI-inferred) */
  openIssuesCount: number;
  /** A GitHub user. */
  owner: Repository_Owner;
  /** The permission to grant the team on this repository. We accept the following permissions to be set: `pull`, `triage`, `push`, `maintain`, `admin` and you can also specify a custom repository role name, if the owning organization has defined any. If no permission is specified, the team's `permission` attribute will be used to determine what permission to grant the team on this repository. */
  permission: string;
  /** The repository permissions object contains boolean flags indicating the level of access the authenticated user has for the repository, such as 'admin', 'push', and 'pull'. (AI-inferred) */
  permissions: Repository_Permissions;
  /** Whether the repository is private or public. */
  private: boolean;
  /** The API URL for pull requests in this repository (e.g., https://api.github.com/repos/{owner}/{repo}/pulls{/number}). (AI-inferred) */
  pullsUrl: string;
  /** The timestamp of the last push to the repository, in ISO 8601 format. (AI-inferred) */
  pushedAt: string;
  /** URL template for accessing the releases of the repository. It may include a placeholder for a specific release ID and is intended for use with API requests. (AI-inferred) */
  releasesUrl: string;
  /** The real name of the permission role granted here. (AI-inferred) */
  roleName: string;
  /** The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0. (AI-inferred) */
  size: number;
  /** The URL to clone the repository over SSH. (AI-inferred) */
  sshUrl: string;
  /** The number of users who have starred the repository on GitHub. (AI-inferred) */
  stargazersCount: number;
  /** The URL to the GitHub API endpoint that lists the users who have starred this repository. (AI-inferred) */
  stargazersUrl: string;
  /** The URL template for the commit statuses of the repository, with the placeholder {sha} to be replaced by a specific commit SHA. (AI-inferred) */
  statusesUrl: string;
  /** The number of subscribers (users who have subscribed to repository notifications) for this GitHub repository. This is a computed value provided by the GitHub API. (AI-inferred) */
  subscribersCount: number;
  /** URL to retrieve the list of users who have subscribed to (watching) this repository. (AI-inferred) */
  subscribersUrl: string;
  /** The API URL to subscribe to notifications for this repository. (AI-inferred) */
  subscriptionUrl: string;
  /** The URL to access the repository through Subversion (SVN), e.g., https://github.com/owner/repo. (AI-inferred) */
  svnUrl: string;
  /** The URL to fetch the repository's tags via the GitHub API. (AI-inferred) */
  tagsUrl: string;
  /** The API URL for the teams associated with this repository. (AI-inferred) */
  teamsUrl: string;
  /** A temporary token that can be used to clone the repository. (AI-inferred) */
  tempCloneToken: string;
  /** The list of topic names associated with the repository. (AI-inferred) */
  topics: string[];
  /** URL template for the repository's git trees, used to access tree objects. Contains a placeholder for the tree SHA. (AI-inferred) */
  treesUrl: string;
  /** The timestamp of when the repository was last updated, in ISO 8601 format. This value is set by the system and cannot be modified. (AI-inferred) */
  updatedAt: string;
  /** The GitHub API URL for the repository (e.g., https://api.github.com/repos/owner/repo). This field is computed and read-only. (AI-inferred) */
  url: string;
  /** The repository visibility: public, private, or internal. */
  visibility: string;
  /** The number of users who are watching the repository, i.e., have subscribed to receive notifications for activity in the repository. This is a computed, read-only field. (AI-inferred) */
  watchers: number;
  /** The number of users who are watching the repository (i.e., subscribed to receive notifications about it). This is typically equal to the repository's subscribers count. (AI-inferred) */
  watchersCount: number;
  /** Whether to require contributors to sign off on web-based commits */
  webCommitSignoffRequired: boolean;
  /** path parameter, not part of the API's own resource representation */
  org: string;
  /** path parameter, not part of the API's own resource representation */
  teamSlug: string;
  /** path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute) */
  ownerPath: string;
  /** path parameter, not part of the API's own resource representation */
  repo: string;
  /** path parameter, not part of the API's own resource representation (renamed from "owner": that name is already used by a differently-typed, real response attribute) */
  ownerPath2: string;
}

export const Repository: ResourceBinding<RepositoryConfig, RepositoryAttrs> = {
  wireType: "github_team_repository",
  fields: {
    permission: "permission",
    org: "org",
    teamSlug: "team_slug",
    ownerPath: "owner_path",
    repo: "repo",
    ownerPath2: "owner_path2",
  },
};
