// Code generated by `ubx sdk gen` from github_coding_agent. DO NOT EDIT.
package coding

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AgentConfig struct {
	Org any
}

type AgentAttrs struct {
	// The policy for which repositories can use Copilot cloud agent. Can be one of `all`, `selected`, or `none`.
	EnabledRepositories any
	Org any
	// The URL for the selected repositories endpoint. Only present when `enabled_repositories` is `selected`.
	SelectedRepositoriesUrl any
}

var Agent = ubx.DataSourceBinding{
	WireType: "github_coding_agent",
	Fields: ubx.FieldMap{
		"Org": ubx.FieldSpec{WireName: "org"},
	},
}
