# Code generated by `ubx sdk gen` from github_license. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class LicenseConfig:
    featured: Any = None
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class LicenseAttrs:
    featured: Any = None
    page: Any = None
    per_page: Any = None

License = ubx.DataSourceBinding(
    wire_type="github_license",
    fields={
        "featured": ubx.FieldSpec(wire_name="featured"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
