# Code generated by `ubx sdk gen` from github_subscriber. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SubscriberConfig:
    owner: Any = None
    page: Any = None
    per_page: Any = None
    repo: Any = None

@dataclasses.dataclass
class SubscriberAttrs:
    owner: Any = None
    page: Any = None
    per_page: Any = None
    repo: Any = None

Subscriber = ubx.DataSourceBinding(
    wire_type="github_subscriber",
    fields={
        "owner": ubx.FieldSpec(wire_name="owner"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
