// Code generated by `ubx sdk gen` from github_get_all_cost_centers. DO NOT EDIT.
package get

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AllCostCenters_CostCenters_AiCreditPoolState struct {
	CurrentAmount any
	TargetAmount any
}

type AllCostCenters_CostCenters_Resources struct {
	Name any
	Type any
}

type AllCostCenters_CostCenters struct {
	AiCreditPoolEnabled any
	AiCreditPoolState any
	AzureSubscription any
	Id any
	Name any
	Resources any
	State any
}

type AllCostCentersConfig struct {
	Enterprise any
	State any
}

type AllCostCentersAttrs struct {
	CostCenters any
	Enterprise any
	State any
}

var AllCostCenters = ubx.DataSourceBinding{
	WireType: "github_get_all_cost_centers",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
		"State": ubx.FieldSpec{WireName: "state"},
	},
}
