// Code generated by `ubx sdk gen` from github_run. DO NOT EDIT.
package run

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type RunConfig struct {
	Owner any
	Repo any
	RunId any
}

type RunAttrs struct {
	Owner any
	Repo any
	RunId any
}

var Run = ubx.DataSourceBinding{
	WireType: "github_run",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
		"RunId": ubx.FieldSpec{WireName: "run_id"},
	},
}
