// Code generated by `ubx sdk gen` from github_license. DO NOT EDIT.
package license

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type LicenseConfig struct {
	License any
}

type LicenseAttrs struct {
	Body any
	Conditions any
	Description any
	Featured any
	HtmlUrl any
	Implementation any
	Key any
	License any
	Limitations any
	Name any
	NodeId any
	Permissions any
	SpdxId any
	Url any
}

var License = ubx.DataSourceBinding{
	WireType: "github_license",
	Fields: ubx.FieldMap{
		"License": ubx.FieldSpec{WireName: "license"},
	},
}
