// Code generated by `ubx sdk gen` from github_value. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ValueConfig {
  enterprise: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface ValueAttrs {
  enterprise: string;
  page: number;
  perPage: number;
}

export const Value: DataSourceBinding<ValueConfig, ValueAttrs> = {
  wireType: "github_value",
  fields: {
    enterprise: "enterprise",
    page: "page",
    perPage: "per_page",
  },
};
