// Code generated by `ubx sdk gen` from github_pages_deployment_status. DO NOT EDIT.
package pages

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type DeploymentStatusConfig struct {
	// The ID of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
	ArtifactId any
	// The URL of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
	ArtifactUrl any
	// The target environment for this GitHub Pages deployment.
	Environment any
	// The OIDC token issued by GitHub Actions certifying the origin of the deployment.
	OidcToken any
	// A unique string that represents the version of the build for this deployment.
	PagesBuildVersion any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	PagesDeploymentId any
}

type DeploymentStatusAttrs struct {
	// The ID of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
	ArtifactId any
	// The URL of an artifact that contains the .zip or .tar of static assets to deploy. The artifact belongs to the repository. Either `artifact_id` or `artifact_url` are required.
	ArtifactUrl any
	// The target environment for this GitHub Pages deployment.
	Environment any
	// The OIDC token issued by GitHub Actions certifying the origin of the deployment.
	OidcToken any
	// A unique string that represents the version of the build for this deployment.
	PagesBuildVersion any
	// The current status of the deployment.
	Status any
	// path parameter, not part of the API's own resource representation
	Owner any
	// path parameter, not part of the API's own resource representation
	Repo any
	// path parameter, not part of the API's own resource representation
	PagesDeploymentId any
}

var DeploymentStatus = ubx.ResourceBinding{
	WireType: "github_pages_deployment_status",
	Fields: ubx.FieldMap{
		"ArtifactId":        ubx.FieldSpec{WireName: "artifact_id"},
		"ArtifactUrl":       ubx.FieldSpec{WireName: "artifact_url"},
		"Environment":       ubx.FieldSpec{WireName: "environment"},
		"OidcToken":         ubx.FieldSpec{WireName: "oidc_token"},
		"PagesBuildVersion": ubx.FieldSpec{WireName: "pages_build_version"},
		"Owner":             ubx.FieldSpec{WireName: "owner"},
		"Repo":              ubx.FieldSpec{WireName: "repo"},
		"PagesDeploymentId": ubx.FieldSpec{WireName: "pages_deployment_id"},
	},
}
