# Code generated by `ubx sdk gen` from github_release. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Release_Assets_Uploader:
    avatar_url: Any = None
    email: Any = None
    events_url: Any = None
    followers_url: Any = None
    following_url: Any = None
    gists_url: Any = None
    gravatar_id: Any = None
    html_url: Any = None
    id: Any = None
    login: Any = None
    name: Any = None
    node_id: Any = None
    organizations_url: Any = None
    received_events_url: Any = None
    repos_url: Any = None
    site_admin: Any = None
    starred_at: Any = None
    starred_url: Any = None
    subscriptions_url: Any = None
    type: Any = None
    url: Any = None
    user_view_type: Any = None

@dataclasses.dataclass
class Release_Assets:
    browser_download_url: Any = None
    content_type: Any = None
    created_at: Any = None
    digest: Any = None
    download_count: Any = None
    id: Any = None
    label: Any = None
    name: Any = None
    node_id: Any = None
    size: Any = None
    state: Any = None
    updated_at: Any = None
    uploader: Any = None
    url: Any = None

@dataclasses.dataclass
class Release_Reactions:
    confused: Any = None
    eyes: Any = None
    heart: Any = None
    hooray: Any = None
    laugh: Any = None
    rocket: Any = None
    total_count: Any = None
    url: Any = None

@dataclasses.dataclass
class ReleaseConfig:
    # Text describing the contents of the tag.
    body: Any = None
    # If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "[Managing categories for discussions in your repository](https://docs.github.com/enterprise-cloud@latest/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository)."
    discussion_category_name: Any = None
    # `true` to create a draft (unpublished) release, `false` to create a published one.
    draft: Any = None
    # Whether to automatically generate the name and body for this release. If `name` is specified, the specified name will be used; otherwise, a name will be automatically generated. If `body` is specified, the body will be pre-pended to the automatically generated notes.
    generate_release_notes: Any = None
    # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.
    make_latest: Any = None
    # The name of the release.
    name: Any = None
    # `true` to identify the release as a prerelease. `false` to identify the release as a full release.
    prerelease: Any = None
    # The name of the tag.
    tag_name: Any = None
    # Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.
    target_commitish: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    tag: Any = None

@dataclasses.dataclass
class ReleaseAttrs:
    assets: Any = None
    assets_url: Any = None
    # A GitHub user.
    author: Any = None
    # Text describing the contents of the tag.
    body: Any = None
    body_html: Any = None
    body_text: Any = None
    created_at: Any = None
    # If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "[Managing categories for discussions in your repository](https://docs.github.com/enterprise-cloud@latest/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository)."
    discussion_category_name: Any = None
    # The URL of the release discussion.
    discussion_url: Any = None
    # `true` to create a draft (unpublished) release, `false` to create a published one.
    draft: Any = None
    # Whether to automatically generate the name and body for this release. If `name` is specified, the specified name will be used; otherwise, a name will be automatically generated. If `body` is specified, the body will be pre-pended to the automatically generated notes.
    generate_release_notes: Any = None
    html_url: Any = None
    id: Any = None
    # Whether or not the release is immutable.
    immutable: Any = None
    # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.
    make_latest: Any = None
    mentions_count: Any = None
    # The name of the release.
    name: Any = None
    node_id: Any = None
    # `true` to identify the release as a prerelease. `false` to identify the release as a full release.
    prerelease: Any = None
    published_at: Any = None
    reactions: Any = None
    # The name of the tag.
    tag_name: Any = None
    tarball_url: Any = None
    # Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.
    target_commitish: Any = None
    updated_at: Any = None
    upload_url: Any = None
    url: Any = None
    zipball_url: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    tag: Any = None

Release = ubx.ResourceBinding(
    wire_type="github_release",
    fields={
        "body": ubx.FieldSpec(wire_name="body"),
        "discussion_category_name": ubx.FieldSpec(wire_name="discussion_category_name"),
        "draft": ubx.FieldSpec(wire_name="draft"),
        "generate_release_notes": ubx.FieldSpec(wire_name="generate_release_notes"),
        "make_latest": ubx.FieldSpec(wire_name="make_latest"),
        "name": ubx.FieldSpec(wire_name="name"),
        "prerelease": ubx.FieldSpec(wire_name="prerelease"),
        "tag_name": ubx.FieldSpec(wire_name="tag_name"),
        "target_commitish": ubx.FieldSpec(wire_name="target_commitish"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
        "tag": ubx.FieldSpec(wire_name="tag"),
    },
)
