# Code generated by `ubx sdk gen` from github_release. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class Release_Assets_Uploader:
    # The URL for the uploader's avatar image. (AI-inferred)
    avatar_url: Any = None
    # The email address of the user who uploaded the release asset. (AI-inferred)
    email: Any = None
    # The URL to the events endpoint for the uploader user, providing access to the user's public events. (AI-inferred)
    events_url: Any = None
    # The API URL to the uploader's list of followers on GitHub. (AI-inferred)
    followers_url: Any = None
    # The URL to the GitHub API endpoint that lists the users this uploader is following. (AI-inferred)
    following_url: Any = None
    # The URL to the user's gists. (AI-inferred)
    gists_url: Any = None
    # The Gravatar ID for the user, which is the MD5 hash of the user's email address. It is used to construct the user's avatar URL via Gravatar. In current API responses, this field is often an empty string. (AI-inferred)
    gravatar_id: Any = None
    # The URL to the uploader's GitHub profile page. (AI-inferred)
    html_url: Any = None
    # The unique numeric identifier for the GitHub user who uploaded the release asset. (AI-inferred)
    id: Any = None
    # The GitHub username of the user who uploaded the release asset. (AI-inferred)
    login: Any = None
    # The display name of the user who uploaded the release asset. (AI-inferred)
    name: Any = None
    # The unique identifier for the uploader's user object in GitHub's GraphQL API. (AI-inferred)
    node_id: Any = None
    # The API URL to fetch the list of organizations the uploader belongs to, typically in the form https://api.github.com/users/{username}/orgs. (AI-inferred)
    organizations_url: Any = None
    # The URL to the received events endpoint for the uploader user, providing a list of events that this user has received. (AI-inferred)
    received_events_url: Any = None
    # The API endpoint URL that lists the repositories owned by the uploader user. (AI-inferred)
    repos_url: Any = None
    # Whether the uploader is a site administrator on GitHub. (AI-inferred)
    site_admin: Any = None
    starred_at: Any = None
    # The URL to retrieve the list of repositories starred by this uploader user. (AI-inferred)
    starred_url: Any = None
    # The API endpoint URL for the uploader user's GitHub subscriptions, typically pointing to a list of repositories the user is subscribed to. (AI-inferred)
    subscriptions_url: Any = None
    # The type of GitHub user account that uploaded the asset. Typically 'User' or 'Bot'. (AI-inferred)
    type: Any = None
    # The GitHub API URL for the uploader user. (AI-inferred)
    url: Any = None
    user_view_type: Any = None

@dataclasses.dataclass
class Release_Assets:
    # The URL to download the release asset directly in a browser. This is the web-based link that users can visit to download the file without using the API. (AI-inferred)
    browser_download_url: Any = None
    # The MIME type of the release asset, e.g., application/zip or application/x-gzip. (AI-inferred)
    content_type: Any = None
    # The date and time when the GitHub release asset was created, formatted as an ISO 8601 timestamp. (AI-inferred)
    created_at: Any = None
    # The cryptographic digest (typically SHA-256) of the release asset file, used to verify its integrity. (AI-inferred)
    digest: Any = None
    # Number of times this release asset has been downloaded. (AI-inferred)
    download_count: Any = None
    # The unique identifier for the release asset, as assigned by GitHub. (AI-inferred)
    id: Any = None
    # The user-defined label for the release asset, which is displayed in the GitHub UI; may be null if no label is set. (AI-inferred)
    label: Any = None
    # The name of the release asset, typically the filename. (AI-inferred)
    name: Any = None
    # The GraphQL node ID of the release asset. (AI-inferred)
    node_id: Any = None
    # The size of the release asset in bytes. (AI-inferred)
    size: Any = None
    # The state of the release asset, either `uploaded` or `open`. (AI-inferred)
    state: Any = None
    # The timestamp of when the release asset was last updated. (AI-inferred)
    updated_at: Any = None
    # The GitHub user who uploaded the release asset. This is a user object containing standard GitHub user fields such as login, id, and avatar_url. (AI-inferred)
    uploader: Any = None
    # The API URL for the release asset. (AI-inferred)
    url: Any = None

@dataclasses.dataclass
class Release_Reactions:
    # The number of users who reacted with the 'confused' emoji to this release. (AI-inferred)
    confused: Any = None
    # The number of 'eyes' emoji reactions on the release. (AI-inferred)
    eyes: Any = None
    # The count of heart reactions (❤️) on the release. (AI-inferred)
    heart: Any = None
    # The number of 'hooray' reactions (🎉) on the GitHub release. (AI-inferred)
    hooray: Any = None
    # The number of users who reacted with the 'laugh' (😂) emoji on this GitHub release. (AI-inferred)
    laugh: Any = None
    # The count of rocket (🚀) reactions on the GitHub release. (AI-inferred)
    rocket: Any = None
    # The total count of reactions on the release. (AI-inferred)
    total_count: Any = None
    # The URL to the API endpoint that returns the reactions for this GitHub release. (AI-inferred)
    url: Any = None

@dataclasses.dataclass
class ReleaseConfig:
    # Text describing the contents of the tag.
    body: Any = None
    # If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "[Managing categories for discussions in your repository](https://docs.github.com/enterprise-cloud@latest/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository)."
    discussion_category_name: Any = None
    # `true` to create a draft (unpublished) release, `false` to create a published one.
    draft: Any = None
    # Whether to automatically generate the name and body for this release. If `name` is specified, the specified name will be used; otherwise, a name will be automatically generated. If `body` is specified, the body will be pre-pended to the automatically generated notes.
    generate_release_notes: Any = None
    # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.
    make_latest: Any = None
    # The name of the release.
    name: Any = None
    # `true` to identify the release as a prerelease. `false` to identify the release as a full release.
    prerelease: Any = None
    # The name of the tag.
    tag_name: Any = None
    # Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.
    target_commitish: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    tag: Any = None

@dataclasses.dataclass
class ReleaseAttrs:
    # The list of release assets (files) attached to the GitHub release. (AI-inferred)
    assets: Any = None
    # The API URL for the assets associated with this GitHub release. (AI-inferred)
    assets_url: Any = None
    # A GitHub user.
    author: Any = None
    # Text describing the contents of the tag.
    body: Any = None
    # The rendered HTML version of the release body or description. (AI-inferred)
    body_html: Any = None
    # The full body text of the GitHub release, typically containing release notes or a description. (AI-inferred)
    body_text: Any = None
    # The timestamp of when the release was created, in ISO 8601 format (e.g., 2023-01-01T00:00:00Z). (AI-inferred)
    created_at: Any = None
    # If specified, a discussion of the specified category is created and linked to the release. The value must be a category that already exists in the repository. For more information, see "[Managing categories for discussions in your repository](https://docs.github.com/enterprise-cloud@latest/discussions/managing-discussions-for-your-community/managing-categories-for-discussions-in-your-repository)."
    discussion_category_name: Any = None
    # The URL of the release discussion.
    discussion_url: Any = None
    # `true` to create a draft (unpublished) release, `false` to create a published one.
    draft: Any = None
    # Whether to automatically generate the name and body for this release. If `name` is specified, the specified name will be used; otherwise, a name will be automatically generated. If `body` is specified, the body will be pre-pended to the automatically generated notes.
    generate_release_notes: Any = None
    # The GitHub web URL where the release can be viewed. (AI-inferred)
    html_url: Any = None
    # The unique numeric identifier for the release, automatically assigned by GitHub when the release is created. (AI-inferred)
    id: Any = None
    # Whether or not the release is immutable.
    immutable: Any = None
    # Specifies whether this release should be set as the latest release for the repository. Drafts and prereleases cannot be set as latest. Defaults to `true` for newly published releases. `legacy` specifies that the latest release should be determined based on the release creation date and higher semantic version.
    make_latest: Any = None
    mentions_count: Any = None
    # The name of the release.
    name: Any = None
    # The GraphQL Node ID of the GitHub release. (AI-inferred)
    node_id: Any = None
    # `true` to identify the release as a prerelease. `false` to identify the release as a full release.
    prerelease: Any = None
    # The timestamp of when the release was published. This field is computed and cannot be set by the user. (AI-inferred)
    published_at: Any = None
    # An object summarizing reactions to the release, mapping each reaction type (e.g., +1, -1, laugh, hooray) to the count received. This field is automatically computed and read-only. (AI-inferred)
    reactions: Any = None
    # The name of the tag.
    tag_name: Any = None
    # The URL to download the tarball source archive for this release. (AI-inferred)
    tarball_url: Any = None
    # Specifies the commitish value that determines where the Git tag is created from. Can be any branch or commit SHA. Unused if the Git tag already exists. Default: the repository's default branch.
    target_commitish: Any = None
    # The timestamp of the last update to the release, in ISO 8601 format (e.g., '2023-01-15T12:34:56Z'). This value is set by the system and cannot be modified directly. (AI-inferred)
    updated_at: Any = None
    # The URL endpoint for uploading assets to this GitHub release. It is a computed, read-only value and typically includes a placeholder for the asset name. (AI-inferred)
    upload_url: Any = None
    # The API URL that points to this release on GitHub (e.g., https://api.github.com/repos/{owner}/{repo}/releases/{id}). (AI-inferred)
    url: Any = None
    # The URL of the zip archive of the source code for this release. (AI-inferred)
    zipball_url: Any = None
    # path parameter, not part of the API's own resource representation
    owner: Any = None
    # path parameter, not part of the API's own resource representation
    repo: Any = None
    # path parameter, not part of the API's own resource representation
    tag: Any = None

Release = ubx.ResourceBinding(
    wire_type="github_release",
    fields={
        "body": ubx.FieldSpec(wire_name="body"),
        "discussion_category_name": ubx.FieldSpec(wire_name="discussion_category_name"),
        "draft": ubx.FieldSpec(wire_name="draft"),
        "generate_release_notes": ubx.FieldSpec(wire_name="generate_release_notes"),
        "make_latest": ubx.FieldSpec(wire_name="make_latest"),
        "name": ubx.FieldSpec(wire_name="name"),
        "prerelease": ubx.FieldSpec(wire_name="prerelease"),
        "tag_name": ubx.FieldSpec(wire_name="tag_name"),
        "target_commitish": ubx.FieldSpec(wire_name="target_commitish"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
        "tag": ubx.FieldSpec(wire_name="tag"),
    },
)
