# Code generated by `ubx sdk gen` from github_code_frequency. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class FrequencyConfig:
    owner: Any = None
    repo: Any = None

@dataclasses.dataclass
class FrequencyAttrs:
    owner: Any = None
    repo: Any = None

Frequency = ubx.DataSourceBinding(
    wire_type="github_code_frequency",
    fields={
        "owner": ubx.FieldSpec(wire_name="owner"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
