# Code generated by `ubx sdk gen` from github_code_quality. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class QualityConfig:
    after: Any = None
    before: Any = None
    direction: Any = None
    owner: Any = None
    per_page: Any = None
    repo: Any = None
    state: Any = None

@dataclasses.dataclass
class QualityAttrs:
    after: Any = None
    before: Any = None
    direction: Any = None
    owner: Any = None
    per_page: Any = None
    repo: Any = None
    state: Any = None

Quality = ubx.DataSourceBinding(
    wire_type="github_code_quality",
    fields={
        "after": ubx.FieldSpec(wire_name="after"),
        "before": ubx.FieldSpec(wire_name="before"),
        "direction": ubx.FieldSpec(wire_name="direction"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "repo": ubx.FieldSpec(wire_name="repo"),
        "state": ubx.FieldSpec(wire_name="state"),
    },
)
