# Code generated by `ubx sdk gen` from github_codespaces_permissions_check_for_devcontainer. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class PermissionsCheckForDevcontainerConfig:
    devcontainer_path: Any = None
    owner: Any = None
    ref: Any = None
    repo: Any = None

@dataclasses.dataclass
class PermissionsCheckForDevcontainerAttrs:
    # Whether the user has accepted the permissions defined by the devcontainer config
    accepted: Any = None
    devcontainer_path: Any = None
    owner: Any = None
    ref: Any = None
    repo: Any = None

PermissionsCheckForDevcontainer = ubx.DataSourceBinding(
    wire_type="github_codespaces_permissions_check_for_devcontainer",
    fields={
        "devcontainer_path": ubx.FieldSpec(wire_name="devcontainer_path"),
        "owner": ubx.FieldSpec(wire_name="owner"),
        "ref": ubx.FieldSpec(wire_name="ref"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
