# Code generated by `ubx sdk gen` from github_codespaces_secret_list. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SecretList_Secrets:
    created_at: Any = None
    name: Any = None
    selected_repositories_url: Any = None
    updated_at: Any = None
    visibility: Any = None

@dataclasses.dataclass
class SecretListConfig:
    page: Any = None
    per_page: Any = None

@dataclasses.dataclass
class SecretListAttrs:
    page: Any = None
    per_page: Any = None
    secrets: Any = None
    total_count: Any = None

SecretList = ubx.DataSourceBinding(
    wire_type="github_codespaces_secret_list",
    fields={
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
    },
)
