// Code generated by `ubx sdk gen` from github_repo. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RepoConfig {
  enterprise: string | Computed<string>;
}

export interface RepoAttrs {
  enterprise: string;
}

export const Repo: DataSourceBinding<RepoConfig, RepoAttrs> = {
  wireType: "github_repo",
  fields: {
    enterprise: "enterprise",
  },
};
