# Code generated by `ubx sdk gen` from github_billing_usage_summary_report_ghe. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class UsageSummaryReportGhe_CostCenter:
    # The unique identifier of the cost center.
    id: Any = None
    # The name of the cost center.
    name: Any = None

@dataclasses.dataclass
class UsageSummaryReportGhe_TimePeriod:
    # The day for the usage report.
    day: Any = None
    # The month for the usage report.
    month: Any = None
    # The year for the usage report.
    year: Any = None

@dataclasses.dataclass
class UsageSummaryReportGhe_UsageItems:
    discount_amount: Any = None
    discount_quantity: Any = None
    gross_amount: Any = None
    gross_quantity: Any = None
    net_amount: Any = None
    net_quantity: Any = None
    price_per_unit: Any = None
    product: Any = None
    sku: Any = None
    unit_type: Any = None

@dataclasses.dataclass
class UsageSummaryReportGheConfig:
    cost_center_id: Any = None
    day: Any = None
    enterprise: Any = None
    month: Any = None
    organization: Any = None
    product: Any = None
    repository: Any = None
    sku: Any = None
    year: Any = None

@dataclasses.dataclass
class UsageSummaryReportGheAttrs:
    cost_center: Any = None
    cost_center_id: Any = None
    day: Any = None
    enterprise: Any = None
    month: Any = None
    organization: Any = None
    product: Any = None
    repository: Any = None
    sku: Any = None
    time_period: Any = None
    usage_items: Any = None
    year: Any = None

UsageSummaryReportGhe = ubx.DataSourceBinding(
    wire_type="github_billing_usage_summary_report_ghe",
    fields={
        "cost_center_id": ubx.FieldSpec(wire_name="cost_center_id"),
        "day": ubx.FieldSpec(wire_name="day"),
        "enterprise": ubx.FieldSpec(wire_name="enterprise"),
        "month": ubx.FieldSpec(wire_name="month"),
        "organization": ubx.FieldSpec(wire_name="organization"),
        "product": ubx.FieldSpec(wire_name="product"),
        "repository": ubx.FieldSpec(wire_name="repository"),
        "sku": ubx.FieldSpec(wire_name="sku"),
        "year": ubx.FieldSpec(wire_name="year"),
    },
)
