// Code generated by `ubx sdk gen` from github_actions_cache_retention_limit_for_repository. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface CacheRetentionLimitForRepositoryConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface CacheRetentionLimitForRepositoryAttrs {
  /** The maximum number of days to keep caches in this repository. */
  maxCacheRetentionDays: number;
  owner: string;
  repo: string;
}

export const CacheRetentionLimitForRepository: DataSourceBinding<CacheRetentionLimitForRepositoryConfig, CacheRetentionLimitForRepositoryAttrs> = {
  wireType: "github_actions_cache_retention_limit_for_repository",
  fields: {
    owner: "owner",
    repo: "repo",
  },
};
