// Code generated by `ubx sdk gen` from github_actions_fork_pr_contributor_approval. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface ForkPrContributorApprovalConfig {
  enterprise: string | Computed<string>;
}

export interface ForkPrContributorApprovalAttrs {
  /** The policy that controls when fork PR workflows require approval from a maintainer. */
  approvalPolicy: string;
  enterprise: string;
}

export const ForkPrContributorApproval: DataSourceBinding<ForkPrContributorApprovalConfig, ForkPrContributorApprovalAttrs> = {
  wireType: "github_actions_fork_pr_contributor_approval",
  fields: {
    enterprise: "enterprise",
  },
};
