// Code generated by `ubx sdk gen` from github_actions_hosted_runner_custom_image. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface HostedRunnerCustomImageConfig {
  enterprise: string | Computed<string>;
  imageDefinitionId: number | Computed<number>;
}

export interface HostedRunnerCustomImageAttrs {
  enterprise: string;
  /** The ID of the image. Use this ID for the `image` parameter when creating a new larger runner. */
  id: number;
  imageDefinitionId: number;
  /** The latest image version associated with the image. */
  latestVersion: string;
  /** Display name for this image. */
  name: string;
  /** The operating system of the image. */
  platform: string;
  /** The image provider. */
  source: string;
  /** The number of image versions associated with the image. */
  state: string;
  /** Total size of all the image versions in GB. */
  totalVersionsSize: number;
  /** The number of image versions associated with the image. */
  versionsCount: number;
}

export const HostedRunnerCustomImage: DataSourceBinding<HostedRunnerCustomImageConfig, HostedRunnerCustomImageAttrs> = {
  wireType: "github_actions_hosted_runner_custom_image",
  fields: {
    enterprise: "enterprise",
    imageDefinitionId: "image_definition_id",
  },
};
