// Code generated by `ubx sdk gen` from github_actions_variable_list. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface VariableList_Variables {
  createdAt?: string | Computed<string>;
  name?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  value?: string | Computed<string>;
}

export interface VariableListConfig {
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  repo: string | Computed<string>;
}

export interface VariableListAttrs {
  owner: string;
  page: number;
  perPage: number;
  repo: string;
  totalCount: number;
  variables: VariableList_Variables[];
}

export const VariableList: DataSourceBinding<VariableListConfig, VariableListAttrs> = {
  wireType: "github_actions_variable_list",
  fields: {
    owner: "owner",
    page: "page",
    perPage: "per_page",
    repo: "repo",
  },
};
