// Code generated by `ubx sdk gen` from github_actions_workflow_access_to_repository. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface WorkflowAccessToRepositoryConfig {
  owner: string | Computed<string>;
  repo: string | Computed<string>;
}

export interface WorkflowAccessToRepositoryAttrs {
  /** Defines the level of access that workflows outside of the repository have to actions and reusable workflows within the repository. `none` means the access is only possible from workflows in this repository. `user` level access allows sharing across user owned private repositories only. `organization` level access allows sharing across the organization. `enterprise` level access allows sharing across the enterprise. */
  accessLevel: string;
  owner: string;
  repo: string;
}

export const WorkflowAccessToRepository: DataSourceBinding<WorkflowAccessToRepositoryConfig, WorkflowAccessToRepositoryAttrs> = {
  wireType: "github_actions_workflow_access_to_repository",
  fields: {
    owner: "owner",
    repo: "repo",
  },
};
