// Code generated by `ubx sdk gen` from github_minimal_repository. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Repository_Repositories_CodeOfConduct {
  body?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface Repository_Repositories_License {
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  spdxId?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface Repository_Repositories_Owner {
  avatarUrl?: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl?: string | Computed<string>;
  followersUrl?: string | Computed<string>;
  followingUrl?: string | Computed<string>;
  gistsUrl?: string | Computed<string>;
  gravatarId?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  login?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  organizationsUrl?: string | Computed<string>;
  receivedEventsUrl?: string | Computed<string>;
  reposUrl?: string | Computed<string>;
  siteAdmin?: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  starredUrl?: string | Computed<string>;
  subscriptionsUrl?: string | Computed<string>;
  type?: string | Computed<string>;
  url?: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface Repository_Repositories_Permissions {
  admin?: boolean | Computed<boolean>;
  maintain?: boolean | Computed<boolean>;
  pull?: boolean | Computed<boolean>;
  push?: boolean | Computed<boolean>;
  triage?: boolean | Computed<boolean>;
}

export interface Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity {
  status?: string | Computed<string>;
}

export interface Repository_Repositories_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions_Reviewers {
  mode?: string | Computed<string>;
  reviewerId?: number | Computed<number>;
  reviewerType?: string | Computed<string>;
}

export interface Repository_Repositories_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions {
  reviewers?: Repository_Repositories_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions_Reviewers[] | Computed<Repository_Repositories_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions_Reviewers[]>;
}

export interface Repository_Repositories_SecurityAndAnalysis {
  advancedSecurity?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  codeSecurity?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  dependabotSecurityUpdates?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanning?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanningAiDetection?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanningDelegatedAlertDismissal?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanningDelegatedBypass?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanningDelegatedBypassOptions?: Repository_Repositories_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions | Computed<Repository_Repositories_SecurityAndAnalysis_SecretScanningDelegatedBypassOptions>;
  secretScanningNonProviderPatterns?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanningPushProtection?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
  secretScanningValidityChecks?: Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity | Computed<Repository_Repositories_SecurityAndAnalysis_AdvancedSecurity>;
}

export interface Repository_Repositories {
  allowForking?: boolean | Computed<boolean>;
  archiveUrl?: string | Computed<string>;
  archived?: boolean | Computed<boolean>;
  assigneesUrl?: string | Computed<string>;
  blobsUrl?: string | Computed<string>;
  branchesUrl?: string | Computed<string>;
  cloneUrl?: string | Computed<string>;
  codeOfConduct?: Repository_Repositories_CodeOfConduct | Computed<Repository_Repositories_CodeOfConduct>;
  collaboratorsUrl?: string | Computed<string>;
  commentsUrl?: string | Computed<string>;
  commitsUrl?: string | Computed<string>;
  compareUrl?: string | Computed<string>;
  contentsUrl?: string | Computed<string>;
  contributorsUrl?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  customProperties?: unknown | Computed<unknown>;
  defaultBranch?: string | Computed<string>;
  deleteBranchOnMerge?: boolean | Computed<boolean>;
  deploymentsUrl?: string | Computed<string>;
  description?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  downloadsUrl?: string | Computed<string>;
  eventsUrl?: string | Computed<string>;
  fork?: boolean | Computed<boolean>;
  forks?: number | Computed<number>;
  forksCount?: number | Computed<number>;
  forksUrl?: string | Computed<string>;
  fullName?: string | Computed<string>;
  gitCommitsUrl?: string | Computed<string>;
  gitRefsUrl?: string | Computed<string>;
  gitTagsUrl?: string | Computed<string>;
  gitUrl?: string | Computed<string>;
  hasDiscussions?: boolean | Computed<boolean>;
  hasDownloads?: boolean | Computed<boolean>;
  hasIssues?: boolean | Computed<boolean>;
  hasPages?: boolean | Computed<boolean>;
  hasProjects?: boolean | Computed<boolean>;
  hasPullRequests?: boolean | Computed<boolean>;
  hasWiki?: boolean | Computed<boolean>;
  homepage?: string | Computed<string>;
  hooksUrl?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  isTemplate?: boolean | Computed<boolean>;
  issueCommentUrl?: string | Computed<string>;
  issueEventsUrl?: string | Computed<string>;
  issuesUrl?: string | Computed<string>;
  keysUrl?: string | Computed<string>;
  labelsUrl?: string | Computed<string>;
  language?: string | Computed<string>;
  languagesUrl?: string | Computed<string>;
  license?: Repository_Repositories_License | Computed<Repository_Repositories_License>;
  mergesUrl?: string | Computed<string>;
  milestonesUrl?: string | Computed<string>;
  mirrorUrl?: string | Computed<string>;
  name?: string | Computed<string>;
  networkCount?: number | Computed<number>;
  nodeId?: string | Computed<string>;
  notificationsUrl?: string | Computed<string>;
  openIssues?: number | Computed<number>;
  openIssuesCount?: number | Computed<number>;
  owner?: Repository_Repositories_Owner | Computed<Repository_Repositories_Owner>;
  permissions?: Repository_Repositories_Permissions | Computed<Repository_Repositories_Permissions>;
  private?: boolean | Computed<boolean>;
  pullRequestCreationPolicy?: string | Computed<string>;
  pullsUrl?: string | Computed<string>;
  pushedAt?: string | Computed<string>;
  releasesUrl?: string | Computed<string>;
  roleName?: string | Computed<string>;
  securityAndAnalysis?: Repository_Repositories_SecurityAndAnalysis | Computed<Repository_Repositories_SecurityAndAnalysis>;
  size?: number | Computed<number>;
  sshUrl?: string | Computed<string>;
  stargazersCount?: number | Computed<number>;
  stargazersUrl?: string | Computed<string>;
  statusesUrl?: string | Computed<string>;
  subscribersCount?: number | Computed<number>;
  subscribersUrl?: string | Computed<string>;
  subscriptionUrl?: string | Computed<string>;
  svnUrl?: string | Computed<string>;
  tagsUrl?: string | Computed<string>;
  teamsUrl?: string | Computed<string>;
  tempCloneToken?: string | Computed<string>;
  topics?: string[] | Computed<string[]>;
  treesUrl?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  visibility?: string | Computed<string>;
  watchers?: number | Computed<number>;
  watchersCount?: number | Computed<number>;
  webCommitSignoffRequired?: boolean | Computed<boolean>;
}

export interface RepositoryConfig {
  org: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  runnerGroupId: number | Computed<number>;
}

export interface RepositoryAttrs {
  org: string;
  page: number;
  perPage: number;
  repositories: Repository_Repositories[];
  runnerGroupId: number;
  totalCount: number;
}

export const Repository: DataSourceBinding<RepositoryConfig, RepositoryAttrs> = {
  wireType: "github_minimal_repository",
  fields: {
    org: "org",
    page: "page",
    perPage: "per_page",
    runnerGroupId: "runner_group_id",
  },
};
