// Code generated by `ubx sdk gen` from github_key. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface KeyConfig {
  owner: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  repo: string | Computed<string>;
}

export interface KeyAttrs {
  owner: string;
  page: number;
  perPage: number;
  repo: string;
}

export const Key: DataSourceBinding<KeyConfig, KeyAttrs> = {
  wireType: "github_key",
  fields: {
    owner: "owner",
    page: "page",
    perPage: "per_page",
    repo: "repo",
  },
};
