# Code generated by `ubx sdk gen` from github_copilot_space_resource. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class SpaceResource_Resources:
    copilot_chat_attachment_id: Any = None
    created_at: Any = None
    id: Any = None
    metadata: Any = None
    resource_type: Any = None
    updated_at: Any = None

@dataclasses.dataclass
class SpaceResourceConfig:
    org: Any = None
    space_number: Any = None

@dataclasses.dataclass
class SpaceResourceAttrs:
    org: Any = None
    # The list of resources attached to this Copilot Space.
    resources: Any = None
    space_number: Any = None

SpaceResource = ubx.DataSourceBinding(
    wire_type="github_copilot_space_resource",
    fields={
        "org": ubx.FieldSpec(wire_name="org"),
        "space_number": ubx.FieldSpec(wire_name="space_number"),
    },
)
