# Code generated by `ubx sdk gen` from github_statuse. DO NOT EDIT.
from __future__ import annotations

import dataclasses
from typing import Any

import ubx_sdk as ubx

@dataclasses.dataclass
class StatuseConfig:
    owner: Any = None
    page: Any = None
    per_page: Any = None
    ref: Any = None
    repo: Any = None

@dataclasses.dataclass
class StatuseAttrs:
    owner: Any = None
    page: Any = None
    per_page: Any = None
    ref: Any = None
    repo: Any = None

Statuse = ubx.DataSourceBinding(
    wire_type="github_statuse",
    fields={
        "owner": ubx.FieldSpec(wire_name="owner"),
        "page": ubx.FieldSpec(wire_name="page"),
        "per_page": ubx.FieldSpec(wire_name="per_page"),
        "ref": ubx.FieldSpec(wire_name="ref"),
        "repo": ubx.FieldSpec(wire_name="repo"),
    },
)
