// Code generated by `ubx sdk gen` from github_server_statistics. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface StatisticsConfig {
  dateEnd?: string | Computed<string>;
  dateStart?: string | Computed<string>;
  enterpriseOrOrg: string | Computed<string>;
}

export interface StatisticsAttrs {
  dateEnd: string;
  dateStart: string;
  enterpriseOrOrg: string;
}

export const Statistics: DataSourceBinding<StatisticsConfig, StatisticsAttrs> = {
  wireType: "github_server_statistics",
  fields: {
    dateEnd: "date_end",
    dateStart: "date_start",
    enterpriseOrOrg: "enterprise_or_org",
  },
};
