// Code generated by `ubx sdk gen` from github_gist. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface GistConfig {
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
  since?: string | Computed<string>;
}

export interface GistAttrs {
  page: number;
  perPage: number;
  since: string;
}

export const Gist: DataSourceBinding<GistConfig, GistAttrs> = {
  wireType: "github_gist",
  fields: {
    page: "page",
    perPage: "per_page",
    since: "since",
  },
};
