// Code generated by `ubx sdk gen` from github_gist_simple. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface Simple_Files {
  content?: string | Computed<string>;
  encoding?: string | Computed<string>;
  filename?: string | Computed<string>;
  language?: string | Computed<string>;
  rawUrl?: string | Computed<string>;
  size?: number | Computed<number>;
  truncated?: boolean | Computed<boolean>;
  type?: string | Computed<string>;
}

export interface Simple_ForkOf_Files {
  filename?: string | Computed<string>;
  language?: string | Computed<string>;
  rawUrl?: string | Computed<string>;
  size?: number | Computed<number>;
  type?: string | Computed<string>;
}

export interface Simple_ForkOf_Owner {
  avatarUrl: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl: string | Computed<string>;
  followersUrl: string | Computed<string>;
  followingUrl: string | Computed<string>;
  gistsUrl: string | Computed<string>;
  gravatarId: string | Computed<string>;
  htmlUrl: string | Computed<string>;
  id: number | Computed<number>;
  login: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId: string | Computed<string>;
  organizationsUrl: string | Computed<string>;
  receivedEventsUrl: string | Computed<string>;
  reposUrl: string | Computed<string>;
  siteAdmin: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  starredUrl: string | Computed<string>;
  subscriptionsUrl: string | Computed<string>;
  type: string | Computed<string>;
  url: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface Simple_ForkOf {
  comments: number | Computed<number>;
  commentsEnabled?: boolean | Computed<boolean>;
  commentsUrl: string | Computed<string>;
  commitsUrl: string | Computed<string>;
  createdAt: string | Computed<string>;
  description: string | Computed<string>;
  files: Record<string, Simple_ForkOf_Files> | Computed<Record<string, Simple_ForkOf_Files>>;
  forks?: unknown[] | Computed<unknown[]>;
  forksUrl: string | Computed<string>;
  gitPullUrl: string | Computed<string>;
  gitPushUrl: string | Computed<string>;
  history?: unknown[] | Computed<unknown[]>;
  htmlUrl: string | Computed<string>;
  id: string | Computed<string>;
  nodeId: string | Computed<string>;
  /** A GitHub user. */
  owner?: Simple_ForkOf_Owner | Computed<Simple_ForkOf_Owner>;
  public: boolean | Computed<boolean>;
  truncated?: boolean | Computed<boolean>;
  updatedAt: string | Computed<string>;
  url: string | Computed<string>;
  /** A GitHub user. */
  user: Simple_ForkOf_Owner | Computed<Simple_ForkOf_Owner>;
}

export interface Simple_Forks_User_Plan {
  collaborators?: number | Computed<number>;
  name?: string | Computed<string>;
  privateRepos?: number | Computed<number>;
  space?: number | Computed<number>;
}

export interface Simple_Forks_User {
  avatarUrl?: string | Computed<string>;
  bio?: string | Computed<string>;
  blog?: string | Computed<string>;
  collaborators?: number | Computed<number>;
  company?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  diskUsage?: number | Computed<number>;
  email?: string | Computed<string>;
  eventsUrl?: string | Computed<string>;
  followers?: number | Computed<number>;
  followersUrl?: string | Computed<string>;
  following?: number | Computed<number>;
  followingUrl?: string | Computed<string>;
  gistsUrl?: string | Computed<string>;
  gravatarId?: string | Computed<string>;
  hireable?: boolean | Computed<boolean>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  location?: string | Computed<string>;
  login?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  notificationEmail?: string | Computed<string>;
  organizationsUrl?: string | Computed<string>;
  ownedPrivateRepos?: number | Computed<number>;
  plan?: Simple_Forks_User_Plan | Computed<Simple_Forks_User_Plan>;
  privateGists?: number | Computed<number>;
  publicGists?: number | Computed<number>;
  publicRepos?: number | Computed<number>;
  receivedEventsUrl?: string | Computed<string>;
  reposUrl?: string | Computed<string>;
  siteAdmin?: boolean | Computed<boolean>;
  starredUrl?: string | Computed<string>;
  subscriptionsUrl?: string | Computed<string>;
  totalPrivateRepos?: number | Computed<number>;
  twitterUsername?: string | Computed<string>;
  type?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface Simple_Forks {
  createdAt?: string | Computed<string>;
  id?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  user?: Simple_Forks_User | Computed<Simple_Forks_User>;
}

export interface Simple_History_ChangeStatus {
  additions?: number | Computed<number>;
  deletions?: number | Computed<number>;
  total?: number | Computed<number>;
}

export interface Simple_History {
  changeStatus?: Simple_History_ChangeStatus | Computed<Simple_History_ChangeStatus>;
  committedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  user?: Simple_ForkOf_Owner | Computed<Simple_ForkOf_Owner>;
  version?: string | Computed<string>;
}

export interface SimpleConfig {
  gistId: string | Computed<string>;
  sha: string | Computed<string>;
}

export interface SimpleAttrs {
  comments: number;
  commentsEnabled: boolean;
  commentsUrl: string;
  commitsUrl: string;
  createdAt: string;
  description: string;
  files: Record<string, Simple_Files>;
  /** Gist */
  forkOf: Simple_ForkOf;
  forks: Simple_Forks[];
  forksUrl: string;
  gistId: string;
  gitPullUrl: string;
  gitPushUrl: string;
  history: Simple_History[];
  htmlUrl: string;
  id: string;
  nodeId: string;
  /** A GitHub user. */
  owner: Simple_ForkOf_Owner;
  public: boolean;
  sha: string;
  truncated: boolean;
  updatedAt: string;
  url: string;
  user: string;
}

export const Simple: DataSourceBinding<SimpleConfig, SimpleAttrs> = {
  wireType: "github_gist_simple",
  fields: {
    gistId: "gist_id",
    sha: "sha",
  },
};
