// Code generated by `ubx sdk gen` from github_following. DO NOT EDIT.
package following

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type FollowingConfig struct {
	Page    any
	PerPage any
}

type FollowingAttrs struct {
	Page    any
	PerPage any
}

var Following = ubx.DataSourceBinding{
	WireType: "github_following",
	Fields: ubx.FieldMap{
		"Page":    ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
