// Code generated by `ubx sdk gen` from github_assignment. DO NOT EDIT.
package assignment

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type AssignmentConfig struct {
	AssignmentId any
	Page any
	PerPage any
}

type AssignmentAttrs struct {
	AssignmentId any
	Page any
	PerPage any
}

var Assignment = ubx.DataSourceBinding{
	WireType: "github_assignment",
	Fields: ubx.FieldMap{
		"AssignmentId": ubx.FieldSpec{WireName: "assignment_id"},
		"Page": ubx.FieldSpec{WireName: "page"},
		"PerPage": ubx.FieldSpec{WireName: "per_page"},
	},
}
