// Code generated by `ubx sdk gen` from github_protected_branch_pull_request_review. DO NOT EDIT.
package protected

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type BranchPullRequestReview_BypassPullRequestAllowances_Apps_Owner struct {
	AvatarUrl any
	CreatedAt any
	Description any
	Email any
	EventsUrl any
	FollowersUrl any
	FollowingUrl any
	GistsUrl any
	GravatarId any
	HtmlUrl any
	Id any
	Login any
	Name any
	NodeId any
	OrganizationsUrl any
	ReceivedEventsUrl any
	ReposUrl any
	SiteAdmin any
	Slug any
	StarredAt any
	StarredUrl any
	SubscriptionsUrl any
	Type any
	UpdatedAt any
	Url any
	UserViewType any
	WebsiteUrl any
}

type BranchPullRequestReview_BypassPullRequestAllowances_Apps_Permissions struct {
	Checks any
	Contents any
	Deployments any
	Issues any
	Metadata any
}

type BranchPullRequestReview_BypassPullRequestAllowances_Apps struct {
	ClientId any
	CreatedAt any
	Description any
	Events any
	ExternalUrl any
	HtmlUrl any
	Id any
	InstallationsCount any
	Name any
	NodeId any
	Owner any
	Permissions any
	Slug any
	UpdatedAt any
}

type BranchPullRequestReview_BypassPullRequestAllowances_Teams_Parent struct {
	Description any
	EnterpriseId any
	HtmlUrl any
	Id any
	LdapDn any
	MembersUrl any
	Name any
	NodeId any
	NotificationSetting any
	OrganizationId any
	Permission any
	Privacy any
	RepositoriesUrl any
	Slug any
	Type any
	Url any
}

type BranchPullRequestReview_BypassPullRequestAllowances_Teams_Permissions struct {
	Admin any
	Maintain any
	Pull any
	Push any
	Triage any
}

type BranchPullRequestReview_BypassPullRequestAllowances_Teams struct {
	AccessSource any
	Description any
	EnterpriseId any
	HtmlUrl any
	Id any
	MembersUrl any
	Name any
	NodeId any
	NotificationSetting any
	OrganizationId any
	Parent any
	Permission any
	Permissions any
	Privacy any
	RepositoriesUrl any
	Slug any
	Type any
	Url any
}

type BranchPullRequestReview_BypassPullRequestAllowances_Users struct {
	AvatarUrl any
	Email any
	EventsUrl any
	FollowersUrl any
	FollowingUrl any
	GistsUrl any
	GravatarId any
	HtmlUrl any
	Id any
	Login any
	Name any
	NodeId any
	OrganizationsUrl any
	ReceivedEventsUrl any
	ReposUrl any
	SiteAdmin any
	StarredAt any
	StarredUrl any
	SubscriptionsUrl any
	Type any
	Url any
	UserViewType any
}

type BranchPullRequestReview_BypassPullRequestAllowances struct {
	// The list of apps allowed to bypass pull request requirements.
	Apps any
	// The list of teams allowed to bypass pull request requirements.
	Teams any
	// The list of users allowed to bypass pull request requirements.
	Users any
}

type BranchPullRequestReview_DismissalRestrictions struct {
	// The list of apps with review dismissal access.
	Apps any
	// The list of teams with review dismissal access.
	Teams any
	TeamsUrl any
	Url any
	// The list of users with review dismissal access.
	Users any
	UsersUrl any
}

type BranchPullRequestReviewConfig struct {
	Branch any
	Owner any
	Repo any
}

type BranchPullRequestReviewAttrs struct {
	Branch any
	// Allow specific users, teams, or apps to bypass pull request requirements.
	BypassPullRequestAllowances any
	DismissStaleReviews any
	DismissalRestrictions any
	Owner any
	Repo any
	RequireCodeOwnerReviews any
	// Whether the most recent push must be approved by someone other than the person who pushed it.
	RequireLastPushApproval any
	RequiredApprovingReviewCount any
	Url any
}

var BranchPullRequestReview = ubx.DataSourceBinding{
	WireType: "github_protected_branch_pull_request_review",
	Fields: ubx.FieldMap{
		"Branch": ubx.FieldSpec{WireName: "branch"},
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
	},
}
