// Code generated by `ubx sdk gen` from github_budget. DO NOT EDIT.
package budget

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Budget_Budgets_BudgetAlerting struct {
	AlertRecipients any
	WillAlert       any
}

type Budget_Budgets struct {
	BudgetAlerting      any
	BudgetAmount        any
	BudgetEntityName    any
	BudgetProductSku    any
	BudgetScope         any
	BudgetType          any
	ConsumedAmount      any
	Id                  any
	PreventFurtherUsage any
	User                any
}

type Budget_EffectiveBudget struct {
	// The budget amount for the effective budget.
	BudgetAmount any
	// The consumed amount for the specified user within the effective budget.
	ConsumedAmount any
	// The unique identifier of the effective budget.
	Id any
}

type BudgetConfig struct {
	Enterprise any
	Page       any
	PerPage    any
	Scope      any
	User       any
}

type BudgetAttrs struct {
	// Array of budget objects for the enterprise
	Budgets any
	// Effective user-level budget details returned when the response is scoped with the `user` query parameter.
	EffectiveBudget any
	Enterprise      any
	// Indicates if there are more pages of results available (maps to hasNextPage from billing platform)
	HasNextPage any
	Page        any
	PerPage     any
	Scope       any
	// Total number of budgets matching the query
	TotalCount any
	User       any
}

var Budget = ubx.DataSourceBinding{
	WireType: "github_budget",
	Fields: ubx.FieldMap{
		"Enterprise": ubx.FieldSpec{WireName: "enterprise"},
		"Page":       ubx.FieldSpec{WireName: "page"},
		"PerPage":    ubx.FieldSpec{WireName: "per_page"},
		"Scope":      ubx.FieldSpec{WireName: "scope"},
		"User":       ubx.FieldSpec{WireName: "user"},
	},
}
