// Code generated by `ubx sdk gen` from github_codeowners_errors. DO NOT EDIT.
package codeowners

import ubx "github.com/ubiquex/ubx-sdk-go/runtime"

type Errors_Errors struct {
	Column any
	Kind any
	Line any
	Message any
	Path any
	Source any
	Suggestion any
}

type ErrorsConfig struct {
	Owner any
	Ref any
	Repo any
}

type ErrorsAttrs struct {
	Errors any
	Owner any
	Ref any
	Repo any
}

var Errors = ubx.DataSourceBinding{
	WireType: "github_codeowners_errors",
	Fields: ubx.FieldMap{
		"Owner": ubx.FieldSpec{WireName: "owner"},
		"Ref": ubx.FieldSpec{WireName: "ref"},
		"Repo": ubx.FieldSpec{WireName: "repo"},
	},
}
