// Code generated by `ubx sdk gen` from github_self_hosted_runner. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface HostedRunner_Repositories_CodeSearchIndexStatus {
  lexicalCommitSha?: string | Computed<string>;
  lexicalSearchOk?: boolean | Computed<boolean>;
}

export interface HostedRunner_Repositories_License {
  htmlUrl?: string | Computed<string>;
  key?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  spdxId?: string | Computed<string>;
  url?: string | Computed<string>;
}

export interface HostedRunner_Repositories_Owner {
  avatarUrl?: string | Computed<string>;
  email?: string | Computed<string>;
  eventsUrl?: string | Computed<string>;
  followersUrl?: string | Computed<string>;
  followingUrl?: string | Computed<string>;
  gistsUrl?: string | Computed<string>;
  gravatarId?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  login?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  organizationsUrl?: string | Computed<string>;
  receivedEventsUrl?: string | Computed<string>;
  reposUrl?: string | Computed<string>;
  siteAdmin?: boolean | Computed<boolean>;
  starredAt?: string | Computed<string>;
  starredUrl?: string | Computed<string>;
  subscriptionsUrl?: string | Computed<string>;
  type?: string | Computed<string>;
  url?: string | Computed<string>;
  userViewType?: string | Computed<string>;
}

export interface HostedRunner_Repositories_Permissions {
  admin?: boolean | Computed<boolean>;
  maintain?: boolean | Computed<boolean>;
  pull?: boolean | Computed<boolean>;
  push?: boolean | Computed<boolean>;
  triage?: boolean | Computed<boolean>;
}

export interface HostedRunner_Repositories {
  allowAutoMerge?: boolean | Computed<boolean>;
  allowForking?: boolean | Computed<boolean>;
  allowMergeCommit?: boolean | Computed<boolean>;
  allowRebaseMerge?: boolean | Computed<boolean>;
  allowSquashMerge?: boolean | Computed<boolean>;
  allowUpdateBranch?: boolean | Computed<boolean>;
  anonymousAccessEnabled?: boolean | Computed<boolean>;
  archiveUrl?: string | Computed<string>;
  archived?: boolean | Computed<boolean>;
  assigneesUrl?: string | Computed<string>;
  blobsUrl?: string | Computed<string>;
  branchesUrl?: string | Computed<string>;
  cloneUrl?: string | Computed<string>;
  codeSearchIndexStatus?: HostedRunner_Repositories_CodeSearchIndexStatus | Computed<HostedRunner_Repositories_CodeSearchIndexStatus>;
  collaboratorsUrl?: string | Computed<string>;
  commentsUrl?: string | Computed<string>;
  commitsUrl?: string | Computed<string>;
  compareUrl?: string | Computed<string>;
  contentsUrl?: string | Computed<string>;
  contributorsUrl?: string | Computed<string>;
  createdAt?: string | Computed<string>;
  defaultBranch?: string | Computed<string>;
  deleteBranchOnMerge?: boolean | Computed<boolean>;
  deploymentsUrl?: string | Computed<string>;
  description?: string | Computed<string>;
  disabled?: boolean | Computed<boolean>;
  downloadsUrl?: string | Computed<string>;
  eventsUrl?: string | Computed<string>;
  fork?: boolean | Computed<boolean>;
  forks?: number | Computed<number>;
  forksCount?: number | Computed<number>;
  forksUrl?: string | Computed<string>;
  fullName?: string | Computed<string>;
  gitCommitsUrl?: string | Computed<string>;
  gitRefsUrl?: string | Computed<string>;
  gitTagsUrl?: string | Computed<string>;
  gitUrl?: string | Computed<string>;
  hasDiscussions?: boolean | Computed<boolean>;
  hasDownloads?: boolean | Computed<boolean>;
  hasIssues?: boolean | Computed<boolean>;
  hasPages?: boolean | Computed<boolean>;
  hasProjects?: boolean | Computed<boolean>;
  hasPullRequests?: boolean | Computed<boolean>;
  hasWiki?: boolean | Computed<boolean>;
  homepage?: string | Computed<string>;
  hooksUrl?: string | Computed<string>;
  htmlUrl?: string | Computed<string>;
  id?: number | Computed<number>;
  isTemplate?: boolean | Computed<boolean>;
  issueCommentUrl?: string | Computed<string>;
  issueEventsUrl?: string | Computed<string>;
  issuesUrl?: string | Computed<string>;
  keysUrl?: string | Computed<string>;
  labelsUrl?: string | Computed<string>;
  language?: string | Computed<string>;
  languagesUrl?: string | Computed<string>;
  license?: HostedRunner_Repositories_License | Computed<HostedRunner_Repositories_License>;
  masterBranch?: string | Computed<string>;
  mergeCommitMessage?: string | Computed<string>;
  mergeCommitTitle?: string | Computed<string>;
  mergesUrl?: string | Computed<string>;
  milestonesUrl?: string | Computed<string>;
  mirrorUrl?: string | Computed<string>;
  name?: string | Computed<string>;
  nodeId?: string | Computed<string>;
  notificationsUrl?: string | Computed<string>;
  openIssues?: number | Computed<number>;
  openIssuesCount?: number | Computed<number>;
  owner?: HostedRunner_Repositories_Owner | Computed<HostedRunner_Repositories_Owner>;
  permissions?: HostedRunner_Repositories_Permissions | Computed<HostedRunner_Repositories_Permissions>;
  private?: boolean | Computed<boolean>;
  pullRequestCreationPolicy?: string | Computed<string>;
  pullsUrl?: string | Computed<string>;
  pushedAt?: string | Computed<string>;
  releasesUrl?: string | Computed<string>;
  size?: number | Computed<number>;
  squashMergeCommitMessage?: string | Computed<string>;
  squashMergeCommitTitle?: string | Computed<string>;
  sshUrl?: string | Computed<string>;
  stargazersCount?: number | Computed<number>;
  stargazersUrl?: string | Computed<string>;
  starredAt?: string | Computed<string>;
  statusesUrl?: string | Computed<string>;
  subscribersUrl?: string | Computed<string>;
  subscriptionUrl?: string | Computed<string>;
  svnUrl?: string | Computed<string>;
  tagsUrl?: string | Computed<string>;
  teamsUrl?: string | Computed<string>;
  tempCloneToken?: string | Computed<string>;
  topics?: string[] | Computed<string[]>;
  treesUrl?: string | Computed<string>;
  updatedAt?: string | Computed<string>;
  url?: string | Computed<string>;
  useSquashPrTitleAsDefault?: boolean | Computed<boolean>;
  visibility?: string | Computed<string>;
  watchers?: number | Computed<number>;
  watchersCount?: number | Computed<number>;
  webCommitSignoffRequired?: boolean | Computed<boolean>;
}

export interface HostedRunnerConfig {
  org: string | Computed<string>;
  page?: number | Computed<number>;
  perPage?: number | Computed<number>;
}

export interface HostedRunnerAttrs {
  org: string;
  page: number;
  perPage: number;
  repositories: HostedRunner_Repositories[];
  totalCount: number;
}

export const HostedRunner: DataSourceBinding<HostedRunnerConfig, HostedRunnerAttrs> = {
  wireType: "github_self_hosted_runner",
  fields: {
    org: "org",
    page: "page",
    perPage: "per_page",
  },
};
