// Code generated by `ubx sdk gen` from github_private_registrie. DO NOT EDIT.
import type { Computed, FieldMap, DataSourceBinding } from "@ubx/sdk";

export interface RegistrieConfig {
  org: string | Computed<string>;
}

export interface RegistrieAttrs {
  /** The Base64 encoded public key. */
  key: string;
  /** The identifier for the key. */
  keyId: string;
  org: string;
}

export const Registrie: DataSourceBinding<RegistrieConfig, RegistrieAttrs> = {
  wireType: "github_private_registrie",
  fields: {
    org: "org",
  },
};
